pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/cmd.go
already reviewed via https://github.com/openshift/service-serving-cert-signer/pull/7
cobra RunE prints a useless help message on failures, so fatal works better.
The actual error was lost during failures in non-leader elected cases.
=> error handling fixes for controllers

pkg/assets/assets.go, pkg/assets/assets_test.go
We will need this in every master operator repo to render the manifests for bootkube.
Instead of copying this, make it shared.
/cc @deads2k
/cc @sttts
=> add helper for processing and writing assets using go templates

pkg/config/helpers/client.go, pkg/config/helpers/config_refs.go
Adds helper methods direct against api types.  Fixes name consistency
=> align client helpers to types

pkg/operator/resource/resourcemerge/generic_config_merger.go, pkg/operator/resource/resourcemerge/generic_config_merger_test.go
If we decode into maps we can prevent conflicting object meta, but we don't require it in all cases.  If we want to require it, we can do that too, but we can do it without trying the decoding stack.
/assign @soltysh
=> don't require type meta to merge

pkg/operator/v1alpha1helpers/helper_test.go, pkg/operator/v1alpha1helpers/helpers.go
Adds a generic helper that can be used by any operator to ensure that a config exists
=> Add EnsureOperatorConfigExists helper function

OWNERS
As discussed, any new externally consumable code needs agreement among the approvers. Goal: don't turn this into a sink of trivial helpers.
=> OWNERS: add myself as approver

alpha-build-machinery/make/targets/help.mk
@mfojtik this issue you were having with bash (shell) < 4.x
/assign @sttts
=> Make mac with prehistoric shell happy by using the old redirection syntax

pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go, pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go, pkg/operator/staticpod/controller/deployment/deployment_controller_test.go
Refactors backing resource and deployment unit tests to evaluate test client actions instead of mocking with test client reactors. 
I left the installer test as it was, since it needs to do more trickery to kubeclient than other tests.
Fixes: https://github.com/openshift/library-go/issues/71
/cc @deads2k
=> refactor staticpod unit tests

alpha-build-machinery/make/targets/openshift/deps.mk
```
COMPATIBILITY
Historic versions of the cp utility had a -r option.  This implementation supports that option; however, its use is strongly discouraged, as it does not cor-
rectly copy special files, symbolic links, or fifo's.
```
=> build: make verify-deps work on osx

alpha-build-machinery/make/lib/golang.mk
This fix will build all commands that are represented as directories under `./cmd` instead of doing `./cmd/...` which does not result into any binary.
/cc @tnozicka 
/cc @soltysh
=> build: fix GO_BUILD_PACKAGES to build binaries

.gitignore, alpha-build-machinery/make/targets/openshift/deps.mk, vendor/bitbucket.org/ww/goautoneg/.hg_archival.txt
- ~~use compatible `cp -R` instead of `cp -r`.~~ merged in @mfojtik's PR.
- gitignore `.hg_archival.txt` files as there content depends on the hg version installed
- make `verify-deps` make target ignore gitignored files
=> alpha-build-machinery: fix verify-deps

pkg/config/serving/server.go
Without having the metav1 schema, unauthorized requests for metrics will eventually panic the server:
https://gist.github.com/mfojtik/f8101d0ea3092709b93da3c2429c38aa
=> serving: register metav1 types to api server

pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go
This provides the core of controller loop that operators can use to drive config observation wiring in their process.  It manages retries, merging, error handling, and condition reporting.
=> add skeleton for operator config observation

pkg/operator/events/recorder.go, pkg/operator/events/recorder_deployment.go, pkg/operator/events/recorder_deployment_test.go, pkg/operator/events/recorder_test.go
Adding event recorder interface for recording events from operators. Recorder should be wired to resourceapply package and observer package to. Events published by operator are for historical action debugging.
This implementation require the ObjectReference to be passed to NewRecorder in the factory when the operator is started. It means that the `EVENT_SOURCE_REPLICASET_NAME` will have to be passed via downward API into the container running the operator and the replica set is then used as the object we recording the events against. These events should be also propagated to the owning deployment.
/cc @deads2k 
/cc @sttts
=> Add simple event recorder

pkg/controller/fileobserver/observer_polling.go
The observer should never accept to observe an empty file. If it does, it is a programming error and we should panic.
/cc @sttts
=> observer: fail when requesting empty filename for observing

pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/cmd.go, pkg/controller/controllercmd/flags.go
Allows the config flag to be optional (satisfying @derekwaynecarr ) and injects it into the start method (satisfying @enj).  I think both are possible using the unstructured scheme and type coersion
/assign @enj
=> expose the configuration file content for a controller

pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/cmd.go, pkg/controller/controllercmd/flags.go
StartFunc was refactored to take a ControllerContext struct.  This prevents the function signature from expanding indefinitely and makes is easier to add new fields without breaking every caller.
Signed-off-by: Monis Khan <mkhan@redhat.com>
=> Pass controller context struct to StartFunc

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/rbac.go
There is API level defaulting that a diff has to understand to avoid needless updates.
=> fix diff calculations for roleref and services

pkg/operator/resource/resourceapply/apps.go, pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go, pkg/operator/resource/resourceapply/event_helpers.go, pkg/operator/resource/resourceapply/generic.go, pkg/operator/resource/resourceapply/generic_test.go, pkg/operator/resource/resourceapply/rbac.go, pkg/operator/resource/resourceapply/storage.go, pkg/operator/staticpod/controller/revision/deployment_controller.go, pkg/operator/v1alpha1staticpod/controller/deployment/deployment_controller.go, pkg/operator/v1alpha1staticpod/controller/deployment/deployment_controller_test.go, pkg/operator/v1alpha1staticpod/controllers.go
This wire event recorder to all resourceapply functions. Any operator using these should pass an event recorder.
=> events: wire events directly to resourceapply

pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go
This is needed so we can wire events into https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/pkg/operator/configobservation/etcd/observe_etcd.go#L17 
/cc @deads2k 
/cc @sttts
=> wire events to config observer functions

pkg/operator/resource/resourceapply/event_helpers.go
Fixes the output which is currently:
```
2 minutes   ServiceCreated                Created Service "openshift-kube-apiserver/apiserver" because it was missing
2 minutes   ClusterRoleBindingCreated     Created ClusterRoleBinding "system:openshift:operator:openshift-kube-apiserver-installer" because it was missing
2 minutes   ServiceAccountCreated         Created ServiceAccount "openshift-kube-apiserver/installer-sa" because it was missing
2 minutes   Created                       Created  "openshift-kube-apiserver/etcd-serving-ca" because it was missing
3 minutes   Created                       Created  "openshift-kube-apiserver/etcd-client" because it was missing
3 minutes   ConfigMapCreated              Created ConfigMap "openshift-kube-apiserver/deployment-kube-apiserver-config" because …
```
=> events: fix reporting kind from resource apply

pkg/proc/reaper.go, pkg/proc/reaper_unsupported.go
On Linux pid 1 processes (container processes) must reap their children.
This library copied directly from openshift/origin.
=> Add proc reaper for PID 1 containerized processes

pkg/controller/controllercmd/builder.go
This fixes the panic when operator is shutting down because fileobserver observed a change in local file. If there are multiple files changed, this will call the callback multiple times, leading to panic about closing a closed channel.
This change will cause it to close the channel just once.
/cc @sttts 
/cc @smarterclayton
=> fileobserve: handle panic when multiple files are changed

pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
This worked during manual testing because the clusteroperator was present. It now works even when it isn't.
=> fix the clusteroperator status update

pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go
Reverts openshift/library-go#131
Just because one observer has failed, does not mean that all observed config is invalid.  Since the previous value is available to the config observer, returning a failure *and* the config to merge in a valid choice and we need to be able to observe config generally.
=> Revert "config obverser: do not write invalid configs"

pkg/operator/configobserver/network/observe_network.go, pkg/operator/configobserver/network/observe_networking_test.go
This code is used by multiple operators.
=> configobserver: move install-config CIDR readers here

pkg/operator/staticpod/controller/installer/installer_controller.go
Available and progressing is determinable from the overall status of the node.  This pull automatically sets those conditions and provides a spot for level driven evaluation.
/assign @sttts @mfojtik
=> manage available and progressing status for static pods

glide.lock, pkg/operator/staticpod/prune/cmd.go, pkg/operator/staticpod/prune/cmd_test.go, vendor/github.com/openshift/api/config/v1/types.go, vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go, vendor/vbom.ml/util/.gitignore, vendor/vbom.ml/util/LICENSE, vendor/vbom.ml/util/README.md, vendor/vbom.ml/util/cmd/short-regexp/main.go, vendor/vbom.ml/util/doc.go, vendor/vbom.ml/util/regexp.go, vendor/vbom.ml/util/regexp_test.go, vendor/vbom.ml/util/rope/README.md, vendor/vbom.ml/util/rope/concat.go, vendor/vbom.ml/util/rope/concat_test.go, vendor/vbom.ml/util/rope/debug.go, vendor/vbom.ml/util/rope/leaf.go, vendor/vbom.ml/util/rope/leaf_test.go, vendor/vbom.ml/util/rope/node.go, vendor/vbom.ml/util/rope/node_test.go, vendor/vbom.ml/util/rope/reader.go, vendor/vbom.ml/util/rope/reader_test.go, vendor/vbom.ml/util/rope/rebalance.go, vendor/vbom.ml/util/rope/rebalance_test.go, vendor/vbom.ml/util/rope/rope.go, vendor/vbom.ml/util/rope/rope_test.go, vendor/vbom.ml/util/sortorder/README.md, vendor/vbom.ml/util/sortorder/doc.go, vendor/vbom.ml/util/sortorder/natsort.go, vendor/vbom.ml/util/sortorder/natsort_test.go
Contains just the `Prune` command for static pod installer revisions first created in https://github.com/openshift/library-go/pull/82
part of https://jira.coreos.com/browse/MSTR-221
=> Static pod revision history prune command

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/cabundle_test.go, pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
per @mfojtik's suggestion, this switches us to use structs for each bit of a cert rotation logic
/assign @sttts
=> segregate and simplify the cert rotation config

pkg/config/clusteroperator/v1helpers/status.go, pkg/config/clusteroperator/v1helpers/status_test.go, pkg/operator/status/status_controller.go
This change provides more details into what changed in operator status conditions, instead of just printing the status changed.
/cc @deads2k 
/cc @smarterclayton
=> events: provide more details when operator status change

pkg/operator/resource/resourceapply/core.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/staticpod/controller/revision/deployment_controller.go, pkg/operator/staticpod/controller/revision/deployment_controller_test.go
When creating a new static pod deployment, sets the ownerrefs for copied resources to be the new revision-status configmap (see https://github.com/openshift/cluster-kube-apiserver-operator/pull/179), to be used for garbage collection as part of https://jira.coreos.com/browse/MSTR-221
=> Set revision status ownerrefs when creating new revision

pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
sa sync was never set, so we paniced
/assign @mfojtik @damemi
=> fix panic in service monitor sync

pkg/config/clusteroperator/v1helpers/status.go, pkg/config/clusteroperator/v1helpers/status_test.go, pkg/operator/status/status_controller.go
Makes sure we always have a message about what is changing.  If we don't see an explicit change, we will serialize it to json.  If we end up with a cardinality problem on events, we can deal with it, but this is a fallthrough to find our ghost writes.
/assign @sanchezl
=> add better event information and glog info on diff

pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go, pkg/operator/staticpod/controller/revision/deployment_controller_test.go
Rework of https://github.com/openshift/library-go/pull/162 to prune API resources in the pruner control loop instead of the pruner pod, by adding a separate workqueueand running each in their own routines
=> API resource pruning in pruner control loop

pkg/operator/resource/resourceapply/core.go
Return the existing service when an update is not required.
Signed-off-by: Monis Khan <mkhan@redhat.com>
@openshift/sig-master
=> Return current service in ApplyService

pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
otherwise we end up being failing until servicemonitor comes along and that stops the cvo.
=> don't fail on servicemonitor update failure

pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go
This is needed to handle cases of dynamic locations for @mrogers950 and @bparees
=> add resource syncing to configobservation

pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/resourcesynccontroller/resourcesync_controller_test.go, pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go, pkg/operator/staticpod/controller/revision/revision_controller.go, pkg/operator/staticpod/controller/revision/revision_controller_test.go, pkg/operator/staticpod/controllers.go, pkg/operator/v1helpers/core_getters.go, pkg/operator/v1helpers/fake_informers.go, pkg/operator/v1helpers/informers.go
This pull creates capital to create cached configmap and secret getters which should dramatically reduce qps on repeated sync and apply calls
/assign @juanvallejo @damemi
=> create a cached version of getters to reduce qps

pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/client_cert_rotation_controller_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
This makes us wait for 10% of available overlap for the signer to age before we sign.  Assuming we refresh the target a lot more often than the signer, this works.
Also adds a time based trigger every minute to check if we need to do work.
/assign @sttts
=> rotate only after the signer has had some time to propogate

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/client_cert_rotation_controller.go
We need external visibility into issues with cert rotation, so this adds more conditions to our operator.
=> add conditions for cert rotators

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controller/revision/revision_controller.go, pkg/operator/staticpod/controller/revision/revision_controller_test.go, pkg/operator/staticpod/controllers.go, pkg/operator/staticpod/installerpod/cmd.go, pkg/operator/staticpod/installerpod/cmd_test.go
This lets us pass optional configMaps to the controller that will not halt progress if they don't exist.
@deads2k @openshift/sig-security 
re: https://github.com/openshift/cluster-kube-apiserver-operator/pull/185
=> Add optional configMaps to revision controller

pkg/operator/status/version.go, pkg/operator/status/version_test.go
The locker was empty so we paniced.  I can actually use a mutex like the rest of the code, so do that instead.
@eparis
=> prevent panic on missing mutex

Makefile, alpha-build-machinery/Makefile, alpha-build-machinery/make/default.example.mk, alpha-build-machinery/make/default.example.mk.help.log, alpha-build-machinery/make/examples/multiple-binaries/Makefile, alpha-build-machinery/make/examples/multiple-binaries/Makefile.test, alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log, alpha-build-machinery/make/examples/multiple-binaries/cmd/oc/main.go, alpha-build-machinery/make/examples/multiple-binaries/cmd/openshift/main.go, alpha-build-machinery/make/golang.example.mk, alpha-build-machinery/make/golang.example.mk.help.log, alpha-build-machinery/make/golang.mk, alpha-build-machinery/make/lib/golang.mk, alpha-build-machinery/make/operator.example.mk, alpha-build-machinery/make/operator.example.mk.help.log, alpha-build-machinery/make/targets/golang/build.mk
`go build` will produce a binary only with one package, otherwise it just compiles the code and no binary is produced, so we now call `go build` for each binary.
/cc @juanvallejo @soltysh @sttts @mfojtik
=> Fix building multiple binaries

pkg/serviceability/serviceability.go
The current behavior of writing the file to the current directory is convenient but doesn't allow parallel profiles to be gathered for things like `openshift-tests` which uses child processes, or
short lived commands that you want to profile in a loop.
Callers may now append `-tmp` to the mode and profiling will write to the temp directory which will create a `profile-RANDOM/mode.pprof` file that is unique across runs.
=> Add mutex and trace profiles to serviceability, handle unique

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
When the installer pods fail, we are failing and our status should reflect that.  This makes a new condition (so we stay single writer) for `NodeInstallerFailing` and sets it appropriately with a summary.
@eparis your "kubelet never starts" clusters will now fail in the CVO quickly.
/assign @mfojtik @damemi 
@damemi please bump our repos to fix this status.
=> set failing status for failing installer pod

pkg/operator/staticpod/controller/installer/bindata/bindata.go, pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
This PR sets the podPriorityClass to for the static pod installer pods as these pods should be scheduled first in all cases. AFAIK this does not guarantee the memory for them.
xref: https://github.com/openshift/library-go/issues/208
=> staticpod: set priority class and tolerations for installer pod

pkg/operator/staticpod/controller/revision/revision_controller.go
`required` might be nil when looping on an optional resource.
@deads2k @openshift/sig-auth
=> Fix possible nil deref on isLatestRevisionCurrent reason

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go
sets ownerrefs for pruning pods for revision pruning (and refactors previously merged installerpod ownerrefs, see https://github.com/openshift/library-go/pull/211)
=> add pruner pod ownerrefs for revision

pkg/operator/certrotation/target.go
to rotate CSR signers we need to produce signing certs as a target.  We want it as a target so that we can rotate the overall trust slower than the individual signers themselves. This gives confidence that rotation works without forcing all consumers to rotate at the same time.
/assign @sttts
=> add signer target for rotation

pkg/operator/staticpod/controller/installer/installer_controller_test.go
This add two more tests to installer to exercise the behavior when nodes are on different revision levels.
=> installer: add test to exercise revision skew

pkg/operator/status/status_controller.go
```
2019-02-05 07:38:53 +0100 CET  SignerUpdateRequired         "managed-kube-apiserver-serving-cert-signer" in "openshift-kube-apiserver-operator" requires a new signing cert/key pair
2019-02-05 07:38:53 +0100 CET  StatusNotFound               Unable to determine current operator status for kube-apiserver
2019-02-05 07:38:53 +0100 CET  OperatorStatusChanged        Status for operator kube-apiserver changed: Failing set to False (""),status.relatedObjects changed from [] to [{"operator.openshift.io" "kubeapiservers" "" "cluster"} {"" "namespaces" "" "openshift-config"} {"" "namespaces" "" "openshift-config-managed"} {"" "namespaces" "" "openshift-kube-apiserver-operator"} {"" "namespaces" "" "openshift-kube-apiserver"}]
// 2 minutes ago:
2019-02-05 07:40:37 +0100 CET  StatusNotFound …
```
=> status: print exact message to logs when status not found

pkg/assets/create/OWNERS, pkg/assets/create/create_test.go, pkg/assets/create/creater.go, pkg/assets/create/testdata/0000_10_kube-apiserver-operator_01_config.crd.yaml, pkg/assets/create/testdata/00_openshift-kube-apiserver-ns.yaml, pkg/assets/create/testdata/configmap-aggregator-client-ca.yaml, pkg/assets/create/testdata/operator-config.yaml, pkg/assets/create/testdata/secret-aggregator-client.yaml
This PR add `pkg/assets/create` package that contain helper to create multiple resources from disk and wait for them to be created.
The rationale here is to move this create and wait logic away from [cluster-bootstrap](https://github.com/openshift/cluster-bootstrap/pull/7) (former bootkube) and make it available for multiple components as needed.
=> assets: add creater based on dynamic client

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controllers.go, pkg/operator/staticpod/installerpod/cmd.go
etcd needs to be able to change the static pod on a per node basis.  This makes it possible to register pod mutation functions in both the installer command (to adjust the static pod) and the installer controller (to tell the installer command what to adjust).
@hexfusion @mfojtik @sttts
=> make it possible for an installer pod to have extra args

pkg/assets/create/create_test.go, pkg/assets/create/creater.go
As mentioned in the `interval` comment I'm removing, the REST client configuration includes its own requests-per-second configuration. There's no need for an additional 200ms sleep between loops on top of that.
I'm also passing the context into `create()` so we can cancel without waiting for all of the manifests to be attempted.  At the default 5 requests per second, the installer's 30+ manifests would take 6+ seconds in the "negligable network time" best-case, and we can be more responsive to cancels than that.
I've also shifted `retryCount` into the `for` loop, because that's where I'm used to seeing iteration counters.  And I've dropped logging on returned errors, because the caller will have the error and can make
that logging decision itself.  Logging should be reserved for internal …
=> pkg/assets/create: Allow mid-create cancels

pkg/operator/staticpod/controller/installer/bindata/bindata.go, pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml, pkg/operator/staticpod/installerpod/cmd.go, pkg/operator/staticpod/installerpod/cmd_test.go
* Fix the retry logic to only retry failed gets from API server
* Use `context.Context` to handle timeout
* Report events back to API server (success/failure) (it seems like the ownerRefs for the installer pod is the ConfigMap so the events will be recorded for that object... but at least we get something ;-)
=> installerpod: fix retry handling and report events

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/staticpod/controllers.go
When static pods fail to be ready or crashloop, we should update our status. This sets failing because we are failing and it is a union condition.  I thing we should consider making them all union conditions.
@openshift/sig-master
=> set failing when static pods are not all healthy

pkg/operator/staticpod/installerpod/cmd.go, pkg/operator/staticpod/installerpod/cmd_test.go
The namespace is already included in the Event, this removes duplicated information.
Also fixes an unit test that should check for the node string but instead it just prints it.
=> installerpod: remove namespace from the installer event

pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/status/status_controller.go
Fixes pruning controller that logs no-op as error and status controller that logs not found as error when deleting cluster operator.
=> operator: stop logging not found as errors

pkg/config/client/client_config.go, pkg/controller/controllercmd/builder.go, pkg/operator/resource/resourceapply/generic.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/staticpod/controllers.go
This change will prepare controllers to use protobuf enabled client-go. Via the `ControllerContext` we are going to provide two REST config (`KubeConfig` and `ProtoKubeConfig`). The later is a copy with accept set to prefer protobuf protocol.
We need to be careful to not use the protobuf for CR resources (@smarterclayton is fixing it?), so I renamed the `kubeClient` in controllers to `protoKubeClient`.
This change also remove usage of `kubernetes.Interface` and replace it with corresponding clients (pods/configmaps).
Lastly, this removes the `context.Context` from the controller context as storing the context in struct is discouraged in Go. Instead we just expose the `Done()` function.
=> Prepare to use protobuf client-go

pkg/config/client/client_config.go
Found this in the bump PR:
```
"message": "y-go/pkg/controller/controllercmd/builder.go:261 +0x48\ngithub.com/openshift/cluster-kube-apiserver-operator/vendor/github.com/openshift/library-go/pkg/controller/controllercmd.(*ControllerBuilder).Run(0xc42023c6c0, 0xc420106670, 0x1dc4660, 0xc420232b80, 0x3, 0xc42023c6c0)\n\t/go/src/github.com/openshift/cluster-kube-apiserver-operator/vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go:156 +0x43\ngithub.com/openshift/cluster-kube-apiserver-operator/vendor/github.com/openshift/library-go/pkg/controller/controllercmd.(*ControllerCommandConfig).StartController(0xc420124000, 0x1dc46a0, 0xc420052028, 0x2c68928, 0x0)\n\t/go/src/github.com/openshift/cluster-kube-apiserver-operator/vendor/github.com/openshift/library-go/pkg/con …
```
=> config: fix panic in client_config

pkg/operator/staticpod/controller/prune/prune_controller.go
The excludedRevisionHistory method returns an empty slice and no error when there's nothing to prune.
see https://github.com/openshift/library-go/blob/master/pkg/operator/staticpod/controller/prune/prune_controller.go#L142
fixes 
```
I0213 12:46:34.739534       1 prune_controller.go:141] no revision IDs currently eligible to prune
E0213 12:46:34.739754       1 runtime.go:69] Observed a panic: "index out of range" (runtime error: index out of range)
/go/src/github.com/openshift/cluster-kube-apiserver-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/openshift/cluster-kube-apiserver-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/openshift/cluster-kube-apiserver-operator/vendor/k8s.io/apimachinery/pkg …
```
=> don't prune when there are no IDs

pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
We need this to figure out why a particular cert is getting rotated. We know that it is, but we don't know why.
=> add reasons about why a cert was rotated

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/cabundle_test.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
Our resourceapply methods emit events and handle the update/create logic.  This updates the cert rotator to use it.
=> use the resourceapply methods in the cert rotation

pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go, pkg/operator/v1helpers/helpers.go
ConfigObservation is the legitimate writer of observedConfig.  This updates it so that it retries updates to config on conflict.  It also ensures that we requeue on failures so that we retry more often.
This will help speed up our handling of observed config to reduce flakes.
=> retry config updates without failing

pkg/operator/resource/resourceapply/apiextensions.go, pkg/operator/resource/resourceapply/apiregistration.go, pkg/operator/resource/resourceapply/apps.go, pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go, pkg/operator/resource/resourceapply/event_helpers.go, pkg/operator/resource/resourceapply/generic_test.go, pkg/operator/resource/resourceapply/json_patch_helpers.go, pkg/operator/resource/resourceapply/json_patch_helpers_test.go, pkg/operator/resource/resourceapply/monitoring.go, pkg/operator/resource/resourceapply/rbac.go, pkg/operator/resource/resourceapply/storage.go, pkg/operator/staticpod/controller/revision/revision_controller_test.go, pkg/operator/status/status_controller.go
This change will cause logging all changes to resources that we apply updates to. We already log diffs with CR's but we don't see why we changing things like pods/role bindings/etc.
I think this will improve our ability to debug changes done by operators and identify changes that are not desired which is worth the extra `DeepCopy()` ?
Test bump: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/160
=> resourceapply: log changes when objects are modified

pkg/operator/v1helpers/helpers.go
Try to mitigate following panic:
```
E0218 14:39:06.316641       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/openshift/cluster-kube-apiserver-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/openshift/cluster-kube-apiserver-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/openshift/cluster-kube-apiserver-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388 …
```
=> installer: prevent panics when new operator status is nil

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
fallout from the failing error count.
=> retrieval failures count against static pod state

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/staticpod/controllers.go
fixes the mapping bug. Testing in 
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/164
/hold
=> pull the version-mapping from the correct namespace

pkg/operator/render/options/generic.go
Allow to handle certain config JSON paths differently, e.g. merging maps or appending lists.
=> render: add special merge cases arg to GenericConfig.ApplyTo

pkg/operator/status/condition.go, pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
Simplify the logic for building CO status and make all conditions union conditions so we can set multiple `*Available` conditions
/assign @soltysh @sanchezl
=> simplify the clusteroperator status logic

pkg/operator/configobserver/config_observer_controller.go
I introduced this before we had any caching and when we still had some concerning cycles.  I think it's time to remove it to improve responsiveness.
/assign @soltysh
=> remove rate limiting from config observation

pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go, pkg/operator/staticpod/controller/revision/revision_controller.go, pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
When the management state value is set to `foo`, we should stop managing and additionally emit a warning. We don't want to emit a warning per controller loop, so I added one to target config reconciler in each operator.
=> operator: stop managing on unknown management state

pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/cmd.go, pkg/controller/controllercmd/flags.go, pkg/controller/fileobserver/observer.go, pkg/controller/fileobserver/observer_polling.go, pkg/controller/fileobserver/observer_polling_test.go, pkg/crypto/crypto.go
We knew we had a theoretical race, but we didn't expect to see it happen in any practical timeframe.  This is a good candidate fix for https://bugzilla.redhat.com/show_bug.cgi?id=1678929 which appears to happen sometimes.  We just force the initial values to hash.
/hold
hold for proof in another pull.
=> eliminate the race to read the serving certs in operator filepath change detection

pkg/assets/create/create_test.go, pkg/assets/create/creater.go
1) in case the asset already exists, it is skipped (not created again), but user still see:
```
Feb 21 09:54:23 ip-10-0-13-88 bootkube.sh[13308]: Creating /v1, Resource=namespaces ...
Feb 21 09:54:23 ip-10-0-13-88 bootkube.sh[13308]: Creating /v1, Resource=namespaces ...
Feb 21 09:54:23 ip-10-0-13-88 bootkube.sh[13308]: Creating /v1, Resource=namespaces ...
```
2) in case of error, the user will see summary of errors at the end, but we should print error immediately in verbose mode
3) move the created message when the resource is really created
=> assets: add more sense to creater verbose messages

pkg/assets/template.go, pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
This will let us adopt the certs from https://github.com/openshift/installer/pull/1232 into the "normal" rotator.  We need to do this the kubelet client cert.
proven in https://github.com/openshift/cluster-kube-apiserver-operator/pull/276
/assign @sttts
=> make functions for easy adoption of rendered certificates

pkg/assets/template.go
empty doesn't mean malformed.  Logically their values are empty.
=> tolerate empty certificates

pkg/operator/resource/resourceapply/rbac.go
I fixed cluster role binding and forget the role binding. There is still evidence in controller manager operator logs to stomp the apiGroup 130x during CI run. This should fix it.
=> resource: enforce apiGroup to role binding as well

pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
This updates rotation to have server hostnames settable after the fact using a function and provides a way to wire a channel to tickle the controller when there are changes
/hold
holding until I proof of working
/assign @sttts
=> allow hostnames to be specified and changed after initial creation

pkg/operator/resource/resourceapply/rbac.go
We don't have the apiGroup in manifest but the server will default it for `User` kind which mean our operator constantly stomping the rolebinding and removing the group...
/cc @deads2k
=> resourceapply: enforce apiGroup for rolebinding subjects

pkg/operator/staticpod/installerpod/cmd.go
This change will cause retry when we get 503 error from the API server:
`Failed to get config map openshift-kube-apiserver/kube-controller-manager-sa-token-signing-certs-2: an error on the server (\"apiserver is shutting down.\") has prevented the request from succeeding`
=> installerpod: retry on apiserver shutdown error

pkg/operator/staticpod/installerpod/cmd.go, pkg/operator/staticpod/installerpod/copy.go, pkg/operator/staticpod/installerpod/copy_test.go
This simplify the retry mechanism when retrieving secrets and configmaps from API server and also fixes a case when we fail to obtain self-reference for an installer pod (events) and instead of retry we failed.
In addition this add more unit tests to exercise the retry mechanism to increase test coverage for this critical piece of infrastructure.
=> staticpod: simplify retry mechanism

pkg/operator/resource/retry/retry.go, pkg/operator/resource/retry/retry_test.go, pkg/operator/resource/retry/wait.go, pkg/operator/staticpod/installerpod/cmd.go, pkg/operator/staticpod/installerpod/copy.go, pkg/operator/staticpod/installerpod/copy_test.go
This is something I miss in the client-go `retry` package and I think we should add it there.
Retrying on connection errors or (transient) server errors become a common problem as all operators have to talk to a restarting API server and the clients in operators need to handle retries in that case gracefully. While in the operator control loops this problem is not urgent (and it is usually resolved by reconcile), in components like installer pods or pruning pods this problem is more imminent and require some plumbing.
The retry mechanism here use exponential backoff (similar to retry on conflict) and it retry on all errors except the HTTP client errors (not found, auth, etc). The context passed to this function should specify the timeout and the user function should observe the context …
=> wire updated retry on connection logic to installer pod

pkg/operator/staticpod/controller/revision/revision_controller.go
We do a quorum read for the operator status, and the revision controller is the only actor changing LatestAvailableRevision. So seeing it being mutated outside of the controller loop hints at a serious race. This PR adds logging to see whether we experience this race.
=> revision-controller: log possible LatestAvailableRevision race

pkg/operator/staticpod/controller/revision/revision_controller.go
With this change we will log the JSON diff of the config/secret that caused the new revision rollout.
This should make us understand better the reason for the rollouts without spamming events to much.
Additionally, this will report **all** changed secrets/configs instead of reporting just one.
=> revision: log all changes for the latest revision

pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go, pkg/operator/staticpod/prune/cmd.go, pkg/operator/staticpod/prune/cmd_test.go
Using `TargetRevision` for the revision of the pruner pod fails when the pruner takes too long to start the pod and the TargetRevision gets set back to 0 when the install completes (successfully or unsuccessfully). However, `CurrentRevision` only updates when we get a successful install and the pruner kicks off on every install no matter the status. So this compares the max of CurrentRevision and `LastFailedRevision`, the latter which updates whenever we get a failed install.
I also added a couple logging messages that might help debugging in the future
=> Compare LastFailed and Current revisions for pruner pod

pkg/operator/management/management_state.go, pkg/operator/management/management_state_controller.go, pkg/operator/management/management_state_controller_test.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go, pkg/operator/staticpod/controller/revision/revision_controller.go, pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go, pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Reasoning:
Making a core or control plane operator "Unmanaged" will likely lead to a bricked cluster (in case of cert rotation, the cluster will self-destruct in 5 days today). The "Unmanaged" should only be used for development or debugging and it makes sense on higher level operators, where the damage it can do can be recovered by reverting the management state to managed. For debugging core/control plane operators, people can use CVO overrides and deleting the operator deployment (not sure what debugging that can be).
Because the "unmanaged" is giving admins a supported way to brick the clusters, we should not support it.
UPDATED: `management.SetOperatorAlwaysManaged()` and `management.SetOperatorNotRemovable()` will make the operator ignore the "unmanaged" and "removed" state, so you …
=> operator: ignore Unmanaged state in control plane operators

cmd/crd-schema-gen/generator/generator.go
Put a `<crd>.yaml-merge-patch` merge patch (https://tools.ietf.org/html/rfc7386) next to a CRD manifest `<crd>.yaml` and it will be applied to the CRD after the kubebuilder openapi generator has been run (only `spec.validation` changes are supported for now). This is useful to customize behaviour of shared types for specific types, e.g. ObjectMeta or OperatorSpec.
=> crd-schema-gen: allow a *-yaml-merge-patch file to post-kubebuilder-gen patch validation schemata

pkg/operator/events/eventstesting/recorder_testing.go, pkg/operator/events/recorder.go, pkg/operator/events/recorder_in_memory.go, pkg/operator/events/recorder_logging.go, pkg/operator/events/recorder_upstream.go, pkg/operator/staticpod/controllers.go
Based on https://github.com/openshift/library-go/blob/master/vendor/k8s.io/client-go/tools/record/events_cache.go#L414 the events are correlated and that also means the "spam" is filtered out. Based on the "key" for counting the events, if we keep the component the same for entire operator and all controller loops inside, we might get rate limited and some events might be dropped as "spam".
This change will allow to set custom component per-controller which should mitigate this issue.
=> events: allow to set component per controller

pkg/operator/configobserver/config_observer_controller.go, pkg/operator/events/eventstesting/recorder_testing.go, pkg/operator/events/recorder.go, pkg/operator/events/recorder_in_memory.go, pkg/operator/events/recorder_logging.go, pkg/operator/events/recorder_upstream.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/staticpod/certsyncpod/certsync_controller.go, pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go, pkg/operator/staticpod/controller/node/node_controller.go, pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/revision/revision_controller.go, pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/status/status_controller.go, pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Builds on https://github.com/openshift/library-go/pull/301
This will add `-controller-name` suffix to event recorder component name for each controller we own.
=> events: wire component name for each controller

pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
We always had a spot for this, but we only had a todo to wire in reaction to clusteroperator changes.  This updates us to react now that openshift/api has caught up.
@derekwaynecarr fyi
=> react to clusteroperator updates

pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go
We see errors like `E0306 19:58:57.817107       1 prune_controller.go:303] key failed with : unable to set pruner pod ownerrefs: configmap "revision-status-0" not found`, but there is no reason to try to make or prune a "revision 0" nor any reason one of our revisions should be at that number (that I know of)
=> don't create pruner pod with revision 0

pkg/config/leaderelection/leaderelection.go
@smarterclayton 
This PR increases leader election default periods. So, instead of pings every 2s, it's every 20s with this change.
* **k8s default** --> **thisPR**          
* lease-duration 15s  --> 120s
* renew-deadline 10s --> 90s
* retry-period 2s --> 20s
[k8s defaults](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/)
=> Leader election: increase LeaseDuration,RenewDeadline,RetryPeriod

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
`Mar 13 13:57:31.824 E clusteroperator/kube-apiserver changed Failing to True: StaticPodsFailing: StaticPodsFailing: nodes/ip-10-0-131-22.ec2.internal pods/kube-apiserver-ip-10-0-131-22.ec2.internal container="kube-apiserver-7" is not ready\nStaticPodsFailing: nodes/ip-10-0-131-22.ec2.internal pods/kube-apiserver-ip-10-0-131-22.ec2.internal container="kube-apiserver-7" is waiting: "PodInitializing" - ""\nStaticPodsFailing: nodes/ip-10-0-131-22.ec2.internal pods/kube-apiserver-ip-10-0-131-22.ec2.internal container="kube-apiserver-cert-syncer-7" is not ready\nStaticPodsFailing: nodes/ip-10-0-131-22.ec2.internal pods/kube-apiserver-ip-10-0-131-22.ec2.internal container="kube-apiserver-cert-syncer-7" is waiting: "PodInitializing" - ""
`
=> staticpodstate: do not report failing when containers are initializing

pkg/certs/util.go, pkg/certs/util_test.go, pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/target.go
We use this in must-gather and we should make the output consistent across all tools.
/cc @deads2k 
/cc @sttts
=> certs: add helpers to unify cert format

pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Signed-off-by: Monis Khan <mkhan@redhat.com>
@openshift/sig-master
=> Correctly run UnsupportedConfigOverridesController when Managed

pkg/serviceability/profiler.go
Otherwise components that don't pull in net/http/pprof can't use
it automatically.
=> web profiler should take implicit dependency on net/http/pprof

pkg/operator/staticpod/controller/installer/installer_controller.go
`0 nodes are failing on revision 6:\nNodeInstallerFailing: static pod has been installed, but is not ready while new revision is pending` indicates we report errors for nodes that are not actually failing (their failing count == 0).
=> installer: do no report errors for nodes that are not failing

pkg/operator/certrotation/config.go
This was requested by David in https://github.com/openshift/cluster-kube-apiserver-operator/pull/359#issuecomment-477623400
=> Get unnsuported cert rotation config reading

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/status/version.go
Set the operand version using `OPERAND_IMAGE_VERSION` variable.
=> staticpod: set operand version using environment variable

pkg/operator/status/status_controller.go
Without this PR, during upgrades, components that utilize the ClusterOperatorStatusController
(authentication and service-ca) have a glitch in reporting cluster operator version. This PR adds a wait for the operatorClient informer to catch up.
(testing now, this fixes the glitch in version reporting for auth, service-ca COs)
=> ClusterOperatorStatusController: Wait for cache sync

pkg/operator/status/status_controller.go
Without this PR, during upgrades, components that utilize the ClusterOperatorStatusController
(authentication and service-ca) will see a glitch in reporting cluster operator version
during upgrades.  Instead of deleting cluster operator from cluster when not found via
operatorClient, wait for the operatorClient informer to catch up.
=> ClusterOperatorStatusController: Add WaitForCacheSync

pkg/controller/controllercmd/cmd.go
A controller that needs to slightly tweak the builder (to provide
either extra API serving, health checks, or alter authorization)
must currently clone the StartController() method. Instead, split
config and default rotation into their own methods to make it
it easier to turn the default command into config, then start
default rotation.
@deads2k when I tried to reuse had to copy the rotation stuff
to tweak the builder
=> Allow controllercmd to reuse default config and rotation logic

pkg/controller/controllercmd/builder.go, pkg/operator/events/recorder.go, pkg/operator/events/recorder_test.go, pkg/operator/staticpod/installerpod/cmd.go
With this change, when we are unable to get the pod running the operator or we are not able to guess the pod by listing all pods in namespace, instead of failing hard use the provided namespace as a controller.
This will prevent operator failure to start in some cases.
/cc @deads2k
=> events: fallback to use namespace as controller if we are not able to get pod

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/metrics/monitor.go, pkg/operator/certrotation/metrics/util.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/target.go
This change will label all secrets and configmaps we rotate, collect certificate metadata from them and publish them to prometheus as:
`certificates_ca_bundle_expire_hours`
`certificates_signer_expire_hours`
`certificates_target_expire_hours`
The gauge values indicates number of hours until each certificate expire. This should help us better monitor the certificate expiration in live cluster and add alerts when certificates are about to expire without replacement.
Proof: https://github.com/openshift/cluster-kube-apiserver-operator/pull/360
/cc @soltysh 
/cc @deads2k 
/cc @sttts
=> Add prometheus metrics for rotated certificates

cmd/crd-schema-gen/generator/generator.go
Upstream controller-tools expect correct repo and domain settings (usually in a PROJECT file). We instead use --domain and --repo (which is optionally derived from GOPATH and working directory).
=> crd-schema-gen: add --domain and (optional) --repo

pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/metrics/monitor.go
Allow to opt-in for the metrics registration (so we don't duplicate this metrics from various operators).
Fixes a flaw in sample reporting code that can lead to panic.
=> certrotation: fix metrics collector

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/cabundle_test.go, pkg/operator/certrotation/label.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
This change will cause that all secrets and configs managed by certrotation controller will be labeled using their type.
This allows easier label queries.
/cc @soltysh 
/cc @deads2k
=> certrotation: label managed certificates

pkg/controller/controllercmd/builder.go
openshift-config is a reasonable place for operators to report events,
although they may not have access. Allow a builder to set it so we can
both test locally and override it for some operators.
At worst, we will attempt to log events to "openshift-config"
=> Set an arbitrary event namespace when not running inside a cluster

pkg/operator/resource/resourceapply/core.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
This change will make us check cache before making a DELETE call that hits the API server.
This will reduce the amount of DELETE requests we issue when the resource (secret/configmap) does not exists in the target namespace (and therefore the DELETE call always returned 404).
/cc @smarterclayton
=> resourcesynccontroller: use cached get to confirm resource exists before deleting target

pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go, pkg/operator/loglevel/logging_controller.go, pkg/operator/management/management_state_controller.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/resourcesynccontroller/resourcesync_controller_test.go, pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go, pkg/operator/staticpod/controller/node/node_controller.go, pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go, pkg/operator/staticpod/controller/revision/revision_controller.go, pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/status/status_controller.go, pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Upgrades are flapping on revisions because the operator is getting redeployed and we don't wait for cache syncing. The specific instance is https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-4.0/1077/artifacts/e2e-aws-upgrade/events.json in the revision controller, but we had many that were missing because they all used to be live look ups.
@openshift/sig-master
=> wait for caches to synchronize before working

pkg/config/leaderelection/leaderelection.go
Because we have serial updates, the time it takes to acquire a lease is a significant percentage of upgrade time.  In 1.14 we get a graceful release of leases, but until then let's tune this down.
/assign @smarterclayton
=> tighten leader election defaults

pkg/assets/create/create_test.go, pkg/assets/create/creater.go
This ripples into cluster-bootstrap which uses it to create resources.  It adds information about where content comes from when it is skipped and fails so you can see *which* secret is failing.
=> add path, type, name, and namespace information to creation message

pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go, pkg/operator/staticpod/controller/node/node_controller_test.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go, pkg/operator/staticpod/controller/revision/revision_controller_test.go, pkg/operator/v1helpers/interfaces.go, pkg/operator/v1helpers/test_helpers.go
My use case: writing an e2e test for revision pruning, want to trigger a bunch of new revisions by updating the `ForceRedeploymentReason` in `StaticPodOperatorSpec`. Currently we can get the spec but I don't know of any way to update it.
=> Add UpdateStaticPodOperatorSpec function

pkg/config/serving/server.go, pkg/controller/controllercmd/builder.go
Add retry to prevent being fatal:
`Get https://172.30.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 172.30.0.1:443: connect: connection refused`
Best I can think of to address https://bugzilla.redhat.com/show_bug.cgi?id=1702104 (but I suspect there might be other components failing due to races).
/cc @deads2k
=> controller: retry connection errors when getting extension-apiserver-authentication 

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/int32.go
Upgrades have a bunch of events about us because status report is unstable.  This fixes that.  Upstream won't have int32 maps until https://github.com/kubernetes/kubernetes/pull/76964/files merges
@openshift/sig-master 
/assign @soltysh
=> stop flapping status on revision updates

pkg/operator/v1helpers/helpers.go
Removes this helper which should no longer be used in favor of CVO managed operator resources
=> Remove EnsureOperatorConfigExists helper

pkg/operator/events/recorder_in_memory.go, pkg/operator/loglevel/logging_controller.go, pkg/operator/loglevel/logging_controller_test.go, pkg/operator/loglevel/util.go
The recommended way (from klog) to set the loglevel is go trough flags and use the flag.Value to mutate the current verbosity. I added that before we fallback to mutate the global logging var directly.
Added helper to determine what is the current logging verbosity and added a test to prove it works.
/cc @deads2k
=> loglevel: rework setting the log level using flags

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
The "missing: secrets/serving-cert should be logged by event.
=> installer: fire event on missing required certs

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
We currently only retry on OOMs, but we can retry on anything. The backoff should keep us from storming and the last few lines of the installer logs are always included in our operator log.
=> always retry failed installer pods

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/status/version.go
/hold
hold for proof
This could resolve our operator version if the static pod operators set a different key.
proof in https://github.com/openshift/cluster-kube-apiserver-operator/pull/440
=> set operator version to match other operators

pkg/operator/loglevel/logging_controller.go, pkg/operator/loglevel/logging_controller_test.go
In case the logging is set to empty string, we should assume Normal loglevel and do not change it.
=> logging: fix case when logging is set to empty string

pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
There is plenty of these errors in the log and dozen of events generated:
`│2019-04-28T19:12:41.659900979Z I0428 19:12:41.659847       1 event.go:221] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-kube-apiserver-operator", Name:"kube-apiserver-operator", UID:"149d03e3-69e9-11e9-a91d-124681ba4ffe", APIVersion:"apps/v1", ResourceVersion:"", Field│
│2019-04-28T19:12:41.673928052Z E0428 19:12:41.673873       1 monitoring_resource_controller.go:182] key failed with : the server could not find the requested resource`
The reason described in the comment.
=> monitoring: make service monitor CRD unavailability produce less noise

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
A high rate of failed installer pods on revision `1` observed via CI. Caused by missing `etcd-client-1` secret which is part of the "required" secrets.
```
I0429 20:43:28.093507       1 cmd.go:246] Creating target resource directory "/etc/kubernetes/static-pod-resources/kube-apiserver-pod-1" ...
I0429 20:43:28.093861       1 cmd.go:171] Creating target resource directory "/etc/kubernetes/static-pod-resources/kube-apiserver-pod-1" ...
I0429 20:43:28.093951       1 cmd.go:179] Getting secrets ...
I0429 20:43:28.096810       1 copy.go:24] Failed to get secret openshift-kube-apiserver/etcd-client-1: secrets "etcd-client-1" not found
F0429 20:43:28.101133       1 cmd.go:89] failed to copy: secrets "etcd-client-1" not found
```
We already have mechanism to ensure some (cert) required secrets …
=> installer: ensure the etcd-client secret is available

pkg/operator/v1helpers/helpers.go
See 20 lines down where this was fixed for static pods
=> fix updatestatus return value

pkg/operator/staticpod/certsyncpod/certsync_cmd.go
We pass the `POD_NAMESPACE` using the env var to args, but that seems like not properly expanded:
`Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:kube-controller-manager" cannot list resource "configmaps" in API group "" in the namespace "${POD_NAMESPACE}"\nW0502`
```
command: ["cluster-kube-controller-manager-operator", "cert-syncer"]
args:
- --kubeconfig=/etc/kubernetes/static-pod-resources/configmaps/kube-controller-cert-syncer-kubeconfig/kubeconfig
- --namespace=${POD_NAMESPACE}
- --destination-dir=/etc/kubernetes/static-pod-certs
```
This change will make use of the env var default and allow to override via args.
=> certsyncpod: default namespace to POD_NAMESPACE env var

pkg/controller/controllercmd/cmd.go
This allows to wire `stopCh := genericapiserver.SetupSignalHandler()` inside each operator `main.go` and pass the stopCh to the operator command. When the stopCh closes, it cancels the context the command use and trigger shutdown for all controller loops and observers (if wired properly).
https://github.com/kubernetes/kubernetes/pull/77361 to make this more generic.
/cc @sttts 
/cc @deads2k
=> controllercmd: handle TERM signals gracefully in operator

pkg/operator/watchdog/cmd.go, pkg/operator/watchdog/cmd_test.go, pkg/operator/watchdog/proc.go, pkg/operator/watchdog/proc_test.go
The purpose of this package is to live aside to an operand container (side-car). If the operand pod runs with `shareProcessNamespace: true` the watchdog can send SIGTERM to the operand to trigger graceful shutdown.
The watchdog use the fileobserver to detect changes in files (`--files`) and in reaction to a change it will send TERM signal to a process specified by name `--process-name`.
=> file-watcher-watchdog: add command to kill the operand process on file changes

pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/management/management_state_controller.go, pkg/operator/status/status_controller.go
Seeing a lot of:
`
E0520 09:21:27.184580       1 workqueue_metrics.go:129] failed to register depth metric StatusSyncer-kube-controller-manager: descriptor Desc{fqName: "StatusSyncer-kube-controller-manager_depth", help: "(Deprecated) Current depth of workqueue: StatusSyncer-kube-controll│
er-manager", constLabels: {}, variableLabels: []} is invalid: "StatusSyncer-kube-controller-manager_depth" is not a valid metric name
`
Which means the prometheus metrics for queues are not being published. I think this happened after we bumped the client-go in library-go. Starting fixing in library-go and then move to operators.
/cc @deads2k 
/cc @soltysh
=> operator: fix named queue names to prevent prometheus errors

pkg/authorization/scopemetadata/clusterrole_describers.go, pkg/authorization/scopemetadata/describers.go, pkg/authorization/scopemetadata/user_describers.go, pkg/authorization/scopemetadata/validation.go, pkg/authorization/scopemetadata/validation_test.go, pkg/legacyapi/legacygroupification/groupification.go
shared by oauthserver, kube-apiserver, openshift-apiserver, and library-go.
=> move scopes and groupification out

pkg/operator/staticpod/certsyncpod/certsync_cmd.go, pkg/operator/staticpod/certsyncpod/certsync_controller.go
also wait for the caches to fill
/assign @sanchezl 
/hold
@sanchezl please make a fake bump
=> start informers after the listers have been requested

pkg/image/dockerv1client/conversion.go, pkg/image/dockerv1client/types.go
These are missing in openshift/api, but are only needed by `oc` when manipulating with docker images. We can upstream all this to openshift/api, but this should get us started.
=> image: add missing docker types

pkg/apps/appsutil/util.go, pkg/image/imageutil/helpers.go
These two are needed by e2e tests and having them here avoids copying.
=> add helpers shared with e2e tests

pkg/crypto/crypto.go, pkg/operator/condition/condition.go, pkg/operator/staticpod/controller/node/node_controller.go, pkg/operator/staticpod/controller/node/node_controller_test.go
extends node controller to examine `Node.Status.Ready` field and to report unhealthy status.
the status is reported by the controller as a new condition of type `NodeControllerDegraded` that is added to `StaticPodOperatorStatus`
closes https://jira.coreos.com/browse/MSTR-404
=> reports `NotReady` status of master nodes

pkg/config/validation/serving_info.go, pkg/crypto/crypto.go, pkg/crypto/crypto_test.go
We need to discern between the package-valid TLS versions (with go1.12 this now includes tls1.3) and the server enabled versions (which only goes up to tls1.2). Currently some origin tests assume that the package-valid versions above the default are automatically supported, but tls1.3 is opt-in at build time.
=> split valid and enabled TLS versions

pkg/operator/status/condition.go, pkg/operator/status/status_controller_test.go
We chose 1 minute of inertia back when we only waited 30 seconds for AWS.  We now wait 70 seconds, so we blip to degraded.  This makes us longer than the 70 seconds.
/assign @derekwaynecarr
=> allow more interia for degraded because installer pods take a long time for AWS

alpha-build-machinery/make/targets/openshift/bindata.mk
If someone has GOBIN set, `go install` only compiles into the
folder specified by this variable, which causes the make target
to fail and a potential unwanted install of the binary to the user's
GOBIN folder.
=> make targets: Fix broken update-bindata

glide.lock, glide.yaml
Fixes https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_library-go/468/pull-ci-openshift-library-go-master-verify-deps/1254
(I didn't want to couple bump into it. I don't think the hash mismatch matters.)
@openshift/sig-master fyi, this may be needed in other repos where verify-deps is rightfully failing and also you would not be able to bump deps otherwise
=> Fix bitbucket and glide

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
The cloud provider name for GCP platform is `gce` [1]
[1]: https://github.com/kubernetes/kubernetes/blob/844a0c9a10cd52367ec7c05f5a8c176535dcef38/staging/src/k8s.io/legacy-cloud-providers/gce/gce.go#L59
=> configobserver/cloudprovider: add GCP to known platforms

pkg/operator/render/options/config.go, pkg/operator/render/options/manifest.go
Prereq for https://github.com/openshift/cluster-kube-apiserver-operator/pull/525.
=> rendor: add optional --manifest-operator-image

alpha-build-machinery/make/lib/golang.mk
/cc @sttts 
replaces https://github.com/openshift/oc/pull/10
for some reason ART uses multiple paths in GOPATH which looks weird but is allowed
=> Support GOPATH containing a list of paths

alpha-build-machinery/make/lib/golang.mk
We need it for ART when the sources are build from a cloned repo
/cc @deads2k @sttts
=> Allow setting git info externally

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/proxy/observe_proxy.go, pkg/operator/configobserver/proxy/observe_proxy_test.go
OpenShift infrastructure operators should be observing the Proxy object, add a helper so that we can reuse the code.
Useful at least for the kube and openshift apiserver operators.
=> configobserver: add helper function for observing the Proxy object

pkg/operator/resource/resourcemerge/generic_config_merger.go, pkg/operator/resource/resourcemerge/generic_config_merger_test.go
This adds a variant of the ConfigMap resourcemerge funcs which prunes fields that do not show up in a given `runtime.Object`. This will be used to prune configs for operands from mistyped values and from operator internal fields.
=> resourcemerge: add pruning helpers when creating a ConfigMap

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
GCP cloud provider needs to be configured to be Regional and MultiZone so that it is looking for resources like instances in all Zones for the region it's deployed in.
/cc @csrwng
=> configobserver/cloudprovider: sync the cloud-config for GCP

pkg/operator/resource/resourcemerge/generic_config_merger.go, pkg/operator/resource/resourcemerge/generic_config_merger_test.go
intersectArray() was trying to intersect the input array again
instead of the elements of the array, in a recursive loop.
=> configmerge: fix stack smash

pkg/assets/create/create_test.go, pkg/assets/create/creater.go, pkg/assets/create/testdata/operator-config-empty-status.yaml, pkg/assets/create/testdata/operator-config.yaml
Resources like proxies.config.openshift.io that have a status subresource require extra call to UpdateStatus to ensure that the status
contents of the manifest are applied to the cluster.
/cc @deads2k @sttts
=> pkg/asset/create: run UpdateSatus for resources that have status field set

pkg/operator/resource/resourceapply/core.go
Log OLD and NEW instead if a data value changed.
Reject `stringData` because we don't support that right now (could be added if needed, but not in this PR).
=> resourceapply: don't log secret data

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
After https://github.com/openshift/machine-config-operator/pull/964 is merged we can re-enable cloud provider again.
=> Re-enable OpenStack cloud provider

alpha-build-machinery/make/default.example.mk, alpha-build-machinery/make/default.example.mk.help.log, alpha-build-machinery/make/operator.example.mk, alpha-build-machinery/make/operator.example.mk.help.log, alpha-build-machinery/make/targets/openshift/images.mk
We need this so we can build images with correct names especially for the case where that is a chained build.
E.g. we need to be able to match the image name in
```
FROM registry.svc.ci.openshift.org/ocp/4.2:cli
```
@openshift/openshift-team-master This need Makefile updated on first bump. (These targets are not exercised in CI so it won't fail.) 
/cc @sttts
=> Make image building to be more configurable and confirm to 4.x naming conventions

pkg/operator/staticpod/controller/installer/installer_controller.go
This should be a single error instead of three.
=> operator/staticpod: properly format error message

pkg/operator/configobserver/proxy/observe_proxy.go, pkg/operator/configobserver/proxy/observe_proxy_test.go
causes trouble in https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-kube-apiserver-operator/530/pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-aws/2467/artifacts/e2e-aws/pods/openshift-kube-apiserver-operator_kube-apiserver-operator-564769bd4f-p8s98_kube-apiserver-operator.log
=> observe proxy: don't change target in noconfig -> noconfig case

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
OpenStack cloud provider requires a cloud config file to operate properly.
=> Generate cloud config for openstack cloud provider

pkg/operator/configobserver/proxy/observe_proxy.go, pkg/operator/configobserver/proxy/observe_proxy_test.go
When the installer creates the Proxy manifest
Status NoProxy contains the list of cluster urls and
ip address(es) that should not be proxied.  Spec noProxy
only contains the user provided list.
=> Update observe proxy to use Status NoProxy

pkg/operator/staticpod/prune/cmd.go
This PR fixes a small typo, resolved for clarity.
=> pkg/operator/staticpod/prune: return proper flag in error

pkg/oauth/oauthserviceaccountclient/oauthclientregistry_test.go, pkg/operator/watchdog/cmd.go
To avoid races between watchee and watcher.
=> watchdog: add --ready-file support

alpha-build-machinery/doc.go, alpha-build-machinery/make/doc.go, alpha-build-machinery/make/lib/doc.go, alpha-build-machinery/make/targets/doc.go, alpha-build-machinery/make/targets/golang/doc.go, alpha-build-machinery/make/targets/openshift/doc.go, alpha-build-machinery/make/targets/openshift/operator/doc.go, alpha-build-machinery/scripts/doc.go
`go mod` prunes all packages not used.  You cannot rely on a non-go package, but we need our build machinery.  This allows us to use `go mod` by creating a dependency magnet we can use from other repos.
/assign @tnozicka @soltysh
=> add dependency magnet files for go mod and build-machinery

alpha-build-machinery/make/lib/golang.mk
I found that when building rpms (special gopath / multiple gopath) this failed. Looks like `go list` can do it as well and I have more confidence in it.
/cc @sttts
=> build-machinery: Fix and simplify GO_PACKAGE detection

pkg/controller/controllercmd/cmd.go, pkg/controller/controllercmd/flags.go
Needed by cluster-authentication-operator to react to proxy CA changes.
=> controllercmd: add --terminate-on-files file observer

pkg/controller/fileobserver/observer.go, pkg/controller/fileobserver/observer_polling.go, pkg/operator/staticpod/certsyncpod/certsync_cmd.go
The `ExitOnChangeReactor` is dangerous because it calls `os.Exit(0)` directly which kills the process immediately without proper shutdown. 
The `TerminateOnChangeReactor` allow consumer to pass the termination function.
The `ExitOnChangeReactor` is not removed as somebody might be using it, but marked as deprecated.
/cc @sttts
=> fileobserver: deprecate ExitOnChangeReactor in favor of TerminateOnChangeReactor

pkg/operator/staticpod/controller/installer/installer_controller.go
Fixes:
```
2019-08-30T06:34:04.422583209Z   (string) (len=91) "static pod of revision has been installed, but is not ready while new revision % is pending"
```
=> installer: fix pending revision error message to include target revision

pkg/operator/staticpod/certsyncpod/certsync_cmd.go, pkg/operator/staticpod/certsyncpod/certsync_controller.go
4.1 backport of https://github.com/openshift/library-go/pull/424
/cc @sttts
=> Bug 1714158: Prevent cert-syncer to act on stale data

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go
We weren't syncing the binaryData which resulted in failures for the console operator. This fixes it.
=> Bug 1748280: resourceapply: sync ConfigMap binaryData as well

pkg/controller/controllercmd/cmd.go
This fixes a bug where if `--terminate-on-files` is used we never run the file observer (just create it). It also starts the observer only if this flag is specified.
This should unblock the auth operator.
=> cmd: run terminate-on-files observer

pkg/controller/controllercmd/cmd.go, pkg/controller/fileobserver/observer_polling.go, pkg/controller/fileobserver/observer_polling_test.go
Inside auth operator, we read the trusted ca bundle file but we ignore the error when the file does not exists. In that case the starting content for that file is empty string. Without this fix, the fileobserver will hash the empty string (`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`) and then after the binary/operator run, the `calculateFileHash()` return "" as hash if the file does not exists.
That will trigger immediate restart/termination because the content change.
NOTE: This is blocking 4.1 -> 4.2 upgrade test, this was found in the logs:
```
1 observer_polling.go:78] Observed change: file:/var/run/configmaps/trusted-ca-bundle/ca-bundle.crt (current: "", lastKnown: "e3b0c44298fc1c149af....
```
=> fileobserver: do not hash empty string

alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log, alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
This fixes up #526 to only check the diff of CRD manifests, instead of the entire manifest folder, the latter of which causes errors because we do not copy the entire manifests folder to the temp dir.
The other option of course *is* copying the entire manifests folder to the temp dir, however that creates a lot of ugly silenced errors when we call `cp` for just update:
```
$ make update-codegen
Using existing controller-gen from "_output/tools/src/sigs.k8s.io/controller-tools/controller-gen"
Using existing yq from "_output/tools/bin/yq"
'_output/tools/src/sigs.k8s.io/controller-tools/controller-gen' \
schemapatch:manifests="./manifests" \
paths="./vendor/github.com/openshift/api/operator/v1" \
output:dir="./manifests"
cp -n ./manifests/* './manifests/' || true  # FIXME: centos
cp: …
```
=> Fix up crd-schema-gen verify

pkg/assets/create/creater.go
Typo snuck in with 0967e06e68 (#220).
CC @mfojtik.
=> pkg/assets/create: Fix "unstructed" -> "unstructured" typo

alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log, alpha-build-machinery/make/examples/multiple-binaries/manifests/operator.openshift.io_myotheroperatorresources.crd.yaml, alpha-build-machinery/make/examples/multiple-binaries/manifests/operator.openshift.io_myotheroperatorresources.crd.yaml-merge-patch, alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1beta1/types.go, alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myotheroperatorresources.crd.yaml, alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myotheroperatorresources.crd.yaml-merge-patch, alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myotheroperatorresources.crd.yaml, alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myotheroperatorresources.crd.yaml-merge-patch, alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
As discovered in https://github.com/openshift/cluster-kube-apiserver-operator/pull/568#pullrequestreview-296482688, this flag is needed to overwrite existing fields in CRDs with yaml patches
=> Add -x (overwrite) flag to crd-schema-gen command

pkg/image/registryclient/client.go, pkg/image/registryclient/client_test.go
If we see a known 429 or 503 error, or an unknown 503 or 500 error,
we can retry.
Will allow broader retry behavior for cli commands.
Prereq for openshift/oc#112
=> Bug 1754042: Detect more retriable errors from general registry clients

alpha-build-machinery/make/lib/golang.mk
ignore nested `vendor` folders for gofmt. although we strip vendor folder there are legal usecases like `alpha-build-machinery` examples
/cc @sttts
=> Ignore nested vendor/ folders in gofmt

alpha-build-machinery/make/examples/multiple-binaries/Makefile, alpha-build-machinery/make/examples/multiple-binaries/Makefile.test, alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log, alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
`openshift/api` needs to generate CRDs in multiple different directories so we need to macro so it can be instantiated multiple times
=> Generic crdgen

alpha-build-machinery/make/lib/golang.mk
there is a lot of go files in _output where we "go get" tools, enough to overflow args buffer, also third parties are not required to have gofmt
/cc @damemi
=> Ignore _output folders for gofmt

pkg/operator/staticpod/controller/installerstate/installer_state_controller.go, pkg/operator/staticpod/controller/installerstate/installer_state_controller_test.go, pkg/operator/staticpod/controllers.go
This will add controller that watches the installer pods in `Pending` state that are in this state for longer then 5 minutes. If such pods are found, the controller will then make the operator go to Degraded and report the reason and message found for such pod/container state.
This will help improve debugging and triaging bugs caused by slow networking or kubelet that prevents rolling updates to static pod based operators.
/cc @deads2k 
/cc @sttts
=> installer: add controller that watch pending installer pods

pkg/crypto/crypto.go, pkg/crypto/crypto_test.go
This adds TLS 1.3 cipher names to our ciphers list so that we are able to set them in our components. This aligns with the work that's being done for the TLSSecurityProfiles (https://github.com/openshift/api/pull/458) where each of the profiles already contains these cipher suites.
=> add tls1.3 cipher suites

pkg/operator/encryption/controllers/key_controller_test.go, pkg/operator/encryption/controllers/migration_controller_test.go, pkg/operator/encryption/controllers/prune_controller_test.go, pkg/operator/encryption/controllers/state_controller_test.go, pkg/operator/encryption/deployer/staticpod.go, pkg/operator/encryption/testing/helpers.go
We compared the pod names, not the node name they were scheduled to.
=> encryption: cleanup and fix static pod deployer nodeName logic

pkg/operator/encryption/controllers/key_controller_test.go, pkg/operator/encryption/controllers/migration_controller_test.go, pkg/operator/encryption/controllers/prune_controller_test.go, pkg/operator/encryption/controllers/state_controller_test.go, pkg/operator/encryption/deployer/revisionedpod.go, pkg/operator/encryption/deployer/staticpod.go
The static pod controllers are only one way of deploying pods with revisioned resources. This PR split the StaticPodDeployer into a RevisionLabelPodDeployer and separates the static pod part into a StaticPodNodeProvider which returns the `status.nodeStatus` master node names.
=> encryption: split into RevisionLabelPodDeployer and StaticPodNodeProvider

pkg/operator/status/condition.go, pkg/operator/status/status_controller_test.go
The previous logic was built around a boolean assumption.  Running the old logic against my new unit tests from this commit gave:
```console
$ go test ./pkg/operator/status/
--- FAIL: TestDegraded (0.00s)
--- FAIL: TestDegraded/two_present/one_available/one_unknown (0.00s)
status_controller_test.go:293:   &v1.ClusterOperatorStatusCondition{
Type:               "Available",
- Status:             "Unknown",
+ Status:             "True",
LastTransitionTime: v1.Time{},
- Reason:             "TypeBAvailable",
+ Reason:             "AsExpected",
- Message:            "TypeBAvailable: b is confused",
+ Message:            "TypeAAvailable: a is great\nTypeBAvailable: b is confused",
}
--- FAIL: TestDegraded/two_present/one_unavailable/one_unknown (0.00s)
status_controller_test.go:293: …
```
=> pkg/operator/status/condition: Handle Unknown in internalUnionCondition

pkg/operator/encryption/deployer/revisionedpod.go
Missing good pods for a master node is not an error, but a sign of progress rolling out a new revision.
=> encryption: missing node pods => progressing

pkg/operator/encryption/deployer/revisionedpod.go, pkg/operator/encryption/deployer/revisionedpod_test.go
The pods references in the loop were all the same. Golang, sigh.
=> encryption: fix var scope bug in categorizePods and add tests

pkg/crypto/crypto.go, pkg/crypto/crypto_test.go, pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go, pkg/operator/configobserver/apiserver/observe_tlssecurityprofile_test.go
Add observer for `APIServer.Spec.TLSSecurityProfile` to be used in {kube,openshift}-apiserver-operator (and eventually by the authn operator).
Also adds OpenSSL -> IANA cipher names mapping which we need as the API for TLSSecurityProfile uses OpenSSL cipher names.
Requires https://github.com/openshift/library-go/pull/553 for TLS1.3 versions
=> Add observer for APIServer.Spec.TLSSecurityProfile

pkg/crypto/crypto.go, pkg/crypto/crypto_test.go
The `Subject Common Name` field was previously assumed to be unique and used in determining whether the CA that generated a serving cert had changed. With service serving cert CA rotation, the `Common Name` will now be retained across CAs and this suggested the use of `SubjectKeyId` and `AuthorityKeyId` as a way to determine if a serving cert required regeneration.
Required by https://github.com/openshift/service-ca-operator/pull/73
cc: @sttts @deads2k
=> Add SubjectKeyId and AuthorityKeyId to server certs

pkg/operator/certrotation/signer.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
For automatic recovery we need to run a process that regenerates certificate only when they are expired. (library-go forces rotation in 1/5 of the lifetime.) We need to avoid stealing the rotation from the operator so logs are in one place.
proof this isn't breaking current flow in https://github.com/openshift/cluster-kube-apiserver-operator/pull/635
/cc @soltysh
=> Allow rotation "only when certs are expired"

pkg/operator/encryption/controllers/migrators/errors.go, pkg/operator/encryption/controllers/migrators/inprocess.go
Following kube-storage-version-migrator logic (errors.go comes from there).
=> encryption: forgiving error handling for migration for retryable errors

pkg/controller/fileobserver/observer.go, pkg/controller/fileobserver/observer_polling.go, pkg/controller/fileobserver/observer_polling_test.go
* First commit is adding mechanism for callers to ensure the initial sync passed and the fileobserver see and observing changes on files successfully
* Second commit is critical as when the initial content of file is empty, the reactor for the file is never added
* Third commit is adding much more unit test coverage to ensure all corner cases are handled
There is one TODO in unit test when the initial content is empty and the file content is empty (but exists), the observer will trigger "Created" action, even when the file existed. This should be handled as follow up issue.
=> File observer fixes

pkg/image/reference/reference.go
When we convert a ref like `foo/bar:baz@sha256:...` to Exact(), we
should prefer the digest.
=> image/reference: A ref with tag and ID should prefer ID

pkg/controller/fileobserver/observer_polling.go
Found that the recent changes to file observer also caused to spam log as we log the observed file on each resync.
=> fileobserver: fix logging

pkg/operator/encryption/controllers/state_controller_test.go, pkg/operator/encryption/statemachine/transition.go, pkg/operator/encryption/statemachine/transition_test.go
An etcd backup during migration might require the last read key to be used to decrypt. If the backup of the config might not include that last read key though when done too late. This PR makes the last read to stay in the encryption config such that decryption is always possible.
=> Bug 1775057: encryption: keep last read key after migration for easier backup/restore

pkg/operator/encryption/controllers/migrators/inprocess.go, pkg/operator/encryption/controllers/migrators/inprocess_processor.go, pkg/operator/encryption/controllers/prune_controller.go
We assumed in the migration code that the default verbosity is 4, but it is 2. This PR fixes the `V(n)` call accordingly.
=> encryption: adapt log output verbosity to default of 2

pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/key_controller_test.go
The old
```
I1127 10:41:49.608448       1 event.go:255] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-kube-apiserver-operator", Name:"kube-apiserver-operator", UID:"e7160562-1117-4844-a859-1c5a94e5729c", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'EncryptionWriteKeyTriggeredInternal' Triggered key "1" for resource "configmaps" because no-secrets, no-secrets
```
could not be understood by users, nor us developers.
=> encryption: improve EncryptionWriteKeyTriggeredInternal reasons

pkg/operator/encryption/controllers.go, pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/key_controller_test.go, pkg/operator/encryption/controllers/migration_controller.go, pkg/operator/encryption/controllers/migration_controller_test.go, pkg/operator/encryption/controllers/state_controller.go, pkg/operator/encryption/controllers/state_controller_test.go, pkg/operator/encryption/encryptionconfig/config.go, pkg/operator/encryption/encryptionconfig/config_test.go, pkg/operator/encryption/secrets/secrets.go, pkg/operator/encryption/statemachine/transition.go
The current config state was not enriched with the information we store in secret annotations (reasons, migration state). Hence, every comparison of that info between current and desired state was wrong, leading to more events and possibly other unwanted side-effects. This PR also updates the current state with the secrets, like we did with the desired state.
=> encryption: enrich current state with secret info to avoid spurious events

pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/key_controller_test.go, pkg/operator/encryption/controllers/prune_controller_test.go, pkg/operator/encryption/state/helpers.go, pkg/operator/encryption/statemachine/transition.go, pkg/operator/encryption/statemachine/transition_test.go, test/e2e-encryption/encryption_test.go
The key controller was still just expecting one read-key, while with the recent change for backup/restore we always preserve one more key. This made the key controller freeze after the first two read-keys were in the config.
While fixing the upper, we also run into the case that during pruning this one more read-key is preserved, but this read-key must be backed. Hence, we have to preserve also all other unbacked read-keys in between.
=> encryption: fix freezing key controller

pkg/controller/fileobserver/observer.go, pkg/controller/fileobserver/observer_polling.go, pkg/controller/fileobserver/observer_polling_test.go
In some cases the file observer will not trigger an action when the file is modified (empty files, non-existing files). This will backport the fixes that already merged to master.
=> Bug 1771665: Backport file observer fixes

pkg/operator/encryption/controllers.go, pkg/operator/encryption/controllers/condition_controller.go, test/e2e-encryption/encryption_test.go
This adds an `Encrypted` condition that is understandable by users. It is true iff there is a fully migrated read-key, and no identity key since then.
=> encryption: add Encrypted condition

pkg/operator/encryption/controllers/migrators/inprocess.go, pkg/operator/encryption/controllers/migrators/inprocess_processor.go, pkg/operator/encryption/controllers/migrators/inprocess_processor_test.go, pkg/operator/encryption/controllers/migrators/metrics.go
Adds two simple metrics to the storage migrator. Since the same metrics will be used by `kas-o` and `oas-o` I think it's fine to have them down in `library-go`
1. `migrated_objects` - represents the total number of objects that have been migrated, labeled with the full resource name.
2. `migrations` - represents the number of completed migration, labeled with the full resource name, and the status of the migration (failed or succeeded)
note that the names and types align with those defined in the upstream migrator.
=> inprocess migrator metrics

pkg/controller/controllercmd/builder.go
since `ControllerBuilder` is used as a building block for other controllers and due to the recent changes in the controller interface which now accepts a context keeping `ctx` as part of `ControllerBuilder` seems to be reasonable.
=> adds context to ControllerContext for signal and cancellation propagation

pkg/operator/encryption/controllers.go, pkg/operator/encryption/controllers/condition_controller.go, pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/key_controller_test.go, pkg/operator/encryption/controllers/migration_controller.go, pkg/operator/encryption/controllers/migration_controller_test.go, pkg/operator/encryption/controllers/migrators/inprocess.go, pkg/operator/encryption/controllers/migrators/inprocess_processor.go, pkg/operator/encryption/controllers/migrators/inprocess_processor_test.go, pkg/operator/encryption/controllers/migrators/metrics.go, pkg/operator/encryption/controllers/prune_controller.go, pkg/operator/encryption/controllers/prune_controller_test.go, pkg/operator/encryption/controllers/state_controller.go, pkg/operator/encryption/controllers/state_controller_test.go, pkg/operator/encryption/encryptionconfig/config.go, pkg/operator/encryption/encryptionconfig/config_test.go, pkg/operator/encryption/secrets/secrets.go, pkg/operator/encryption/state/helpers.go, pkg/operator/encryption/statemachine/transition.go, pkg/operator/encryption/statemachine/transition_test.go, test/e2e-encryption/encryption_test.go, test/library/encryption/errors.go, test/library/encryption/helpers.go, test/library/encryption/perf_helpers.go, test/library/encryption/perf_scenarios.go
This PR syncs 4.4 work with 4.3 mainly doing:
- speeding up migration by a factor: 50k objects in half an hour (before around 1k in 5m)
- added Encrypted condition for the user to see the encryption status
- leave last read-key in encryption config in order to allow backup/restore when encryption-config backup is done after backup, without losing data (compare https://github.com/openshift/enhancements/pull/131).
=> Bug 1776797: encryption: speed-up, Encrypted condition, allow backup/restore

pkg/operator/encryption/deployer/revisionedpod.go, pkg/operator/encryption/deployer/revisionedpod_test.go
On upgrade the openshift-apiserver pods have no revision making the encryption controller fall over.
=> Bug 1779263: encryption: cope with missing revisions on upgrade

pkg/image/registryclient/client.go, pkg/image/registryclient/client_test.go
We can verify that the returned digest matches our expectation cheaply.
May work with schema1, but more focused on schema2 for now.
Testing in openshift/oc#186
=> Verify outbound manifests now that schema1 support is dropped

pkg/operator/v1helpers/helpers.go
since you asked for it in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/285#discussion_r328058781 and on top of that we use it in 3 operators: kcm-o, kas-o and oas-o.
=> Add MapToEnvVars helper function

pkg/controller/controllercmd/builder.go
Leader election client can freeze due to a TCP connection timeout not being set. Then the other timeouts set in the election config have no effect.
=> Bug 1779796: controllercmd: set TCP timeout on leader election client

pkg/operator/status/condition.go, pkg/operator/status/inertia.go, pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
Instead of hard-coding a two-minute inertia, allow the controller-creator to set a custom inertia function.  The previous value was chosen to work fairly well for most cases, but there was contention between important conditions where 2m was pushing too long and less severe conditions where 2m was short enough to catch slow launch-time initialization that triggered distracting Degraded flaps (e.g. the 2m10s missing ConfigMaps in [rhbz#1775922][1], where the bulk of that 2m was taken by other kube-apiserver initialization actions).  With this commit, the kube-apiserver can say:
> 3m of missing ConfigMaps is ok, but only accept 1m of SomeOtherThing before going `Degraded=True`.
or whatever.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1775922
=> pkg/operator/status: Add configurable inertia

pkg/operator/status/condition.go, pkg/operator/status/status_controller_test.go
Instead of MultipleConditionsMatching, you get TypeA_Something::TypeB
/assign @mfojtik @sttts @soltysh
=> show the individual reasons for status conditions on union

pkg/controller/controllercmd/cmd.go
Since providing `--config` to a controller is optional, the config file should not be observed if unspecified.
This is required for https://github.com/openshift/service-ca-operator/pull/88
=> controllercmd: Only observe config file if provided

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
If the revision resources needed by a static pod installer are deleted, static pods are stuck, unable to be upgraded to use the latest revision of the resources. 
This PR detects this situation and moves the static pods to the latest available revision.
=> Bug 1780809: kube-apiserver stuck in Progressing/Degraded if target revision is deleted

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go
ApplySecret was fighting with kube controller manager - service account token controller when used for service accounts. It was constantly deleting the injected data. This PR prevents it.
/cc @deads2k 
needed for https://github.com/openshift/cluster-kube-apiserver-operator/pull/663
=> ApplySecret: Don't erase injected Data for ServiceAccounts

pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/cmd.go
Passing context.Context via struct field is a Go anti-pattern. We need to pass the context directly via function arguments instead.
After this PR land, the bumps in operator will have to fix the way they pass the context.
=> controllercmd: pass context via func argument

alpha-build-machinery/make/lib/golang.mk
`go list ./cmd/...` that is used in resolving `GO_BUILD_PACKAGES_EXPANDED` for some reason fetches the go modules although that's a local reference, respecting mod vendor there force the correct behaviour
/cc @soltysh
=> build-machinery: respect -mod=vendor for go list

pkg/controller/fileobserver/observer.go, pkg/controller/fileobserver/observer_polling.go
This add `fileobserver_action_count{name=ACTION, filename="file"}=N` prometheus metric that can be used to track changes on particular files over time and indicate problems when files are changed too often or not changed at all.
=> fileobserver: prometheus counter for observed actions

pkg/config/leaderelection/leaderelection.go
This will cause faster operator upgrades as we release the leader when the context that we pass to all control loops in operators is cancelled (typically on graceful shutdown).
=> leaderelection: set release on cancel to true

pkg/controller/controllercmd/builder.go
Use protobuf client for leader election. Should decrease the CPU usage when querying for the configmap (but it really is just cosmetic).
=> leaderelection: use proto client

pkg/config/configdefaults/config_default.go
Based on https://github.com/openshift/cluster-authentication-operator/pull/231 we should default to `tcp` instead of forcing `tcp4`
=> config: default bind network to tcp instead of tcp4

pkg/operator/staticpod/controller/node/node_controller.go, pkg/operator/staticpod/controller/node/node_controller_test.go
We see more than 20 clusters reporting this degraded condition for long time. To determine the cause for this we have to investigate the insights data and rely on insights to give us node YAML.
We already have the reason and message for a node being not ready, why not report it via degraded message?
/cc @deads2k 
/cc @sttts
=> staticpod: improve node not ready degraded message to include reason and message

pkg/operator/resource/resourceapply/event_helpers.go, pkg/operator/resource/resourceapply/event_helpers_test.go, pkg/operator/resource/resourcehelper/resource_helpers.go
Generates a string that can be copy/pasted for use with `oc get`.
e.g.: `oc get TYPE[.GROUP]/NAME[ -n NS_NAME]`
Can be used by operator impls to report (log/event/etc.) on resources.
=> helper for logging resource names

test/library/metrics/query.go, vendor/github.com/prometheus/client_golang/api/client.go, vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go, vendor/modules.txt
@marun @sanchezl this PR provides helper functions for prometheus query
I placed a fake bump/testing here:
* https://github.com/openshift/cluster-kube-controller-manager-operator/pull/316
* https://github.com/openshift/cluster-kube-scheduler-operator/pull/191
/cc @sttts
=> add helper functions for running prometheus query

test/library/encryption/helpers.go
if the controller is slow when creating the keys we can get into a state in which we expect the previous key to be no previous key which is wrong.
=> changes the next empty encryption key's name for encryption e2e test

pkg/operator/staticpod/certsyncpod/certsync_controller.go
When emitting an event concerning the absence of a resource, use the namespace and name that were used to try to get the resource, rather than the namespace and name from the result of trying to get the resource (which will both be blank since the resource did not exist).
Remove a superfluous `err` argument in the `Warningf` call made when removing the file for a non-existent secret.  The `err` argument has no corresponding placeholder in the format string; the extra argument, combined with using the empty result's namespace and name, resulted in messages like the following:
Removed file for secret: /%!(EXTRA *errors.StatusError=secrets "user-serving-cert" not found)
As the error is always a "not found" error, it can be omitted.
Follow-up to #546.
* …
=> cert-syncer: Fix events for not-found resources

pkg/operator/resource/resourceapply/apiextensions.go, pkg/operator/resource/resourceapply/generic.go, pkg/operator/resource/resourcemerge/apiextensions.go, pkg/operator/resource/resourceread/apiextensions.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go, pkg/operator/staticpod/controllers.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
1.  automatic informers get wired into the controller and the cache waiting
1. allow static resource management of CRDs
=> support CRDs at v1 throughout the apply stack

pkg/operator/resource/resourceapply/generic.go, pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go, pkg/operator/staticpod/controllers.go, pkg/operator/staticresourcecontroller/static_resource_controller.go, pkg/operator/v1helpers/core_getters.go
Alright, I think this is the last one in the chain.  We have
1. static resource management for the most common types
2. automatic informers get wired into the controller and the cache waiting
3. automatic status reporting for operators with aggregated status.
4. allow static resource management of CRDs
5. update CRD handling to support v1
6. add the ability to use cached clients based on the namespaced informers.
=> add cached client capabilities to stay out of qps jail

pkg/operator/render/options/config.go, pkg/operator/render/options/generic.go
Cluster operators do not use this - they manage post-bootstrap config separately.
Canaries: 
- https://github.com/openshift/cluster-kube-apiserver-operator/pull/732
=> Remove unused post-bootstrap config override from rendering

pkg/controller/controllercmd/cmd.go, pkg/controller/controllercmd/flags.go
When we run multiple library-go based binaries in a pod ports will collide.
e.g. KCM collides on 8433 that was hardcoded
/cc @mfojtik @soltysh
=> Allow adjusting serving info to avoid port collisions

pkg/operator/staticpod/controller/prune/bindata/bindata.go, pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
Adds a 100M memory request/limit to revision pruners, taken from the installer pod's requests: https://github.com/openshift/library-go/blob/941707e97d/pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml#L29-L33
=> Bug 1792501: Add memory request and limit to revision pruner pod

pkg/controller/factory/base_controller.go, pkg/controller/factory/controller_context.go, pkg/controller/factory/controller_test.go, pkg/controller/factory/factory.go, pkg/controller/factory/interfaces.go, pkg/controller/manager/controller_manager.go, pkg/operator/loglevel/logging_controller.go, pkg/operator/loglevel/logging_controller_test.go, pkg/operator/revisioncontroller/revision_controller.go, pkg/operator/revisioncontroller/revision_controller_test.go, pkg/operator/staticpod/certsyncpod/certsync_cmd.go, pkg/operator/staticpod/certsyncpod/certsync_controller.go, pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controller/installerstate/installer_state_controller.go, pkg/operator/staticpod/controller/installerstate/installer_state_controller_test.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go, pkg/operator/staticpod/controller/node/node_controller.go, pkg/operator/staticpod/controller/node/node_controller_test.go, pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go, pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/staticpod/controllers.go, pkg/operator/staticresourcecontroller/static_resource_controller.go, pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Background: As we keep adding more controllers to operators, we keep copying a single boiler plate for new controllers. The boilerplate usually include the Run() function, event handler registration to informers, workers and shutdown handling. 
Problem: It is pretty easy to add an informer to this code and forget to wait for its cache to sync. Refactoring all controllers to do proper graceful shutdown, where all workers are properly terminated (and we wait until they finish their job) is hard as there is no single place to change this but dozen of controllers have to be modified.
This change introduces a "factory" pattern when creating new controllers. In 95% of our controllers, we only observe change on resource(s) via informer and run the "Sync()" function that has main logic.
Adding a …
=> Controller factory

alpha-build-machinery/make/targets/golang/build.mk, alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
build-machinery supports only golang >=1.13
(Yes, we have come to a point where we need this enforced. Version check is on my list next.)
There was a case when someone was building it with 1.12 which resulted in silently failing `go list` in a subshell and `GO_BUILD_PACKAGES_EXPANDED` being empty. Since the time we have added building multiple packages and introduced a for loop, with empty var it executes nothing, but ends with exit code `0`. That made the image build continue. Unfortunately this was combined with a bug in the image builder that also didn't error out on `COPY` instruction missing the files.
```
RUN make build --warn-undefined-variables
build flag -mod=vendor only valid when using modules
make: Nothing to be done for `build'.
```
We need to fix our part to be resilient and …
=> Make sure there are some packages to be build

alpha-build-machinery/make/lib/golang.mk, alpha-build-machinery/make/targets/openshift/deps.mk
if built without network connectivity, `go list` without `-mod=vendor` flag fails and GO_PACKAGE would be empty
/cc @soltysh
=> Bug 1793267: Add -mod=vendor fallback for `go list`

pkg/controller/factory/base_controller.go
This prevents factory controllers to run two sync()'s in parallel. Instead the time based resyncs are now handled via queue.
=> factory: fix time based resync to use queue instead of calling sync directly

pkg/operator/condition/condition.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
the static pod operator directly sets available and progressing, which makes it impossible to appropriately compose the conditions inside of an operator.
=> bug 1798725:  allow static pod operator to be composed

pkg/operator/staticpod/controller/installer/bindata/bindata.go, pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml, pkg/operator/staticpod/installerpod/cmd.go
by substituting the NODE_NAME, we can select which env vars and arguments we want to use in commands.  This allows a single static pod template to be used on nodes that must have different arguments
=> bug 1800321: add substitution for NODE_NAME inside of static pods

pkg/operator/staticpod/controller/installer/bindata/bindata.go, pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml, pkg/operator/staticpod/controller/prune/bindata/bindata.go, pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
The kubelet requires cpu and memory limits both specified to become guaranteed.
=> bug 1800609: add cpu limits to become guaranteed

go.mod, go.sum, vendor/github.com/openshift/build-machinery-go/OWNERS, vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk, vendor/github.com/openshift/build-machinery-go/make/lib/version.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk, vendor/modules.txt
We need to pick the PR lowering go version after CI went back, builder fixes for Mac and fixing verify-deps exit codes.
/cc @soltysh @mfojtik
=> bump: openshift/build-machinery-go

pkg/operator/staticpod/installerpod/cmd.go
the etcd-o has a demonstrated need to substitute other configmaps for node name.
=> bug 1806692: substitute all content for node name and revision

pkg/operator/staticpod/installerpod/cmd.go
We need this for recovery shell scripts we place on the nodes.
=> set .sh files to be executeable

pkg/crypto/crypto.go
Previously a serial number of 1 was used when generating signing certificates. If such a certificate was ever rotated, the new signing certificate would have the same issuer+serial number which violates the rfc. Setting a random serial number ensures that signing certificates can be uniquely identified for a given issuer when rotated.
=> Bug 1810036: Set a random serial number for signing certificate templates

pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/builder_test.go, pkg/controller/factory/base_controller.go, pkg/controller/factory/factory.go, pkg/controller/factory/interfaces.go, pkg/controller/manager/controller_manager.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/resourcesynccontroller/resourcesync_controller_test.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controllers.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
First commit add controller manager that groups multiple controllers and **wait** until all controllers are terminated. This is used later in leader election block for builder where we allow controllers to properly finish before terminating them forcefully. IF controllers exit cleanly and in time, we exit 0 (must be for graceful termination), otherwise we exit 1.
Additionally, this converts resourcesync controller to use factory and allow to build the SyncContext upfront for unit testing or for more tide control on event recorder.
=> Properly terminate controllers on leader election lost/shutdown

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go, pkg/operator/resource/resourcemerge/object_merger.go
A couple of components were using run-level labels on their
namespaces even though they did not have to. Make it possible
to remove this label with the library-go functions while not
changing the other labels/annotations in case these are maintained
automatically by a different controller.
=> resourceapply: Allow removing run-level labels from namespaces

pkg/config/leaderelection/leaderelection.go, pkg/controller/factory/base_controller.go, pkg/controller/factory/controller_context.go, pkg/controller/factory/controller_test.go, pkg/controller/factory/factory.go, pkg/controller/factory/interfaces.go, pkg/operator/apiserver/controller/apiservice/apiservice_controller.go, pkg/operator/apiserver/controller/apiservice/apiservice_controller_test.go, pkg/operator/apiserver/controller/nsfinalizer/finalizer_controller.go, pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go, pkg/operator/management/management_state_controller.go, pkg/operator/management/management_state_controller_test.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/staleconditions/remove_stale_conditions.go, pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
This moves more controllers to controller factory.
It also makes one more extension point in factory, which is `PostRunHook`. This allows to register custom triggers or other asynchronous code to run **after** the controller us run.
=> Migrate controllers to factory

pkg/operator/loglevel/logging_controller.go, pkg/operator/loglevel/logging_controller_test.go, pkg/operator/loglevel/util.go, pkg/operator/staticpod/controller/installer/installer_controller.go
Properly determine the current log level and set the `klog.V()` level so we don't run with `V(0)`.
Also add unit tests to make sure this never break.
=> logging: properly set log level

pkg/operator/certrotation/client_cert_rotation_controller.go
Fixes panic in bootstrap:
```
panic: interface conversion: interface {} is nil, not bool
goroutine 1249 [running]:
github.com/openshift/library-go/pkg/operator/certrotation.CertRotationController.Sync(0x219cac1, 0x13, 0x21b9933, 0x21, 0x21a8e3d, 0x19, 0x126ad20e840000, 0x9356907420000, 0x0, 0x256fd00, ...)
github.com/openshift/library-go@v0.0.0-20200313123224-fc1c562fafc7/pkg/operator/certrotation/client_cert_rotation_controller.go:80 +0x3f4
```
Found in https://github.com/openshift/cluster-kube-apiserver-operator/pull/794
=> certrotation: check the context value for nil

pkg/operator/configobserver/apiserver/observe_cors.go, pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/featuregates/observe_featuregates.go, pkg/operator/configobserver/proxy/observe_proxy.go, pkg/operator/configobserver/unstructured.go
Config observers are supposed to return the existing config in case of error. This is not uniformely implemented. Some observers even return the entire observed config, including fields from other observers.
This PR switch existing config reconstruction trivial by just filter the whole observed config by the keys the observer is interested in. This is a three liner in each observer, super simple and uniform.
=> config-observers: prune returned config

pkg/operator/encryption/deployer/unionrevisionedpod.go, pkg/operator/encryption/deployer/unionrevisionedpod_test.go
This PR implements `UnionRevisionLabelPodDeployer` that returns a unified state from multiple distinct deployers. That is: none has reported an error, all have converged, all have observed exactly the same encryption configuration.
Visit https://github.com/openshift/enhancements/blob/master/enhancements/etcd/etcd-encryption-for-separate-oauth-apis.md for more details.
=> UnionRevisionLabelPodDeployer

pkg/operator/resource/resourceapply/storage.go, pkg/operator/resource/resourceapply/storage_test.go, pkg/operator/resource/resourceread/storage.go
The CSIDriver object contains information about a CSI driver.
Up until recenty, this object was created by the cluster-driver-registrar sidecar container, however, this sidecar has been deprecated. As a result, operators need to create this object when installing a CSI driver.
=> Add CSIDriver to resourceread and resourceapply

pkg/operator/encryption/deployer/deploynodeprovider.go
it knows how to return the node list from nodes matching the node selector of a Deployment, it will be used by `OAS-O` and `CAO`
a slightly modified version of https://github.com/openshift/cluster-openshift-apiserver-operator/blob/master/pkg/operator/deploynodeprovider.go
=> moves DeploymentNodeProvider 

pkg/operator/configobserver/apiserver/observe_cors_test.go, pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go
This is to support config observation for CAO where one operator deploys two different payloads
Used in https://github.com/openshift/cluster-authentication-operator/pull/242
=> apiserver: add prefix to tls and cors observers

pkg/operator/resource/resourceapply/storage.go, pkg/operator/resource/resourceapply/storage_test.go
StorageClasses are currently always updated on every operator resync.
The reason is `ApplyStorageClass()` does a `DeepEqual` comparison between the SCs, however, 
1) creation time are always different and 
2) the object got from the API doesn't contain `TypeMeta` set.
As a result, `DeepEqual()` returns `false` and the SC is always updated.
=> Fix StorageClasses comparison

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go
SA token secrets are special. When we copy them or create revisions from them we need to make sure the already have a token injected from KCM SA controller as that is being  done asynchronously to the Secret creation. We also have to avoid copying the `kubernetes.io/service-account.name` annotation to prevent the KCM SA controller from updated the token in the copies or revisions.
/hold
for proof in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/383
/cc @deads2k @soltysh
=> Bug 1819256: Fix SA token sync

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go
backport of https://github.com/openshift/library-go/pull/764 for https://bugzilla.redhat.com/show_bug.cgi?id=1813512 + https://bugzilla.redhat.com/show_bug.cgi?id=1820255 + https://bugzilla.redhat.com/show_bug.cgi?id=1820261
/cc @deads2k @sttts @soltysh
=> [release-4.4] Fix SA token sync

pkg/controller/controllercmd/cmd.go, pkg/controller/fileobserver/observer_polling.go, pkg/controller/fileobserver/observer_polling_test.go
Scenario:
a) AddDefaultRotationToConfig():
1. no serving cert and key found in expected directory
2. creates self-signed serving cert/key pair
3. serving-cert key-pair appears in the expected directory
b) WithRestartOnChange() -> AddReactor()
4. does not see starting content for the observed files
5. hashes for the expected cert/key pair are counted from the
actual files but the controller will keep serving with the
self-signed cert/key pair now
This was most probably caused by the line
```
certDir = temporaryCertDir
```
which caused that starting content was added for wrong two files.
=> Bug 1779438: fix race for controller commands

pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target_test.go, pkg/operator/encryption/controllers/state_controller_test.go, pkg/operator/encryption/encryptionconfig/secret.go, pkg/operator/encryption/secrets/secrets.go, pkg/operator/encryption/testing/helpers.go, pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go, pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Kubernetes validation silently ignores secret changes and doesn't return an error.
https://github.com/kubernetes/kubernetes/blob/98e65951dccfd40d3b4f31949c2ab8df5912d93e/pkg/apis/core/validation/validation.go#L5048
This leads to the resource sync controller constantly trying to update to the desired state. (mutating admission vs. DeepEqual)
/cc @deads2k
=> Fix ApplySecret for Type changes

pkg/controller/controllercmd/builder.go
This helper will avoid making mistakes when copying the pkg/version content for control plane operators and also templatize the description.
It will also be easier to replace the legacyregistry from this point in future.
=> Add WithVersion() to command builder that reports binary version to prometheus

pkg/controller/controllercmd/cmd.go
Note, after this change, the pkg/version in each operator that receives this change must change and they must drop the `func init()` and only leave the `func Get()` in this package.
Failing to do that will result in panic during operator/binary runtime as the version metric will be registered twice.
=> cmd: add WithVersion to StartController

pkg/operator/resource/resourceapply/apps.go
This removes the need for the caller to supply an expected generation and be able to force a rollout. Any state that is not present in the spec should instead be added as an annotation so that a rollout will be triggered when the annotation changes.
This is intentionally a breaking change to encourage switching to the revised function. Callers who want to continue using the previous (deprecated) implementation will need to change the name of the function they are calling to `ApplyDeploymentWithForce`.
Canaries:
- https://github.com/openshift/cluster-authentication-operator/pull/272
- https://github.com/openshift/cluster-openshift-apiserver-operator/pull/354
=> Update Apply{DaemonSet,Deployment} to rely on a hash of the spec

pkg/controller/controllercmd/builder.go
Found these when checking something in Prometheus:
```
_build_info{buildDate="2020-04-21T15:28:33Z", endpoint="https", gitCommit="158288a", gitTreeState="dirty", gitVersion="v0.0.0-alpha.0-240-g158288a", instance="10.128.0.24:8443", job="metrics", namespace="openshift-config-operator", pod="openshift-config-operator-6b9855859b-pszjx", service="metrics"} | 1
-- | --
_build_info{buildDate="2020-04-22T06:02:43Z", endpoint="https", gitCommit="bc12831", gitVersion="v0.0.0-alpha.0-749-gbc12831", instance="10.130.0.2:8443", job="metrics", namespace="openshift-kube-controller-manager-operator", pod="kube-controller-manager-operator-56f7b794bf-fv8p9", service="metrics"} | 1
_build_info{buildDate="2020-04-21T22:37:27Z", endpoint="https", gitCommit="2a81dc6", gitTreeState="clean", gitVersion="v0.0.1- …
```
=> version: make sure to always have namespace when reporting version

pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Fixing a typo in mutex name inside unit test.
=> resourcesynccontroller: fix race in unit test

pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/builder_test.go, pkg/controller/controllercmd/cmd.go, pkg/operator/events/eventstesting/recorder_testing.go, pkg/operator/events/eventstesting/recorder_wrapper.go, pkg/operator/events/recorder.go, pkg/operator/events/recorder_in_memory.go, pkg/operator/events/recorder_logging.go, pkg/operator/events/recorder_upstream.go, pkg/operator/events/recorder_upstream_test.go, pkg/operator/staticpod/certsyncpod/certsync_cmd.go
This change will wire the broadcaster `Shutdown()` function into library-go event recorder.
This is later facilitated in controllercmd builder, where this is called when the binary leader election change.
In addition, this change will provide more fine-tuned correlator options that operators which send a lot of events and don't want to loose events should use. These are default now for controllercmd builder based operators.
=> events: make kube broadcaster shutdown gracefully and tune correlator so we don't loose events

pkg/config/clusteroperator/v1helpers/status.go
Don't show ugly JSON diff when only the operator version changes.
Before this PR, when only `Versions` changed in a ClusterOperator:
```
Status for clusteroperator/csi-snapshot-controller changed: {"conditions":[{"type":"Degraded","status":"False","lastTransitionTime":"2020-04-29T11:32:49Z","reason":"AsExpected"},{"type":"Progressing","status":"False","lastTransitionTime":"2020-04-29T11:34:04Z","reason":"AsExpected"},{"type":"Available","status":"True","lastTransitionTime":"2020-04-29T11:34:04Z","reason":"AsExpected"},{"type":"Upgradeable","status":"True","lastTransitionTime":"2020-04-29T11:32:49Z","reason":"AsExpected"}],"
A: relatedObjects":[{"group":"","resource":"namespaces","name":"openshift-cluster-storage-operator"},{"group":"","resource":"namespaces","name":"openshift-cluster-stora …
```
=> Fix ClusterOperator event when version changes

pkg/operator/staticpod/controller/monitoring/bindata/bindata.go, pkg/operator/staticpod/controller/monitoring/manifests/service-monitor.yaml
Previously the staticpod controller was configuring the service monitor to source the service ca from the service account token configmap. As of 4.5 the service ca will no longer be set in token
configmap, so its necessary to source the service ca from the prometheus configmap (as per the example of most operators).
/cc @deads2k @sttts
=> Bug 1813894: Fix staticpod controller to use service ca from prometheus

pkg/operator/resource/resourceapply/apps.go
Cherrypick of #773. Did not apply cleanly due to the addition of context to all client calls in master.
/cc @deads2k
=> [release-4.4] Update Apply{DaemonSet,Deployment} to rely on a hash of the spec

pkg/operator/staticpod/controller/installer/bindata/bindata.go, pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml, pkg/operator/staticpod/controller/prune/bindata/bindata.go, pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
Doubling the resource and limits values to avoid installer and pruner pod OOMKills on ppc64le machines
=> Bug 1812126: double memory resource request and limits values

pkg/operator/revisioncontroller/revision_controller.go, pkg/operator/revisioncontroller/revision_controller_test.go, pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go
This carries some of the changes in https://github.com/openshift/library-go/pull/794, specifically when creating a new revision it checks for interrupted `InProgress` revisions and marks them as `Abandoned`
=> Update interrupted InProgress revisions to Abandoned

pkg/controller/factory/base_controller.go, pkg/operator/revisioncontroller/revision_controller.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
This change will remove errors like this from the log:
> E0604 15:58:52.824104   14930 base_controller.go:180] "TargetConfigController" controller failed to sync "key", err: synthetic requeue request
Developers can use `factory.SyntheticRequeueError` to trigger this from `sync()`.
=> factory: add mechanism to allow synthetic requeue without error

go.mod, go.sum, pkg/controller/factory/base_controller.go, pkg/controller/factory/factory.go, pkg/controller/factory/factory_test.go, vendor/github.com/robfig/cron/v3/.gitignore, vendor/github.com/robfig/cron/v3/.travis.yml, vendor/github.com/robfig/cron/v3/LICENSE, vendor/github.com/robfig/cron/v3/README.md, vendor/github.com/robfig/cron/v3/chain.go, vendor/github.com/robfig/cron/v3/constantdelay.go, vendor/github.com/robfig/cron/v3/cron.go, vendor/github.com/robfig/cron/v3/doc.go, vendor/github.com/robfig/cron/v3/go.mod, vendor/github.com/robfig/cron/v3/logger.go, vendor/github.com/robfig/cron/v3/option.go, vendor/github.com/robfig/cron/v3/parser.go, vendor/github.com/robfig/cron/v3/spec.go, vendor/modules.txt
Allows to specify a cron based syntax when specifying manual controller resync times:
```golang
factory.New().ResyncSchedule("@every 1s").ToController()     // Every second
factory.New().ResyncSchedule("@hourly").ToController()       // Every hour
factory.New().ResyncSchedule("30 * * * *").ToController()    // Every hour on the half hour
```
=> Add simple cron based scheduler to controller factory

pkg/operator/eventwatch/controller.go, pkg/operator/eventwatch/controller_test.go
This controller can be used to filter interesting event reasons and take action on them.
For example, this allow to register handler, that will update Prometheus counter when an interesting event is observed (or update operator conditions, etc..).
Example:
```golang
eventwatch.New().WithEventHandler("kube-apiserver", "Reason", func(*corev1.Event) error {
// prometheusCounter++
return nil
}).ToController(informers, eventClient, eventRecorder)
```
=> eventwatch: add controller

pkg/operator/configobserver/config_observer_controller_test.go, pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/management/management_state_controller_test.go, pkg/operator/status/status_controller_test.go, pkg/operator/v1helpers/interfaces.go, pkg/operator/v1helpers/test_helpers.go
This PR is intended to get more clarification. Will fix the tests once I know the direction.
Use case: we are creating a library to use in CSI operators. This library uses the `genericoperatorclient`. At some point, we need to update the CR status and set the right generation, like it's done here:
https://github.com/openshift/machine-api-operator/blob/5688547505e7963783f04ad0737740cfac4b6457/pkg/controller/machineset/status.go#L85-L89
As a result, I need access to the CR metadata as well (not only spec and status).
@deads2k @sttts could you take a look, please?
My main question is: is it OK to change the `OperatorClient`  interface to get the CR metadata? Or that should be done differently?
=> operatorclient: add metadata methods to interface

pkg/operator/eventwatch/controller.go, pkg/operator/eventwatch/controller_test.go
Similar events can be aggregated into one single event where the count is increased. In that case, the current implementation of this controller won't call process() (in case the count is increased).
This can lead into situation where an event is fired multiple times, but metrics are not increased because the event was already acknowledged.
This change the annotation to track the last seen acknowledged count and run the process() every time the "count" field is updated (does not match with the annotation).
=> eventwatch: process events with increasing counter

pkg/image/registryclient/client.go
This PR adds information about why the client thinks that the registry doesn't support v2 API. The information may be provided back to the registry administrators if the registry is expected to support v2 API, but sometimes the /v2/ endpoint misbehaves.
=> Bug 1845766: Add status code to ErrNotV2Registry

pkg/config/leaderelection/leaderelection.go
compare to https://github.com/kubernetes/kubernetes/blob/0d674c4edb3af80a5630223819d9203e43679ba5/cmd/kube-controller-manager/app/controllermanager.go#L264-L270
@jsafrane see if this helps you.
=> use a hostname in leader election id so we can the leaseholder

pkg/controller/controllercmd/builder.go, pkg/controller/factory/base_controller.go
In case of panic() inside the sync() the controller can crash the operator and cause it to crashloop. This will prevent that using the same way as API server is handing this and it allows the controllers to recover themself.
NOTE: This might lead to wedged controller loops that never clear their conditions, but it is better than crashlooping pods?
=> factory: handle panic in sync

pkg/operator/loglevel/logging_controller.go, pkg/operator/loglevel/logging_controller_test.go
This allows to have debug CI jobs against PR's that have debug commit which increases the operator loglevel (which is normally set by operator config).
=> loglevel: allow to override the default log level

pkg/operator/eventwatch/controller.go, pkg/operator/eventwatch/controller_test.go, pkg/operator/eventwatch/glob.go
This allows to match the event reasons just by substring. An example is `FooBarPanic` event reason (we send this events when a controller panic occur) can be matched with `.WithEventHandler("namespace", "Panic", handlerFn)`.
=> eventwatch: allow to match reason substring

pkg/operator/configobserver/apiserver/listers.go, pkg/operator/configobserver/apiserver/listers_test.go, pkg/operator/configobserver/apiserver/observe_cors_test.go, pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go, pkg/operator/configobserver/apiserver/observe_tlssecurityprofile_test.go, pkg/operator/configobserver/etcd/OWNERS, pkg/operator/configobserver/etcd/listers.go, pkg/operator/configobserver/etcd/listers_test.go, pkg/operator/configobserver/etcd/observe_etcd_endpoints.go, pkg/operator/configobserver/etcd/observe_etcd_endpoints_test.go
this PR moves existing observer to the shared library as it will be used by CAO and OAS-O.
I slightly changed the code so that it supports passing a custom path under which the configuration will be saved.
=> move the etcd config observer to library-go

pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go
This PR adds `NewNestedConfigObserver` controller that creates a config observer that watches changes to a nested field (nestedConfigPath) in the config.
The new function is useful when the config is shared across multiple controllers in the same process.
For example, passing `operandOne` in the `nestedConfigPath` argument will create a controller that watches only values stored under that path.
```
"operandOne": {
"foo": "one",
"bar": "two",
"baz": "three"
},
"operandTwo": {
"foo1": "one",
"bar1": "two",
"baz1": "three"
}
}`
``
=> NewNestedConfigObserver controller

pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csidrivercontroller/csi_driver_controller.go, pkg/operator/csi/csidrivercontroller/csi_driver_controller_test.go, pkg/operator/genericoperatorclient/dynamic_operator_client.go
PR https://github.com/oVirt/csi-driver-operator/pull/12/files landed, so the CSI Driver controller needs to react to a different resource: `clustercsidrivers`. In addition to that, the controller should only react if the CR has a certain name.
=> CSI: Accept custom instance name

pkg/controller/factory/factory.go
I noticed `factory.New().WithPostStartHooks(foo)` does not do anything useful.
The hooks must be copied to newly created Controller, so the Controller can actually find them when their time comes.
=> Fixed PostStartHook execution

pkg/operator/status/condition.go, pkg/operator/status/status_controller.go
The function is useful outside of StatusSyncer controller. Added two flavors, depending if the caller needs `OperatorCondition` or
`ClusterOperatorStatusCondition`.
=> Make unionCondition public

pkg/operator/configobserver/masterurl/observe_masterurl.go, pkg/operator/configobserver/masterurl/observe_masterurl_test.go
promotion of https://github.com/openshift/cluster-kube-controller-manager-operator/tree/master/pkg/operator/configobservation/masterurl for inclusion in kube-scheduler.
will open proof
=> add configobserver for the master url arg for kcm and ks

go.mod, pkg/operator/apiserver/controller/workload/workload.go
the `EnsureAtMostOnePodPerNode` will assign a stable anit-affinity value to unblock usage of `ApplyDeployment` method.
It turned out that assigning a random value is not necessary and the deployment controller will roll out a new version even if the value is static.
=> tweak EnsureAtMostOnePodPerNode method

pkg/operator/apiserver/audit/audit_policies.go, pkg/operator/apiserver/audit/audit_policies_test.go, pkg/operator/apiserver/audit/bindata/bindata.go, pkg/operator/apiserver/audit/manifests/audit-policies-cm.yaml
makes it more generic so that it can be used by the API servers.
=> tweaks audit policies

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/status/version.go
This fixes a bug, but I don't know which one.
Proof PRs are needed for the big static pod operator.  Will link shortly.
=> static pod operator should not update versions until the image is new

pkg/operator/staticpod/controller/installer/installer_controller.go
The line
```
ret.TargetRevision = currNodeState.CurrentRevision
```
led to a dead-lock because the installer controller only does anything if either
- all `TargetRevision`s are zero
- or the `TargetRevision` value is larger than `CurrentRevision`.
We went into the second case and the controller dead-locked.
**Note:** just before this code there is the `ensureInstallerPod` invocation. We run into the bug when the pod apply call fails (e.g. of some network issue).
**Note:** when the installer pod disappears again and again (for whatever reason), this could hotloop (of course we do the usual backoff in the controller though). But this is the same
for the existing OOM case.
=> Bug 1858763: static-pod-installer: remove deadlock by recreating installers that disappear

pkg/controller/factory/base_controller.go, pkg/controller/factory/base_controller_test.go, pkg/controller/factory/factory.go
This change fix a case when the operator is shutting down **before** the caches are synced. In that case, the main context is cancelled and the WaitForCacheSync() receives stop which result in panic. While these panics are harmless, they look ugly and they might trigger some post-processing filters in CI that look for panics.
=> factory: do not panic on cache sync when we shutdown

pkg/operator/resourcesynccontroller/interfaces.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go
If the `Provider` field is set for the sync source and the sync will fail with error, the error message will include the `... (provided by FOO)` string that helps identify the resource provider.
Practically, when an ingress operator is not running and we fail to sync a config map provided by this operator, the auth operator will error out with "config map foo not found", but it does not say what provides that config map (or it does not mention where to start looking).
=> resourcesync: add provided by to sync error message

pkg/operator/staticpod/installerpod/cmd.go
With `Fatalf` the klog will dump a not really useful stacktrace into log which is then reported in operators as a reason the installer pod fails (hiding the original reason). `Exit()` should still exit 1 but omit the stacktrace.
=> installer: do not log stacktrace when installer pod fail

pkg/operator/staticpod/controller/installer/blame.go, pkg/operator/staticpod/controller/installer/installer_controller.go
Provide blame given the reason message. When the installer pod fails because of networking is not working, suggest admins to look into networking-operator for possible reason.
=> installer: add reason with blame

pkg/operator/resource/retry/retry.go, pkg/operator/resource/retry/retry_test.go
Log retries on connection errors with the connection errors so we know the installer actually retry them.
=> installer: log connection errors on retry

pkg/operator/loglevel/logging_controller.go, pkg/operator/loglevel/logging_controller_test.go, pkg/operator/loglevel/util.go
Only report an event (and log it) on failures and fall back to the default log level (`Normal` in most cases).
We can't do hard validation to prevent from breaking working clusters with potentially bad `logLevels`.
=> Validate operatorSpec.logLevel

pkg/operator/staticpod/controller/installer/installer_controller.go
The line
```
ret.TargetRevision = currNodeState.CurrentRevision
```
led to a dead-lock because the installer controller only does anything if either
- all `TargetRevision`s are zero
- or the `TargetRevision` value is larger than `CurrentRevision`.
We went into the second case and the controller dead-locked.
/assign @sttts
=> [release-4.4] Bug 1876484: static-pod-installer: recreate installers that disappeared

pkg/operator/resource/resourceread/apiextensions.go
Use the right SchemeGroupVersion. Reading v1 CRD manifest panics with:
```
panic: converting (v1.CustomResourceDefinition) to (v1beta1.CustomResourceDefinition): unknown conversion [recovered]
```
/assign @sttts @deads2k
=> Fix reading of CRD v1

pkg/operator/apiserver/controller/workload/workload.go, pkg/operator/apiserver/controllerset/apiservercontrollerset.go
We don't need to pass full informer factory to this controller, pass only things we really need (pod lister).
=> workload: switch to use pod lister instead of passing full informer factory

pkg/operator/loglevel/logging_controller.go, pkg/operator/loglevel/logging_controller_test.go, pkg/operator/loglevel/util.go
Report event (and log it) on failures and fall back to the default log level
(Normal in most cases).
We can't do hard validation to prevent from breaking working clusters with
potentially bad logLevels.
(cherry picked from commit 29b87426f36212e3a2873a707fa03869507a9082)
=> Bug 1878007: Validate operatorSpec.logLevel

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Instead of: `... container "foo" is not ready: unknown reason` if the container is running but not ready because it failed the probe write: `... container "foo" is running for 7 minutes but is not ready: unknown reason`
=> staticpodstate: report if container is running when not ready

pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
This PR updates the status reasons in progressing scenarios to be a bit more explicit. This should reduce the number of "AsExpected" reasons that we see.
=> Bug 1879475: Update status reasons to be more explicit

pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go
Some CSI Drivers need to be given a cluster ID so that they can tag volumes and snapshots they create.
This is done so that the installer can filter those resources out and delete them on cluster deletion.
=> csi: add ${CLUSTER_ID} to placeholders

pkg/verify/configmap.go, pkg/verify/verify.go, pkg/verify/verify_test.go
The code currently wrongly uses implementation types rather than interfaces, this code fixes that by exposing an interface and ensuring all the types implement it properly. 
/assign @wking @jottofar
=> verifier: expose Interface and hide implementation details

pkg/route/OWNERS, pkg/route/routeapihelpers/routeapihelpers.go, pkg/route/routeapihelpers/routeapihelpers_test.go
Constructing a usable URI for a route is non-trivial code that is useful in many route consumers.  Save consumers a few lines by creating a helper in a shared location for centralized maintenance.
Owners from [`router/OWNERS`][1].
CC @Miciah
[1]: https://github.com/openshift/router/blob/189bd7fd5594e09e85b9af178738ae3550a39995/OWNERS
=> pkg/route: Add a package with route helpers

pkg/image/reference/reference.go, pkg/image/reference/reference_test.go
This is useful in mirroring contexts, where a set of images may be mirrored into the same registry, or into the same namespace of a target.
For example, `oc adm catalog mirror` allows you to mirror a catalog into a specific registry or location, so the destination for a mirror can be `localhost:5000` or `quay.io` or `quay.io/my-namespace` or `docker.io/my/nested/org` etc.
Unlike `oc image mirror`, the source is a large list of images instead of only one. Adding support for parsing partial repository names makes it easier to use `TypedImageReferences` in `oc adm catalog mirror`
=> image/reference: support parsing partial repo names

pkg/operator/encryption/controllers/migration_controller.go
Now we ignore errors from setResourceMigrated function, which can lead to unpredictable behavior in runtime. To prevent this we add the standard error checking in the function.
=> Check errors if we can't annotate a secret

pkg/operator/staticpod/controller/installer/installer_controller.go
When a new revision was pending and the previous installer had succeeded, but the operand was not ready yet, we marked that revision as failed. This made the operator to degrade.
=> Bug 1886627: operator/installer: don't mark a successful installer with pending revision as failed

pkg/operator/status/condition.go
If none of the interesting conditions have anything to say, and nothing bad is happening, explicitly say "All is well".  This makes a clearer distinction between "nothing is wrong" and "some things are concerning, but inertia or sub-condition status are keeping me from actually going degraded yet".
=> pkg/operator/status/condition: Say "All is well" with no interesting conditions

pkg/operator/configobserver/network/observe_network.go, pkg/operator/configobserver/network/observe_networking_test.go
This has been the subject of FIXMEs for a while...
AFAIK this is used by cluster-kube-apiserver-operator and cluster-kube-controller-manager-operator, and both of their operands have been updated to be able to deal with multiple values.
=> Change GetServiceCIDR() to GetServiceCIDRs() for dual-stack support

pkg/image/reference/reference.go, pkg/image/reference/reference_test.go
this was incorrectly detecting images without a registry, but with a
tag that included a '.' as a registry-only image reference, instead
of a name+tag image reference.
The corrects an issue introduced in 670e819
=> fix image reference parsing when tag includes a `.`

pkg/operator/loglevel/logging_controller.go, pkg/operator/loglevel/util.go
Using lower case is the way to go.
=> Fixing function name case

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
This caused a storm of OperatorStatusChanged events.
=> controller/staticpodstate: don't use relative times in conditions

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
- containers not being ready is normal, and only get concerning if it stays  like that beyond the probe failure duration
- don't print "unknown reason" for waiting state in case it is running already.
=> Bug 1890724: controller/staticpod: reduce noise of not-ready containers

go.mod, pkg/config/client/client_config.go, pkg/network/dialer.go, pkg/network/dialer_linux.go, pkg/network/dialer_others.go
This PR sets the `TCP_USER_TIMEOUT` (https://man7.org/linux/man-pages/man7/tcp.7.html) socket option which controls for how long transmitted data may be unacknowledged before the connection is forcefully closed.
Without that option, we rely on the TCP stack to detect broken network connection. This can take up to 15 minutes. During that time our platform might be unavailable. 
There are already reported cases in which aggregated APIs (i.e. `openshift-apiserver`) were unable to establish a new connection to the Kube API for 15 minutes after "ungraceful termination" (https://bugzilla.redhat.com/show_bug.cgi?id=1881878 and https://bugzilla.redhat.com/show_bug.cgi?id=1879232#c39)
It looks like detecting broken connections on the application level is getting more traction and is preferable. …
=> Set TCP_USER_TIMEOUT socket option

pkg/operator/resource/resourceapply/monitoring.go
If ApplyServiceMonitor fails to Get() an existing resource because it
is not there, it correctly handles the error and creates the
resource. However, if Get() fails for some other reason the error was
left unhandled, causing a panic later when a pointer is
uninitialized. This change handles the error to avoid the panic.
See the machine-api-operator logs in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/671/pull-ci-openshift-machine-api-operator-master-e2e-metal-ipi/1318544074000568320 for an example of the panic. I suspect it's caused by not having RBAC set up for ServiceMonitor.
=> add a check for an unhandled error in ApplyServiceMonitor

pkg/network/dialer_linux.go
wrapping the DialContext method and setting the socket options on a copy of the file descriptor is not deterministic.
as per documentation attempting to change properties of the original using this duplicate
may or may not have the desired effect.
instead we should set the options on the original file descriptor.
=> improve DefaultClientDialContext

pkg/git/repository.go, pkg/git/repository_test.go
- Adds capability to add git configuration values to the environment
default. This is one of the following:
- The file or option specified by the GIT_CONFIG environment variable.
- The repository-specific git configuration ($location/.git/config)
- Document that AddLocalConfig and AddGlobalConfig can fail if the
GIT_CONFIG environment variable is set.
=> Bug 1896446: Add git configuration to the environment default

test/library/apiserver/apiserver.go
Provides a convenience function for ensuring that APIs have converged to the same revision. The function is meant to be used in tests that require rolling out a new version (i.e. config change).
The API Servers must stay on the same revision for at least `waitForAPIRevisionSuccessThreshold * waitForAPIRevisionSuccessInterval`.
Mainly because of the difference between the propagation time of triggering a new release and the actual roll-out.
Observations:
- rolling out a new version is not instant you need to account for a propagation time (~1/2 minutes)
-  for some API servers (KAS) rolling out a new version can take ~10 minutes
=> tests: provides WaitForAPIServerToStabilizeOnTheSameRevision waits until all API Servers are running at the same revision

pkg/operator/encryption/controllers/state_controller_test.go, pkg/operator/encryption/statemachine/transition.go, pkg/operator/encryption/statemachine/transition_test.go
it turns out that the list of resources to encrypt provided to the encryption controllers is not static and can change over time.
this PR makes the necessary changes to support removing unused GR from the encryption config.
=> encryption controllers: reduce GRs

pkg/operator/apiserver/controllerset/apiservercontrollerset.go, pkg/operator/encryption/controllers.go, pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/key_controller_test.go
allows for specifying an optional prefix for retrieving unsupported config for the encryption controllers
=> unsupported encryption config

pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/key_controller_test.go
there's no need to convert `UnsupportedConfigOverrides.Raw` from `yaml` to `json` as it always comes as `json`. 
I suspect that this code was added because passing no data to `Unmarshal` has unexpected behaviour and could be avoided by examining the lenght of the input.
See for more details:
https://play.golang.org/p/dsWkiPrzZoL
=> encryption key controller: cleans up reading unsupportedEncryptionConfig

pkg/operator/configobserver/etcd/observe_etcd_endpoints.go, pkg/operator/configobserver/etcd/observe_etcd_endpoints_test.go
changes `ObserveStorageURLs` so that it allows for setting previously reserved addresses. That is addresses with `192.0.2.` prefix for v4 and `2001:db8:` for v6.
these addresses should be accepted sine we don't implement RFC 5735, 5737.
=> ObserveStorageURLs: allows for setting reserved IPs as specified in RFC 5735, 5737

pkg/operator/resource/resourceapply/core_test.go, pkg/operator/resource/resourcemerge/object_merger.go
EnsureMeta would report modified=true even if the annotation marked
for removal was already not present in the existing object
should be proven to work by https://github.com/openshift/service-ca-operator/pull/109
=> resourceapply: fix reporting modified on EnsureMeta

pkg/operator/connectivitycheckcontroller/OWNERS
This is to handoff ownership to Network team of this controller piece.
=> Add OWNERS to connectivitycheckcontroller and rcarrillocruz as approver

pkg/operator/configobserver/config_observer_controller_test.go
Exposes undeterministic merge introduced in mergo v0.3.9
To test locally...
`go get github.com/imdario/mergo@v0.3.9` and run this test
=> Add unit test to expose undeterministic merge with empty string key

pkg/route/OWNERS, pkg/route/routeapihelpers/routeapihelpers.go, pkg/route/routeapihelpers/routeapihelpers_test.go
Router host name validation does not match between the apiserver validation and the route admission validation. Add the function to the library so it can be shared between the two processes.
Use a k8s apimachinery host name validation that reports the issue properly, as well as enforcing host name must have at least two labels (new), with each label less than 63 chars, and total length less than 253 chars. Trailing dots are allowed (new). The old behavior may be retained for customers who need it, by using a route annotation set to "true".
=> Bug 1896977: add library function for host name validation

pkg/config/serving/server.go
This should contribute to reducing traffic inside a cluster since not every metrics request to our operators (once every 30s per operator) will need to pass an authn/z check (tokenreview/SAR).
/assign @sttts 
/hold
contains fake bump
=> Bug 1887392: allow configuring authn/z caches TTLs

pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go
=> csi: add hooks in both Node and Controller Services

pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller.go, pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go, pkg/operator/csi/csidrivernodeservicecontroller/helpers.go, pkg/operator/v1helpers/helpers.go
This PR adds two new functionalities to the CSI pieces of library-go:
**csi: add configobserver to watch proxy info**
Cloud CSI drivers perform all sorts of operations using the cloud API.  However, that's not possible in network-restricted clusters, where requests need to go through a given proxy, unless they target the API server.
This patch adds a CSI Config Observer controller to observe the proxy resource and record the information in the operator CR. It also patches the CSI Controller Service Controller to read this information and pass it to the CSI containers that are part of the Deployment.
**csi: add hook that annotates deployment with secret's hash**
This is useful for when the secret changes. In this case we want the deployment to be re-deployed.
=> csi: add configobserver controller and hook helpers

pkg/config/serving/server.go
healthz and readyz have to accessible to unauthenticated so the kubelet can health check. Because of this, there is no reason to run an authz check on them.
system:masters has full power, so the authorization check is unnecessary and just uses an extra call.
=> optimize library-go to eliminate unnecessary SARs

pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller_test.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go, pkg/operator/csi/csidrivernodeservicecontroller/helpers_test.go, pkg/operator/v1helpers/test_helpers.go
This is a follow up PR to add tests to functionalities added in https://github.com/openshift/library-go/pull/976.
**csi: add unit tests for helper hook functions**
These functions were added in https://github.com/openshift/library-go/pull/976.
**csi: add unit tests for CSI Config Observer Controller**
This controller was added in https://github.com/openshift/library-go/pull/976.
**add fake UpdateOperatorSpec implementation**
This is necessary because the ConfigObserver controller updates the _spec_.
=> csi: add some unit tests to code added recently

pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller.go, pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go, pkg/operator/csi/csidrivernodeservicecontroller/helpers.go, pkg/operator/v1helpers/helpers.go
Originally this was a backport of https://github.com/openshift/library-go/pull/976.
However, that PR relied on functionality added by PRs https://github.com/openshift/library-go/pull/968 and https://github.com/openshift/library-go/pull/909, so those had to be backported as well.
=> Bug 1915467: cherry-pick hooks helpers and config observer

pkg/cloudprovider/external.go, pkg/cloudprovider/external_test.go
This will allow operators to determine whether or not they should be using internal or external cloud providers.
We want to be able to have this logic centrally so that we can restrict the feature gate usage only to platforms that have external provider support, without duplicating this logic in multiple locations.
Initially, only the openstack provider will be allowed to use this feature gate as for 4.8 that is the only planned external provider.
=> Add IsCloudProviderExternal helper for operators

pkg/assets/create/creater.go, pkg/client/openshiftrestmapper/hardcoded_restmapper.go
Because discovery for security.openshift.io is served by openshift-apiserver, which is unavailable from the bootstrap node and not present early in an installation flow.  This is a minimal change to pin the RESTMapping so the existing dynamic client flows know where to direct securitycontextconstraints without actual discovery data.
This mechanism is directly lifted from our kubernetes fork where we did this to resolve an ownerref problem.
=> Allow SCC to be created during bootstrapping

pkg/assets/create/create_test.go, pkg/assets/create/creater.go
cluster-bootstrap creates object that either fail on admission on recreate or in different ways than `AlreadyExists`. In resourceapply funcs we already follow that pattern, but in cluster-bootstrap using the assets package we did not.
=> Bug 1933263: pkg/assets: get resources before create to cope with pre-etcd-create errors

pkg/controller/factory/base_controller.go
Instead of 
`"OAuthRouteCheckEndpointAccessibleController" controller failed to sync "key", err: Get "https://oauth-openshift.apps.prod..com/healthz": EOF` 
produce error like:
`OAuthRouteCheckEndpointAccessibleController reconciliation failed: Get "https://oauth-openshift.apps.prod..com/healthz": EOF`
95% of all controller using factory just use string `"key"` as queue key and the controller word is always included in the controller name. This makes the message shorter and nicer to users (this message usually show up in logs and in some cases in degraded reason).
=> factory: produce nicer message when reconcile fail

pkg/config/client/transport.go
this PR adds a few convenience functions that I need in https://github.com/openshift/kubernetes/pull/603
=> convenience functions for client-go transport

pkg/healthmonitor/health_monitor.go, pkg/healthmonitor/health_monitor_test.go, pkg/healthmonitor/metrics.go, pkg/healthmonitor/metrics_test.go, pkg/healthmonitor/options.go, pkg/healthmonitor/target_resolver.go, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go, vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go, vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go, vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go, vendor/golang.org/x/xerrors/LICENSE, vendor/golang.org/x/xerrors/PATENTS, vendor/golang.org/x/xerrors/README, vendor/golang.org/x/xerrors/adaptor.go, vendor/golang.org/x/xerrors/codereview.cfg, vendor/golang.org/x/xerrors/doc.go, vendor/golang.org/x/xerrors/errors.go, vendor/golang.org/x/xerrors/fmt.go, vendor/golang.org/x/xerrors/format.go, vendor/golang.org/x/xerrors/frame.go, vendor/golang.org/x/xerrors/go.mod, vendor/golang.org/x/xerrors/internal/internal.go, vendor/golang.org/x/xerrors/wrap.go, vendor/modules.txt
This PR adds a health check monitor that periodically sends requests to the provided targets to check their health status.
Users can configure:
- `unhealthyProbesThreshold`: specifies consecutive failed health checks after which a target is considered unhealthy
- `healthyProbesThreshold`: specifies consecutive successful health checks after which a target is considered healthy
- `probeResponseTimeout`: specifies a time limit for requests made by the HTTP client for the health check
- `probeInterval`: specifies a time interval at which health checks are send
The HM also implements `Listener` and `Notifier` interfaces.
It automatically registers for notification if the target provided also implements the `Notifier` interface.
It is implicit so that the provider can provide a static or a …
=> introduces health check monitor

pkg/operator/apiserver/controller/workload/workload.go
Required for https://github.com/openshift/cluster-authentication-operator/pull/414
/assign @p0lyn0mial
=> workloadscontroller: don't prefix workloads name on empty prefix

pkg/image/referencemutator/pods.go
This API is not being used nor exposed and will be removed in kubernetes 1.21.
=> Drop batch/v2alpha1 which is not being used

pkg/operator/status/status_controller.go
I have verified and tested this with cluster-storage-operator and it does result in CO not being continuously updated with changing timestamp and event being emitted for each update.
=> Fix event and CO object being updated every 1s when CR is unmanaged

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controllers.go
// minReadySeconds is the time to wait between the completion of an operand becoming ready (all containers ready)
// and starting the rollout onto the next node.  This avoids a problem with an external load balancer that looks like
//  1. for some reason we have two instances, maybe a liveness check blipped on one node. it doesn't matter why
//  2. we bring down an instance on m0 to start a new revision
//  3. at this point we have one instance running on m1
//  4. m0 starts up and goes ready, but the LB ready check just timed out and is waiting for X seconds
//  5. we bring down an instance on m1 to start the new revision.
//  6. the LB thinks all backends are down and routes randomly
//  7. no profit.
// setting this field to 30s can prevent the kube-apiserver from triggering the above …
=>  add minreadyseconds concept to static pod operator

pkg/operator/encryption/crypto/rsa.go, pkg/operator/encryption/crypto/rsa_test.go
This functionality is common between ckao and kcmo and moving it to lib-go ensures that the maintenance can be shared.
/cc @stlaz @sttts @soltysh 
Canaries: 
- https://github.com/openshift/cluster-kube-apiserver-operator/pull/1072
- https://github.com/openshift/cluster-kube-controller-manager-operator/pull/512
=> Migrate rsa keypair validation and generation from ckao and ckcmo

pkg/operator/status/condition.go
We union conditions, but we forgot to sort the constituent conditions to have a stable message.  This causes lots of extra updates.
=> make the union conditions sort stable

pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
To make messages [like][1]:
```
level=error msg=Cluster operator kube-scheduler Degraded is True with InstallerPodContainerWaiting_ContainerCreating::NodeController_MasterNodesReady::StaticPods_Error: NodeControllerDegraded: The master nodes not ready...
level=error msg=InstallerPodContainerWaitingDegraded: Pod "installer-7-ci-op-kqngdf8m-b58e2-8x4c5-master-2" on node "ci-op-kqngdf8m-b58e2-8x4c5-master-2" container "installer" is waiting for 10m9.799978979s because ""
```
slightly more helpful when processing data like:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-azure-4.8/1374791880151142400/artifacts/e2e-azure/pods.json | jq -r '.items[] | select(.metadata.name == …
```
=> pkg/operator/staticpod/controller/installerstate: Include reason in InstallerPodContainerWaitingDegraded

pkg/controller/controllercmd/builder.go
`ControllerCommandConfig` knows the namespace where the operator runs, either from cmdline (`--namespace`) or autodetected from `/var/run/secrets`. Pass this namespace to the operator controller's `StarterFunc`, so the operator knows the namespace too (if it's interested).
This will help library-go based operators to create operands in the same namespace as the operator without passing the namespace as an env. variable.
=> Pass operator namespace to the controller

pkg/verify/verify.go
Use the expression from [go-digest][1], based on [image-spec][2].  We'd get more robust validation by using go-digest directly, but that would require a vendoring bump while bumping our regexp does not.
[1]: https://github.com/opencontainers/go-digest/blob/v1.0.0-rc1/digest.go#L62
[2]: https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md#digests
=> pkg/verify: Use a more-specific digest regular expression

pkg/operator/apiserver/audit/audit_policies.go, pkg/operator/apiserver/audit/audit_policies_test.go
Currently our cluster-kube-apiserver-operator does not use library go audit pkg and uses internal static files.
This is the addition of missing functions to library-go so that the package of library-go audit pkg will work.
Essentially, this fixes build errors.
=> add Default Audit Policy getter function

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
In pending and running phase the reason string was empty, leading to strange incomplete condition messages.
=> static-pods: always set installer reason string

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
Pods that are not terminated, but will never run, block the installer controller today. Typical case: `ContainerCreating` state.
=> static-pods: allow fast-forward to next revision with pending installer

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Fix the event noise during bootstrapping:
```
2021-01-03T08:52:51.343007736+00:00 stderr F I0103 08:52:51.342928       1 event.go:282] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-kube-apiserver-operator", Name:"kube-apiserver-operator", UID:"15fc618e-e332-4088-ac54-76811ef08fad", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'MissingVersion' no image found for operand pod
```
=> Bug 1917129: static-pods: no MissingVersion event as long as there are no known nodes yet

pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
We use kube-rbac-proxy to get https endpoint for metrics.
cc @bertinatto
=> Add ${KUBE_RBAC_PROXY_IMAGE} replacer to CSI driver controller

pkg/operator/revisioncontroller/revision_controller.go
we emit an event, but configmaps last long and this one tracks our status.
=> add revision reason to status configmaps

pkg/operator/staticpod/certsyncpod/certsync_controller.go
/assign @ihcsim 
This addresses the biggest burn budget offender.
=> bug 1953798: stop doing live gets for optional cert syncer files that don't exist on disk yet

pkg/operator/resource/resourcemerge/apiextensions.go
This is causing repeated updated for
I0429 17:11:16.270239       1 apiextensions.go:66] CustomResourceDefinition "apirequestcounts.apiserver.openshift.io" changes: {"spec":{"conversion":null}}
=> bug 1955226: update CRD apply to understand some fields are defaulted

test/library/apiserver/apiserver.go
Previously the maximum time was 15 minutes, now it is 22 minutes.
I'm increasing the timeout to fix failing tests on AWS platform.
There is a known issue on that platform with the NLB, it needs way more time to remove an unhealthy instance from the service.
That time has increased from 70 seconds to 210 seconds.
That means the time needed to wait for all instances has increased at least by 7 minutes.
xref: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1079
=> extends the maximum time the tests will wait for KAS to reach the same revision

test/library/encryption/e_log.go, test/library/encryption/helpers.go
In particular this PR:
- properly detects if the tests are running in CI so that we get output with timeouts. Previously the output didn't have timestamps which made troubleshooting harder.
- adds timestamps to logs to ease troubleshooting
- increases the timeout for migration to 79 minutes:
```
-  rolling out a single instance on AWS: 3m 30s (max delay aws) + 60s (in-flight req) + 3m 10s (starting new instance - observation) = 7m 40s
-  rolling out all instances: 7m 40s * 3 = 23m
-  a happy path scenario needs to roll out 3 revisions each taking 23m
-  plus 10 additional minutes for actual migration
```
xref: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1079
=> Bug 1943804: increases the maximum time for migration for the encryption tests on AWS

pkg/operator/csi/csicontrollerset/csi_controller_set.go
To manage VolumeSnapshotClass objects static resource controller should have a dynamic client[1].
This patch adds a new parameter called `dynamicClient` to `WithStaticResourcesController` function, that allows to specify
the client.
[1] https://github.com/openshift/library-go/pull/1067
=> CSI: allow to set dynamic client to static resource controller

pkg/image/imageutil/helpers.go, pkg/image/imageutil/helpers_test.go
The ResolveLatestTaggedImage utility method was intended for callers that needed to wait for an image import to succeed (trigger controllers and build controllers that need the image SHA). A number of use cases exist where import is not required, such as oc debug and must-gather where the qualified tag is sufficient. Since the existing utility method has confused callers about its limitations and intended use, create a new utility method intended for the three most common use cases:
1. You need to get the user's *current* desired intent (oc adm release new) and want to error out if the import has errors or isn't
complete
2. You need to get a pull spec but you don't care if it's out of date (oc debug / oc adm must-gather)
3. You need to get a pull spec and you must have imported the image …
=> Bug 1960758: New helper for oc adm must-gather / oc debug

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controllers.go
For unrevisioned resources (like dynamically loaded certs) we should not misuse a type for revisioned resources. This leads to confusion when reading the code.
Steps on bump:
1. replace `WithResources` with `WithRevisionedResources`
2. replace `WithCerts` with `WithUnrevisionedCerts` and change type of last arguments from `[]revision.RevisionResource` to `[]UnrevisionedResource` (same fields).
=> staticpod: remove misuse of RevisionResource type

pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go, pkg/operator/resource/resourceapply/generic.go, pkg/operator/resource/resourceapply/policy.go, pkg/operator/resource/resourceread/policy.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
This patch adds a function hook that detects the number of master nodes in the cluster (based on the `Deployment.Spec.NodeSelector` field) and sets the `Deployment.Spec.Replicas` field accordingly.
This will allow us to set the number of Deployment replicas based on the number of master nodes available. Also, we set anti-affinity rules and This is useful for mainly two things:
1. Prevent the operator going unavailable when draining nodes where the operand is running on.
2. Support the effort of avoiding Deployment rollouts getting stuck in single-node clusters (this also requires setting `maxSurge=0` in the Deployment strategy).
This PR also adds the possibility to create/update PDBs in the static resource controller. This will be required by CSI driver operators that will use the hook …
=> Bug 1947402: csi: add hook to set Deployment replicas according to numbe of master nodes

pkg/operator/csr/README.md, pkg/operator/csr/cert_controller.go, pkg/operator/csr/certificate.go, pkg/operator/csr/certificate_test.go, pkg/operator/csr/controller_test.go, pkg/operator/csr/csrtestinghelpers/assertion.go, pkg/operator/csr/csrtestinghelpers/testinghelpers.go, pkg/operator/csr/simple_clientcert_controller.go
This package provides a control loop which takes as input
1. target secret name
2. cert common name
3. desired validity (recall that the signing cert can sign for less)
The flow goes like this.
1. if secret contains a valid client cert good for at least five days or 50% of validity, do nothing.  If not...
2. create new cert/key pair in memory
3. create CSR in the API.
4. watch CSR in the API until it is approved or denied
5. if denied, write degraded status and return
6. if approved, update the secret
Thanks to the OCM team who built this in https://github.com/open-cluster-management/registration/tree/a2bb6439160edafaa94610883cd2f582485b5298/pkg/clientcert
remaining tweaks
=> add a simple client-cert controller for the single-cluster common case

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/installerpod/cmd.go
The target directory holds all files for the current static pod manifest.
As of today, kube-apiserver-certs is accessed by at least two processes, namely the installer pod and the cert-syncer.
Up until now, there was no coordination between these processes that might have lead to many unexpected errors, like https://bugzilla.redhat.com/show_bug.cgi?id=1963730
Moving the cert directory to the target directory (revisioned) ensures that these processes won't step each other's toes.
After this PR /etc/kubernetes/static-pod-resources/kube-apiserver-pod-REVISION/kube-apiserver-certs
Previously it was /etc/kubernetes/static-pod-resources/kube-apiserver-certs
=> Bug 1963730: moves the cert directory under the target directory

pkg/operator/apiserver/audit/bindata/bindata.go, pkg/operator/apiserver/audit/manifests/audit-policies-cm.yaml, pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
/assign @sttts
We no longer need to be treating the oauth tokens differently as they bear very little information that could be misused.
=> Bug 1879182: make secure- and normal audit policies match

go.mod, pkg/image/registryclient/client.go, pkg/image/registryclient/client_mirrored.go, pkg/image/registryclient/client_test.go, pkg/operator/staticpod/installerpod/copy.go, vendor/modules.txt
This is followup to https://github.com/openshift/library-go/pull/1084 fixing:
- setting `insecure` properly for `blobMirroredRepository`
- return proper error if no alternates found
- unit tests for the above two
- replace `golang.org/x/net/context` with built-in `context` package
=> image/registryclient: set insecure and return early in blobMirroredRepository

pkg/operator/staticpod/certsyncpod/certsync_controller.go, pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go, pkg/operator/staticpod/controllers.go, pkg/operator/staticpod/file_utils.go, pkg/operator/staticpod/installerpod/cmd.go, pkg/operator/staticpod/prune/cmd.go
As of today, the dynamic certificates i.e. `kube-apiserver-certs` are accessed by at least two processes, namely the installer pod and the cert-syncer.
Up until now, there was no coordination between these processes that might have lead to many unexpected errors, like https://bugzilla.redhat.com/show_bug.cgi?id=1963730
This PR writes all certificates in an atomic way by first creating a temporary file, writing the content to it, and then renaming it to the original file. 
`os.Rename` calls `syscall.Rename` which in turn uses the rename syscall (Linux) which provides atomicity (https://man7.org/linux/man-pages/man2/rename.2.html)
The previous attempt didn't work as it would break the DR scripts - https://github.com/openshift/library-go/pull/1098
=> Bug 1963730: writes the dynamic certs atomically

pkg/operator/staticresourcecontroller/static_resource_controller.go, pkg/operator/staticresourcecontroller/static_resource_controller_test.go
This PR adds method to get `RelatedObjects` from `StaticResourceController`
This PR required by https://github.com/openshift/cluster-storage-operator/pull/175
=> Bug 1961317: Adding static assets to related objects

pkg/operator/csi/csicontrollerset/csi_controller_set.go
Now there is some inconsistency between CSI controllers, some of which require the asset function to return an error and others to panic immediately. 
Due to the transition to embed module that provides only a function that returns an error[1], we need to unify our interfaces for the controllers.
This commit does this by requiring that all controllers now accept a function that returns an error. For controllers that should have panicked, we do an explicit check in the code.
[1] https://golang.org/pkg/embed/#FS.ReadFile
=> CSI: Unify assetFuncs for all controllers

pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go, pkg/operator/deploymentcontroller/deployment_controller.go, pkg/operator/deploymentcontroller/deployment_controller_test.go, pkg/operator/deploymentcontroller/helpers.go, pkg/operator/deploymentcontroller/helpers_test.go
The 2 commits in this PR are picked from #1095 to make sure that the storage team is not blocked on static pod guard controller for the PR.
=> Migrate csi deployment to use generic deployment

pkg/operator/apiserver/controller/apiservice/apigroup.go
previously a single failed request to the discovery endpoint of a service could make an operator report Availiable=false
to increase resiliency and avoid frequent changes in Availability we are going to send 5 requests in parallel and deemed a service as unavailable only when we didn't get at least 2 successful.
=> makes the apiservice controller more resilient to failures

pkg/operator/deploymentcontroller/deployment_controller.go
When applying hooks, make sure not to overwrite the original manifest. Some hooks may change the content later.
Example: a hook that replaces `${LOG_LEVEL}` with `operator.spec.logLevel`. As user modifies the `logLevel`, the controller + its hooks should replace `${LOG_LEVEL}` with the *current* value, not with the value that was *available on the first sync*.
=> DeploymentController: Do not overwrite manifest

pkg/operator/apiserver/controller/auditpolicy/auditpolicy_controller.go, pkg/operator/apiserver/controllerset/apiservercontrollerset.go
It watches the config.openshift.io/v1 APIServer object and reconciles a ConfigMap in the target namespace with the audit.k8s.io/v1 policy.yaml file.
=> apiserver: add audit policy controller

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
This method is used in KCMO and KAPIO to set the cloud-provider flags.
`FeatureGate` "ExternalCloudProvider" will short-circuit logic to "external" for supported platforms.
This PR is the main blocker for work on CCM integration in Openshift: https://issues.redhat.com/browse/OCPCLOUD-1070
=> [OCPCLOUD-1070] Add observe external switch to cloudpovider observer

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
Ensure each manifest contains the Kubernetes required fields apiVersion, kind, and metadata.name. Use those fields along with the optional field metadata.namespace to uniquely identify each manifest. Generate an error for any duplicate manifests, i.e. any with the same unique id.
Version is removed from apiVersion to produce Group which is what is actually used to form the above mentioned unique id. Some resources, e.g. ConfigMap, have an apiVersion with only a version identifier, e.g. `v1`. In these cases the Group is set to `""` as opposed to `v1`.
See [OTA-260](https://issues.redhat.com/browse/OTA-260).
=> OTA-260: add duplicate manifest error check

pkg/operator/encryption/controllers/condition_controller.go, pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/migration_controller.go, pkg/operator/encryption/controllers/prune_controller.go, pkg/operator/encryption/controllers/state_controller.go
It turns out that the new precondition checker added in 4.8 might prevent the encryption controllers from running and clearing the stale conditions.
This can happen especially on upgrades from 4.7 to 4.8.
This PR changes the encryption controllers to clear stale conditions when the preconditions are not fulfilled.
=> clear encryption conditions when there is no work to be done

pkg/config/leaderelection/leaderelection.go
found via https://github.com/openshift/origin/pull/26215
We want to handle 60s of communication disruption in all components.
=> update leader election defaults so it handles 60s of kube-apiserver communication disruption

pkg/controller/factory/base_controller.go, pkg/operator/configobserver/config_observer_controller.go, pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller.go, pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go, pkg/operator/deploymentcontroller/deployment_controller.go, pkg/operator/deploymentcontroller/deployment_controller_test.go, pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/loglevel/logging_controller.go, pkg/operator/management/management_state.go, pkg/operator/management/management_state_controller.go, pkg/operator/managementstatecontroller/management_state_controller.go, pkg/operator/managementstatecontroller/management_state_controller_test.go, pkg/operator/v1helpers/helpers.go, pkg/operator/v1helpers/interfaces.go, pkg/operator/v1helpers/test_helpers.go
This is minimal alternative of https://github.com/openshift/library-go/pull/1013. Only the controllers that are used by CSI driver operators are changed
Goal: Add support for removable operators managed by OLM, namely CSI drivers. Operands (a CSI driver) should be installed when user creates a CR and removed when user deletes it.
* Most library-go controllers log error / warning messages when the operator CR is missing. I updated only the controllers that are used in CSI driver operators to handle missing CRs and return silently.
* Reusing `management.SetOperatorNotRemovable()` to tell CSI controllers to support removing the operands.
* Removable operators may need to add/remove finalizers in the operator CR. I added a new interface `OperatorClientWithFinalizers` that can add/remove …
=> Add support for removable csi drivers

pkg/operator/resource/resourceapply/generic.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
https://issues.redhat.com/browse/AUTH-5
This Pull Request introduces CRD and Admission Registration types into the StaticResourceController
=> Updates for Cert Manager

pkg/operator/resource/resourceapply/generic.go
This PR adds missing schema.
Required for: https://github.com/openshift/cert-manager-operator/pull/17
=> Add missing schema for Admission Registration

pkg/operator/encryption/controllers/condition_controller.go
the condition controller is used to report the current state of the encryption: EncryptionCompleted, EncryptionInProgress or DecryptionCompleted
unfortunately, the previously set condition might have been cleared due to a bug in the controller every time the API server was deployed.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1982398
=> encryption condition controller doesn't reset previously set conditon

pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/cmd.go
This is needed to lower RBAC privileges (fetching pod definition) for controller that know the owner or want to set themselves as the owner.
=> make component owner reference customizable in controllercmd

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/cabundle_test.go, pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
When it takes 2 senior principal engineers to figure out what cert rotation does, we need better names and proper docs.
=> certrotation: doc and clean up naming

pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go, pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition_test.go
it is meant to be run on a SNO cluster.
it knows how to detect and report that a static pod was rolled back to a previous revision.
it sets/unsets StaticPodFallbackRevisionDegraded condition.
wiring in a follow-up PR.
xref: https://github.com/openshift/enhancements/pull/833
=> adds staticPodFallbackConditionController controller

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
We had a time.Sleep in the installer controller sync loop to delay progress such that load balancer have time to notice ready pods. This is awkward. There is the sync queue, just return and requeue after the given time.
=> staticpod/installer: get rid of sleep in sync loop

pkg/operator/staticpod/startupmonitor/assets/startup-monitor-pod.yaml, pkg/operator/staticpod/startupmonitor/cmd.go, pkg/operator/staticpod/startupmonitor/fallback.go, pkg/operator/staticpod/startupmonitor/fallback_test.go, pkg/operator/staticpod/startupmonitor/options.go
There must not be a different understanding what readiness mean between the operator and the startup-monitor. To avoid race, we move the readiness update of the nodeStatus to the startup-monitor.
=> staticpod/startupmonitor: update nodeStatus after readiness

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
The DeepEqual clause for updating the operator status returned from `Sync`, after `lastFailedCount` had been increased. On next `Sync` we ran directly into new state computation and installer pod creation. The delay much further down was never effective. This PR moved the installer backoff delay up.
=> staticpod/installer: fix backoff of installers

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
We need better, preferibly constant timestamp for `lastFailedTimestamp` to avoid hotlooping status updates. This PR exposes the timestamp from the pod status func such that it can be used for `lastFailedTeimstamp` in `nodeStatus`.
=> staticpod/installer: wire through installer timestamp

pkg/operator/staticpod/startupmonitor/cmd.go, pkg/operator/staticpod/startupmonitor/fallback.go, pkg/operator/staticpod/startupmonitor/fallback_test.go
the existing `fileExists` method checks only the target file and creating a symlink fails when it already exists
=> startup-monitor: always try to delete the symlink before creating it

pkg/operator/staticpod/startupmonitor/cmd_test.go, pkg/operator/staticpod/startupmonitor/monitor.go, pkg/operator/staticpod/startupmonitor/monitor_test.go
additionally, it doesn't fall back when the target revision doesn't match the expected one.
this usually means something bad happened, in that case, we should report an error (the startup controller will put an operator into a degraded state)
=> startup-monitor: releases the lock on each iteration to prevent fight with the installer

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/startupmonitor/fallback.go
This makes https://github.com/openshift/library-go/pull/1167 approximation of the failedLimit better.
=> staticpod/installer: do not wipe nodeStatus.lastFailed* when going ready

pkg/operator/staticpod/startupmonitor/cmd.go
unblock testing on a HA cluster.
=> startupmonitor: allows for passing the current node name to the readiness checker

pkg/operator/revisioncontroller/revision_controller.go, pkg/operator/revisioncontroller/revision_controller_test.go, pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go
The origin state machine was complicated, had races, spread over 3 controller, and can be – without loss of value – replaced with this approximation:
- prune everything before the last excluded revisions while excluded means:
- `failedLimit` many revisions before every targetRevision
- `max(failedLimit,succeededLimit)` many revisions before every lastAvailableRevisions
- `failedLimit` many revisions before every lastFailedRevisions
- `succeddedLimit` many revisions before every currentRevision
=> staticpod/prune: replace status state machine w/ n revs before current/target/failed/latest

pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
Adds a deployment hook that removes the master node selector from CSI controller deployments when deploying on a topology with external infrastructure.
=> Bug 1987025: CSI driver controller: modify nodeselector based on control plane topology

pkg/operator/revisioncontroller/revision_controller.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
Backport of https://github.com/openshift/library-go/pull/1150 and https://github.com/openshift/library-go/pull/1172.
=> Bug 1993800: staticpod/installer: fix backoff of installers

go.mod, pkg/operator/staticpod/startupmonitor/assets/startup-monitor-pod.yaml, pkg/operator/staticpod/startupmonitor/cmd.go, pkg/operator/staticpod/startupmonitor/pod_template.go, vendor/modules.txt
since kubelet doesn't respect the restart policy for static pods
we need to store the logs in a file for future troubleshooting
this PR introduces a new flag that allows specifying a log file.
the file will be rotated on a monthly basis and we will retain only the last 3 files.
=> startup-monitor: allows for logging to a log file in addition to stderr

pkg/operator/staticpod/controller/installer/installer_controller.go
In SNO kube-apiserver operator pog logs, saw many:
```
2021-09-03T02:22:58.369647152Z I0903 02:22:58.369501       1 event.go:282] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-kube-apiserver-operator", Name:"kube-apiserver-operator", UID:"2ed1e3f1-3ea4-407c-b072-b14daeb11140", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'InstallerPodFailed' Failed to create installer pod for revision 11 count %!d(string=xxia0902epic-gqg7k-master-0.c.openshift-qe.internal) on node '\x00': Get "https://172.30.0.1:443/api/v1/namespaces/openshift-kube-apiserver/pods/installer-11-xxia0902epic-gqg7k-master-0.c.openshift-qe.internal": dial tcp 172.30.0.1:443: connect: connection refused
```
Note: Failed to create installer pod for revision 11 count …
=> Correct argument order in 'Failed to create installer pod for revision'

pkg/operator/csi/OWNERS
This would avoid getting the Storage Team blocked.
=> csi: add fbertina and jsafrane as approves

pkg/operator/csi/csidrivernodeservicecontroller/helpers.go
This is required by Azure Disk and Azure File operators.
=> csi: add hook that annotates a DaemonSet with a secret's hash

pkg/operator/configobserver/etcd/observe_etcd_endpoints.go, pkg/operator/configobserver/etcd/observe_etcd_endpoints_test.go
As of today, the following blocks are reserved: 2001:db8::/32 and 192.0.2.0/24.
The usage of these IPs will be reported as a degraded condition (ConfigObservationDegraded)
Hopefully, this will make troubleshooting easier. In the past, it caused confusion as we didn't report any issues.
Note that we preserve backward compatibility since `kas-o` doesn't allow for usage of reserved IPs.
However, we still need to update `kas-o` because currently, it will silently drop reserved addresses
=> etcd observer: explicitly reports reserved address block as an error

pkg/client/openshiftrestmapper/hardcoded_restmapper.go
found on aws-ovn, 4.9 installation
1. bootstrap-kube-apiserver starts, readyz=false
2. cluster-bootstrap starts creating resources, but discovery does not return a full list
3. without a mapping for CRD, the rolebindingrestriction resource isn't created
4. without rolebindingrestrictions defined, the bootstrap-kube-apiserver poststarthook for initial rolebindings cannot create (blocked by admission)
5. the poststarthook fails, preventing initial rolebindings from being created causing a crashloop
6. additionally, permissions granted in our rendered artifacts are not added, this includes permissions for CSR creation for nodes
6. kubelets trying to join the cluster lack RBAC permissions for the initial CSR and anything before the kubelet client
7. pods trying to start may lack RBAC bound …
=> bug 2006945: extend hardcoded restmapper for cluster-bootstrap to avoid crashlooping bootstrap kube-apiserver

pkg/operator/staticpod/certsyncpod/certsync_controller.go
This is for a Bug 1977730. Cert were being given 600 here, but Kubernetes prefers 644.
https://kubernetes.io/docs/concepts/configuration/secret/#secret-files-permissions
=> Bug 1977730: change write storage chmod

pkg/cloudprovider/external.go, pkg/cloudprovider/external_test.go
Adds GCP and vSphere platforms handling to IsCloudProviderExternal function.
For 4.10 external providers enablement for such platforms would be gated by ExternalCloudProviderFeature feature gate.
This change will unblock further testing and development of CCMs.
=> Add GCP and vSphere platforms to IsCloudProviderExternal

pkg/cloudprovider/external.go, pkg/cloudprovider/external_test.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Adds support for PowerVS as an external cloud provider.
Related to nhancement: https://github.com/openshift/enhancements/pull/736
=> Add PowerVS to external CloudProvider

pkg/image/registryclient/client.go
Copied context is missing a CredentialsFactory (required by https://github.com/openshift/oc/pull/924)
=> fix registryclient Context.Copy

pkg/operator/staticpod/installerpod/cmd.go, pkg/operator/staticpod/installerpod/cmd_test.go
Ff the node is >=4.9, the pod UID does not need to be set in the file. Setting it to static UID might trigger a rare case where kubelet does not properly handle graceful shutdown and might lead to a case when regular pods go from "running" to "pending" state.
xref: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26572/pull-ci-openshift-origin-master-e2e-gcp-upgrade/1456620463206699008
=> installerpod: skip installer pod UID generation when running on newer kubelets

pkg/operator/apiserver/controllerset/apiservercontrollerset.go, pkg/operator/encryption/controllers.go, pkg/operator/encryption/controllers/key_controller_test.go, pkg/operator/encryption/controllers/migration_controller_test.go, pkg/operator/encryption/controllers/prune_controller_test.go, pkg/operator/encryption/controllers/state_controller_test.go, pkg/operator/encryption/deployer/revisionedpod.go, pkg/operator/resourcesynccontroller/interfaces.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/resourcesynccontroller/resourcesync_controller_test.go, test/e2e-encryption/encryption_test.go
Controllers behind optional features such as the encryption controller
which is disabled by default for all OpenShift apiservers, have no way
to synchronize secrets/configmaps conditionally. For instance, the
encryption controller tried to synchronize its encryption-config very
often even though encryption is disabled. To mitigate that, some
controllers have some logic to set the SyncResource source
conditionally. An empty source meaning that the sync controller will
skip syncing the object. Since this is very hacky, it would be best to
have preconditions that need to be fulfilled before synchronizing
resources.
To improve that, the ResourceSyncer interface was extended to
add SyncConfigMapCondtionally and SyncSecretConditionally
functions. This allows adding conditional syncs per …
=> Add conditional resource synchronization to the resource sync controller

pkg/operator/apiserver/controller/apiservice/apigroup.go
Fix panic seen in https://github.com/openshift/cluster-openshift-apiserver-operator/pull/483#issuecomment-970532608, after pulling the changes from https://github.com/openshift/library-go/pull/1142.
=> pkg: fix apiservice discovery context panic

pkg/operator/staticpod/prune/cmd.go
When a new master node is provisioned, there's no /etc/kubernetes/static-pod-resources/kube-scheduler-certs directory existing on the node yet. Given there's no sync between when a pruner pod and an installer pod gets to run, it may happen the pruner pod gets to run before the installer pod. In which case the certs directory is missing. Leading to a panic since the pruner expects the certs directory to exists. The directory gets eventually created but the panic is not user friendly.
=> bug 2026352: staticpod pruner: check if the cert directory exists

pkg/operator/resource/resourceapply/admissionregistration.go, pkg/operator/resource/resourceapply/admissionregistration_test.go, pkg/operator/resource/resourceapply/generic.go
Currently, whoever uses the `staticresourcecontroller` to roll out webhook configuration objects will get this test failure in CI:
```
[sig-arch] events should not repeat pathologically 
1 events happened too frequently  event happened 585 times, something is wrong: ns/openshift-cluster-csi-drivers deployment/vmware-vsphere-csi-driver-operator - reason/ValidatingWebhookConfigurationUpdated Updated ValidatingWebhookConfiguration.admissionregistration.k8s.io/validation.csi.vsphere.vmware.com because it changed
```
I see 2 ways of fixing this:
1. Special-case negative values for the expected generation, so that [this](https://github.com/openshift/library-go/blob/c58f31ee6d3a5b97360175fa073a7eec6ccd1b79/pkg/operator/resource/resourceapply/generic.go#L215) won't constantly update the object. …
=> resourceapply: don't require generation for applying *WebhookConfiguration resources

pkg/operator/staticpod/installerpod/cmd.go, pkg/operator/staticpod/installerpod/cmd_test.go
found in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-e2e-aws-serial/1466323246101041152
The kube-scheduler operand pod doesn't appear to be getting updated.  This is only one of a few different problems in the kube-scheduler-operator.
=> tighten static pod UID until v1.23 to account for kubelet bug fix

pkg/config/clusterstatus/clusterstatus.go, pkg/config/leaderelection/leaderelection.go, pkg/config/leaderelection/leaderelection_test.go, pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/builder_test.go
Leader election in SNO clusters have limited resources where requests can put un-needed pressure on the `kube-apiserver`. This PR increases the retry period and lease duration on leader election and exposes some helper functions to determine topology and SNO leader election defaults, on operator start up.
=> Feat: sno leader election config

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go, pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go, pkg/operator/resource/resourceapply/generic.go, pkg/operator/resource/resourceapply/generic_test.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
If we see that neither the manifest being applied (by caching a hash of the manifest),
or the existing resource in the cluster (by caching the resourceVersion) has
changed since the manifest was last updated, applying the resource can be
skipped, since it won't actually do anything.
=> Improve performance by caching src/dest when applying resource manifests

Makefile, pkg/operator/staticpod/controller/guard/bindata/bindata.go, pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go, pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml, pkg/operator/staticpod/controller/guard/manifests/pdb.yaml, pkg/operator/staticpod/controllers.go
Deploy guarding pods with a PDB which will make sure a node does not drain a node until at most one replica of an operand is unavailable. Each guarding pod checks healthz status of an operand on the same node.
The guard controller repeatedly checks available master nodes and for each one renders an unmanaged guard pod. Each guard pod is responsible for checking if corresponding operand (operand pod running on the same node as the guard pod) is ready (through checking the `/healthz` endpoint). The guard uses an https probe to check readiness of its operand. At the same time a pdb with minAvailable set to `len(masters)-1` is rendered. Each time the number of master nodes changes, the `minAvailable` field is updated accordingly. 
Outstanding facts:
- guard pod has its nodename set directly …
=> Guard controller

pkg/operator/resource/resourceapply/core.go
This is to fix TestEnsureNodeKubeconfigs in cluster-kube-apiserver's unit tests (I'm not sure if the test being broken is actually important or not, but we can re-address that later)
=> Ensure that `required` is always fixed up by ApplySecret

pkg/operator/resource/resourceapply/resource_cache.go
ApplSecret is a caching client so sometimes will return a nil from a GET, which causes
the embedded ObjectMeta to be nil.
=> Add nil checks to resource cache

pkg/crypto/missing_san.go, pkg/crypto/missing_san_test.go, pkg/transport/missing_san_roundtripper.go, pkg/transport/missing_san_roundtripper_test.go
This introduces helper methods to verify invalid certificates
having missing SAN fields.
Additionally, this introduces a roundtripper decorator
which increases a metric if invalid certificates without a SAN field
are detected
See https://github.com/openshift/enhancements/pull/980
Note: this functionality is against 4.9 only as this is the last release having tolerant behavior against missing SAN certs.
/cc @stlaz
=> Bug 2037274: [crypto,transport]/missing_san: verify invalid certificates

pkg/security/OWNERS, pkg/security/ldapclient/client.go
This adds the possibility to add connection verification in the ldap client configuration.
See https://github.com/openshift/enhancements/pull/980 for context.
=> Bug 2037274: pkg/security/ldapclient: add configuration for connection verification

pkg/security/OWNERS
This updates the auth team to be owners of the security package which mostly includes ldap helpers.
/cc @sttts
=> pkg/security/OWNERS: add auth team

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go, pkg/operator/staticpod/controllers.go
Not every controller consumes operand pod label selector when the StartMonitor is enabled.
Also, the operand pod label selector is now required by the guard
controller since not every operator has the static pod name
equal to the app label. E.g.
| operand | label | static pod name |
| ------- | ----- | --------------- |
| kube-scheduler | app=openshift-kube-scheduler | openshift-kube-scheduler |
| kube-controller-manager | app=kube-controller-manager | kube-controller-manager |
| kube-apiserver | app=openshift-kube-apiserver | kube-apiserver |
In case of KS and KCM both app label and the static pod name are equal.
Whereas in the case of KA, the app label differs from the static pod
name. Thus, it is more practical to provide the operand pod label selector rather than rely on a specific …
=> bug 2005901: staticpod builder: initialize operand label selector separately

pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivernodeservicecontroller/helpers.go, pkg/operator/v1helpers/helpers.go
This is a backport of https://github.com/openshift/library-go/pull/1271.
We need to backport that fix to all supported versions.
=> [release-4.9] Bug 2029571: csi: add hook to inject custom CA bundle

test/library/metrics/query.go
This is required to clean up origin test prometheus usage.
=> rely on client interfaces for prometheus client

pkg/operator/metricscontroller/legacy_cn_certs_sync.go, pkg/operator/metricscontroller/legacy_cn_certs_sync_test.go
This fixes an empty vector result which can happy during early bootstrap phases, recognized during proof PR https://github.com/openshift/cluster-kube-apiserver-operator/pull/1274.
/cc @stlaz
=> Bug 2031839: metricscontroller: handle empty vector query result

pkg/config/leaderelection/leaderelection.go, pkg/controller/controllercmd/builder.go
See https://github.com/kubernetes/kubernetes/issues/107454 for details on how to migrate to "leases" leader election.
=> Bug 2037856: use 'configmapsleases' based leader election

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go, pkg/operator/staticpod/controllers.go
The guard controller is missing the code that creates a PDB. Also, do not render the guard pod if its underlying node is not schedulable (tainted with `NoSchedule:node.kubernetes.io/unschedulable`).
=> bug 2005901: guard controller: create the pdb if it does not exist

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go, pkg/operator/staticpod/controllers.go
in particular:
run the monitor controllers only when explicitly requested
allow the monitor and the guard controllers to report required parameters
=> staticpodcontroller: refactor ToControllers() method to be less error prone

pkg/image/registryclient/client.go, pkg/image/registryclient/client_mirrored.go, pkg/image/registryclient/client_test.go
The registry client incorrectly parsed the repository name as a full image
reference, and because of this, it could interpret a namespace with a
dot as a host name and eventually loose it.
=> Bug 2049234: Fix handling namespaces with dots in registry client

pkg/operator/staticpod/installerpod/cmd.go, pkg/operator/staticpod/internal/utils.go, pkg/operator/staticpod/internal/utils_test.go
Refactor some of the code used by staticpod controllers to make it reusable by all the controllers as per https://github.com/openshift/library-go/pull/1316#discussion_r805877420.
=> Add package shared between all staticpod controllers

pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go, pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller_test.go, pkg/operator/staticpod/controllers.go
Effort based on https://github.com/openshift/cluster-kube-apiserver-operator/pull/1317 and including the following gists written by @p0lyn0mial to address a comment regarding the termination grace period:
- https://gist.github.com/p0lyn0mial/363f5f1c04c1ff6b607d8358a123dc53
- https://gist.github.com/p0lyn0mial/abd14f30fe1f83b849e5f7f9f9811275
=> Bug 2053582: Track static pod lifecycle

pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go
will help us to get rid of all false-positive cases we are currently seeing, in the majority of cases we are behind by 10 seconds.
=> MissingStaticPodController: increases the delay time needed for a static pod to be reported to 150 seconds

pkg/operator/apiserver/controller/workload/workload.go, pkg/operator/apiserver/controller/workload/workload_test.go
The workload controller throws panics if the sync Delegate returns
(not-ready, nil error) because the error returned is put into a slice
without checking its nil value. A generic processing of the slice
then tries to call Error() on the nil.
------
as observed in https://github.com/openshift/cluster-authentication-operator/pull/532
/assign @p0lyn0mial 
/cc @s-urbaniak
=> workload controller: fix nil panic on precondition not ready w/o an error

pkg/operator/resource/resourceapply/storage.go, pkg/operator/resource/resourceapply/storage_test.go
`CSIDriver.Spec` is immutable after creation. Some of its fields should not be changed, for example changing `attachRequired` from `true` to `false` when a volume is being attached may result in orphaned VolumeAttachment objects.
But most of its fields can be changed without any issues. We need to change `fsGroupPolicy` from default (empty) to `File` in all CSI drivers that are based on a block file to prevent fsGroup issues like https://bugzilla.redhat.com/show_bug.cgi?id=2058626.
Also, remove support for CSIDriver v1beta1, nobody uses it by now.
=> Recreate CSIDriver on change

pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml, pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml, pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml, pkg/operator/apiserver/audit/testdata/multipleCr.yaml, pkg/operator/apiserver/audit/testdata/oauth.yaml, pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
=> Bugzilla 2063342: audit/manifests: exclude tokenreviews and tokenrequests from audit logs

pkg/client/openshiftrestmapper/hardcoded_restmapper.go
It allows properly run jobs when kub-apiserver cannot
reach aggregated APIs. It is related to bz2048801 and bz2054338.
=> Extend rest mappings with job definition

pkg/operator/resource/resourceapply/core.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go
This PR reduces the amount of requests made by the `resourcesynccontroller` when a target ConfigMap doesn't exist.
1. To avoid unnecessary GET requests, we use cached clients in `resourcesynccontroller`.
2. To avoid unnecessary DELETE requests, we first verify if the target exists in `SyncPartialConfigMap`.
Before this patch, on a fresh-installed cluster, without user workloads, we can see that the amount of requests keep growing:
```
$ oc dev_tool audit -f must-gather.local.6142475801866269614/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-de53ed4750def9ed611ca460c780cc78eece525162747213cfdbb4c26687460c/audit_logs/kube-apiserver/ -otop --by=verb --user="system:serviceaccount:openshift-cluster-csi-drivers:aws-ebs-csi-driver-operator"  --resource="configmaps" --failed-only
had 5547 …
```
=> Bug 2049671: resourcesynccontroller: avoid requests to non-existent target

pkg/operator/onepodpernodeccontroller/onepodpernode_controller.go, pkg/operator/onepodpernodeccontroller/onepodpernode_controller_test.go
This will mitigate the platform impact of the scheduler problems.
=> add operator controller that can eliminate co-scheduled pods that should be separate

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
Moving include() method from CVO
as the code will be reused in OC CLI and CVO. The include() method currently exists in https://github.com/openshift/cluster-version-operator/blob/master/pkg/payload/payload.go#L221 and will be replaced by the code from library-go in future.
=> Adding method from cvo for capabilities

pkg/controller/factory/controller_context.go, pkg/controller/factory/controller_context_test.go, pkg/controller/factory/factory.go
Allow enqueuing multiple or no keys while handling an object in an eventHandler. Useful when handling multiple types of objects in a single controller and object of one type needs to be expanded in multiple keys representing the object of the default handled type.
/cc @s-urbaniak 
/cc @sttts 
=> controller factory: allow enqueuing multiple objects in eventHandler

pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go, pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller_test.go
Adding a storage class controller. This controller should be used by CSI driver operators and as a result provide users the possibility of changing their default storage class.
In short the controller can take a storage class asset file which has default StorageClass annotation set to true - this indicates we want to create this specific storage class as default, but only if:
1) there are no other storage classes defined as default
2) there is no storage class with matching name (if there is just copy its annotation)
All other cases should result in applying non-default storage class regardless of the annotation set in asset.
Here is an example of the storage class asset I used for testing:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: gp2-csi
annotations: …
```
=> add storage class controller

pkg/verify/verify.go, pkg/verify/verify_test.go
Sometimes we fail to verify because we find signatures we don't trust.  Sometimes we fail to find signatures at all, either because the backing stores have no signatures, or because we fail to contact the backing stores.  With this commit, we pass all that useful debugging context on to the caller.  Not in the string, because we don't want to overwhelm all callers, but they can get it via [`Unwrap`][1] so they can show the details where they have space to do so.
[1]: https://pkg.go.dev/errors#Unwrap
=> Bug 2071998: pkg/verify: Expose underlying signature errors

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
Add a case statement for Nutanix so the warning does not get issued
for OCP clusters on Nutanix platform.
=> Suppress 'No Recognised Cloud Provider' warning for Nutanix

pkg/operator/resource/resourceapply/storage.go, pkg/operator/resource/resourceapply/storage_test.go
Backporting https://github.com/openshift/library-go/pull/1348 to 4.10.
Some StorageClass fields are immutable after creation, therefore we need to delete and re-create the StorageClass if an operator needs to change these fields.
In 4.10 we need to fix StorageClass for Alibaba CSI driver.
=> 4.10: Re-create StorageClass to change immutable parameters

test/library/apiserver/apiserver.go, test/library/library.go, test/library/pod_same_revision.go, test/library/pod_same_revision_test.go
so that it:
- accepts an object that implements `LoggingT` interface for logging purposes. That allows for using this method from ginkgo and the standard library's testing framework.
- returns an error, that allows the caller of this method to make a decision on how to log the error or/and end the test.
=> updates signature of WaitForAPIServerToStabilizeOnTheSameRevision function

pkg/operator/staticpod/controller/common/helpers.go, pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go
the function will be used by multiple controllers. This PR also renames the function to `NewIsSingleNodePlatformFn`
instructions on update:
import `staticcontrollercommon "github.com/openshift/library-go/pkg/operator/staticpod/controller/common"`
use `staticcontrollercommon.NewIsSingleNodePlatformFn`
will be used by https://github.com/openshift/library-go/pull/1347
=> moves `IsSNOCheckFnc` to a common place

pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go, pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller_test.go, pkg/operator/staticpod/controllers.go
Make threshold timeout for missing static pods take different values depending on the deployment type: multi node or single node.
Some SNO tests fail by a small margin of seconds because of the timeout being ok for multi node and short for single node. Extending 30s to mitigate these errors.
=> Bug 2064024: Increase timeout for missing static pods

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go
When an operator needs to update `service.spec`, `ApplyService` should apply it. We detect change of the spec by using an annotation with the old `service.spec` required by the operator and comparing it with the current operator's request.
Keep the existing heuristics of user changes (`spec.type`, `spec.selector`) in place.
This code expects that the API server restores any immutable ``service.spec` fields, like `clusterIP`. My observation is that the API server restores them when processing the update.
This is related to https://bugzilla.redhat.com/show_bug.cgi?id=2076637 - we want to add new `service.spec.ports` to an existing service during cluster update.
cc @deads2k @openshift/storage
=> Fix ApplyService to detect new Service spec

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
so a resource is filtered out if any of the capabilities are disabled.
=> Bug 2084331: pkg/manifest/manifest.go: Fix checkResourceEnablement

pkg/verify/configmap_test.go, pkg/verify/store/configmap/configmap.go, pkg/verify/store/memory/memory.go, pkg/verify/store/parallel/parallel.go, pkg/verify/store/parallel/parallel_test.go, pkg/verify/store/serial/serial.go, pkg/verify/store/serial/serial_test.go, pkg/verify/store/sigstore/sigstore.go, pkg/verify/store/sigstore/sigstore_test.go, pkg/verify/store/store.go, pkg/verify/verify.go
Extending #1358 with more details and a test-case that confirms we will get timestamps and URIs when a HTTP request times out or is canceled.  Bunch of fiddly pivots here, so it's a number of small commits.  See the individual commit messages for a description of why I'm making the pivot that I'm making in that commit.
=> Bug 2071998: pkg/verify: Expose store error details, especially slow access

pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go, pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller_test.go
An operator now has possibility to modify a StorageClass before it's applied by the SC controller.
Alibaba CSI driver operator will use it to dynamically inject `ResourceGroupID` to the default SC to provision PVs in the same resource group as where are all the other cluster resources like VMs and their root disks.
=> Bug 2096691: Add custom hooks to CSIStorageClassController

pkg/operator/apiserver/controller/workload/workload.go, pkg/operator/apiserver/controller/workload/workload_test.go
An operator that is `progressing=true` for a long time should stay in progressing state (on top of getting `degraded=true`).
```
Progressing Timeline in Minutes
[--------|--------]
0   ^   15   ^  45  ^
A         B        C
A is progressing=true, degraded=false
B is progressing=false, degraded=false
C is progressing=false, degraded=true (inertia logic set to 30 minutes for CAO)
```
[Request Header IDP Flaky Test](https://bugzilla.redhat.com/show_bug.cgi?id=2065028)
[30 minutes](https://github.com/openshift/library-go/blob/master/pkg/operator/apiserver/controllerset/apiservercontrollerset.go#L160-L165=)
Signed-off-by: Krzysztof Ostrowski <kostrows@redhat.com>
=> BZ_2065028: remove P=f on degrading operator

pkg/cloudprovider/external.go, pkg/cloudprovider/external_test.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
The OpenStack team want to enable the OpenStack CCM on all clusters from 4.12 onwards. This changes the decision logic of the `IsCloudProviderExternal` function so that no matter the scenario, the OpenStack CCM will be external.
This will need to be paired with PRs to update KCMO, CCCMO, MCO and KASO.
The KCMO and CCCMO PRs are time sensitive and must be merged simultaneously.
The other two PRs can be merged later without any ill effect to the CI or new installs/debug builds for developers.
I used cluster bot to test this with the respective CCCMO and KCMO PRs, with two results:
* [First attempt - failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-openstack/1551878461327413248)
* [Second attempt - …
=> Always enable external cloud provider on OpenStack

pkg/operator/resource/resourceapply/generic.go, pkg/operator/resource/resourceapply/generic_test.go, pkg/operator/resource/resourceread/generic.go, pkg/operator/resource/resourceread/generic_test.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
And change `ApplyDirectly` + `StaticResourceController` to use it.
This allows `StaticResourceController.RelatedObjects()` to process unknown
types as Unstructured, like `PrometheusRules`.
=> Bug 2108054: Add ReadGenericWithUnstructured

pkg/operator/staticresourcecontroller/static_resource_controller.go
Use services informer instead of namespaces when the controller is about to apply a Service.
=> Fix Services informer in StaticResourceController

go.mod, pkg/security/ldapclient/client.go, pkg/security/ldapclient/client_test.go, vendor/golang.org/x/net/internal/socks/client.go, vendor/golang.org/x/net/internal/socks/socks.go, vendor/golang.org/x/net/proxy/dial.go, vendor/golang.org/x/net/proxy/direct.go, vendor/golang.org/x/net/proxy/per_host.go, vendor/golang.org/x/net/proxy/proxy.go, vendor/golang.org/x/net/proxy/socks5.go, vendor/modules.txt
This change adds downstream ldapDial and ldapDialTLS funcs that are
identical to ldap.Dial{,tls} except that they use a proxy dialer that
respects the ALL_PROXY environment variable to use a socks5 proxy from
there if set.
This is needed for Hypershift, where the oauth server runs in the
management cluster but the ldap server is only accessible from the guest
VPC. In that situation, the traffic from the oauth server needs to be
routed through a proxy into konnektivity which then routes it onto an
agent that runs on workers in the guest vpc and from there it can reach
its final destination.
/assign @stlaz 
Ref https://issues.redhat.com/browse/HOSTEDCP-421
=> Ldap: Respect ALL_PROXY when dialing

pkg/crypto/crypto.go, pkg/crypto/crypto_test.go
The EnsureSubCA function would fail if the serial.txt file did not exist before it's called.
This PR fixes the above, adds unit tests for the Ensure* functions, and removes the deprecated ioutil module use from the crypto package.
=> crypto: fix the EnsureSubCA function failing to read the serial.txt file

pkg/config/serving/server.go
This was generating log entries like:
```
I0615 21:46:44.754123       1 server.go:50] Error initializing delegating authentication (will retry): <nil>
I0615 21:46:45.757131       1 server.go:50] Error initializing delegating authentication (will retry): <nil>
I0615 21:46:46.757610       1 server.go:50] Error initializing delegating authentication (will retry): <nil>
I0615 21:46:47.757257       1 server.go:50] Error initializing delegating authentication (will retry): <nil>
I0615 21:46:48.757348       1 server.go:50] Error initializing delegating authentication (will retry): <nil>
I0615 21:46:49.757570       1 server.go:50] Error initializing delegating authentication (will retry): <nil>
I0615 21:46:50.763997       1 server.go:50] Error initializing delegating authentication (will retry): …
```
=> Bug 2101520: Log right error when initializing delegating authentication

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
during capabilities filtering. When set to true a manifest will not be excluded simply because it contains an unknown capability. This is necessary to allow updates to an OCP version containing newly defined capabilities.
=> OCPBUGS-2125: pkg/manifest/manifest.go: add option to allow unknown capabilities

pkg/template/templateprocessingclient/dynamic_process.go
object namespaces are now validated befoer admission, whereas
before, they were simply ignored and overritten to match the
request namespace during persistence. Fixed so the correct namespace
is used when making requests.
=> Make request using correct namespace

pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
This controller can be used to conditionally to deploy resources that depend on a runtime check. With this we can check if the a `VolumeSnapshotClass` CRD exists before deploying the CR.
While at it, fix the `StaticResourceController.Name()` method to return the controller name that was provided by the user. With this patch log entries will show the correct controller name.
=> OCPBUGS-1904: add new ConditionalStaticResourcesController

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
during capabilities filtering. When set to true a manifest will not be excluded simply because it contains an unknown capability. This is necessary to allow updates to an OCP version containing newly defined capabilities.
=> OCPBUGS-2293: pkg/manifest/manifest.go: add option to allow unknown capabilities

pkg/operator/staticpod/installerpod/cmd.go
Researching https://issues.redhat.com/browse/TRT-589 shows installer pod failures.  Belief is that we are taking 1 minute to timeout trying to fetch secrets.  The expectation is an individual secret should be fetched in under a second so the connection is likely getting hung up.  This PR lowers the timeout to 14 seconds so we can make use of the retry attempts with the expectation if we are hung and timeout after 14 seconds we should have multiple retry attempts to connect and pull the secret.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/1795/pull-ci-openshift-cluster-monitoring-operator-master-e2e-agnostic/1579855936237867008
shows
`Oct 11 16:54:58.794 - 2102s W alert/KubePodNotReady ns/openshift-kube-scheduler …
=> lower timeout to increase retries

pkg/route/hostassignment/assignment.go, pkg/route/hostassignment/assignment_test.go, pkg/route/hostassignment/plugin.go, pkg/route/hostassignment/plugin_test.go, pkg/route/validation/validation.go, pkg/route/validation/validation_test.go
This is an almost-direct copy of the route validation and hostname assignment logic from openshift-apiserver, which has been refactored to operate on the v1 types from openshift/api instead of the internal types from openshift/openshift-apiserver. From library-go, one implementation will be sharable between openshift-apiserver and kube-apiserver to support OpenShift variants that serve the route API via CRD.
=> Copy route validation and defaulting bits from openshift-apiserver.

pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
https://issues.redhat.com/browse/OCPBUGS-2083
Setting this to the same list that was used in Manila:
https://github.com/openshift/csi-driver-manila-operator/pull/145
I don't want to have this string copied in 20 different repos though, it seems better to set a default once in library-go and add a placeholder to the manifests where we want to use it.
=> OCPBUGS-2083: set default list of TLS ciphers for Kube RBAC sidecars

pkg/operator/staticpod/controller/installerstate/installer_state_controller.go, pkg/operator/staticpod/controller/installerstate/installer_state_controller_test.go
In case all the latest revision installer pods are running and an older revision installer pod is in Pending state (e.g. the container runtime unable to delete the pod), do not change the InstallerPodContainerWaitingDegraded condition to True.
Based on https://github.com/openshift/library-go/pull/1230 (just rebased master into here - and changed how maps were being declared/assigned)
I think this is already an acceptable solution. Please let me know if a different approach would be better.
Bugs:
https://bugzilla.redhat.com/show_bug.cgi?id=2009646
https://bugzilla.redhat.com/show_bug.cgi?id=1986385
=> Installer static controller: be more forgiving and consider only recent installer pods

pkg/template/templateprocessingclient/dynamic_process.go
Reverts openshift/library-go#1402
This change seems to break several template tests. https://github.com/openshift/origin/pull/27548 is pulling in new change and gcp-ovn and aws-ovn-fips fail on
> [sig-devex][Feature:Templates] template-api TestTemplate [apigroup:template.openshift.io] [Suite:openshift/conformance/parallel]
> [sig-devex][Feature:Templates] template-api TestTemplateTransformationFromConfig [apigroup:template.openshift.io] [Suite:openshift/conformance/parallel]
https://github.com/openshift/origin/pull/27565 is bringing in kube bump but with openshift/library-go#1402 reverted - tests pass
=> Revert "Make request using correct namespace"

pkg/crypto/crypto.go, pkg/crypto/crypto_test.go
MicroShift uses this library to generate certificates, including the kubelet
certificates.
The subject part of the certificate is used to authenticate the kubelet and
limit the permissions on what can access. On a host name, the client
certificate was not being regenerated, so the kubelet could not create a
new entry for the new hostname, and blocked on a loop.
This commit forces the regeneration of the client certificate when the
subject field on the disk file differs.
https://issues.redhat.com/browse/USHIFT-573
=> USHIFT-573 Regenerate client certificate on subject change

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go
To avoid:
```
Oct 28 23:58:55.693391 ci-op-3hj6pnwf-4f6ab-lv57z-master-1 kubenswrapper[1657]: E1028 23:58:55.693346    1657 kubelet_pods.go:413] "Hostname for pod was too long, truncated it" podName="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-master-1" hostnameMaxLen=63 truncatedHostname="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-maste"
Oct 28 23:59:03.735726 ci-op-3hj6pnwf-4f6ab-lv57z-master-0 kubenswrapper[1670]: E1028 23:59:03.735671    1670 kubelet_pods.go:413] "Hostname for pod was too long, truncated it" podName="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-master-0" hostnameMaxLen=63 truncatedHostname="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-maste"
Oct 28 23:59:11.168082 ci-op-3hj6pnwf-4f6ab-lv57z-master-2 …
```
=> OCPBUGS-3041: guard controller: set an explicit hostname to avoid name collisions

pkg/cloudprovider/external.go, pkg/cloudprovider/external_test.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Add Nutanix as an external cloud provider platform, in order to integrate the nutanix-ccm to openshift.
=> Add Nutanix as an external cloud provider platform

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go
Backporting this one https://github.com/openshift/library-go/pull/1427
=> [release-4.12]  OCPBUGS-4478: guard controller: set an explicit hostname to avoid name collisions

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
The in-tree openstack provider is gone from kube 1.26.
=> Drop support for OpenStack in-tree plugin

pkg/route/routeapihelpers/routeapihelpers.go, pkg/route/routeapihelpers/routeapihelpers_test.go
ValidateHost checks that a route's host name satisfies OpenShift DNS requirements,
with the assumption that the caller is not passing in an empty host name.
ValidateHost mimics the host validation in the validateRoute method in the
[openshift-apiserver/pkg/route/apis/route/validation/validation package.](https://github.com/openshift/openshift-apiserver/blob/db22c038b9184b4ae823bba3f57b669526999a2b/pkg/route/apis/route/validation/validation.go#L58-L72)
The host name length must be no more than 253 characters.  The only characters
allowed in host name are alphanumeric characters, '-' or '.', and it must start
and end with an alphanumeric character. A trailing dot is NOT allowed.
If the allowNonCompliant annotation is not set to true, the host name must in
addition consist of one or more …
=> Bug: 2039256 Validate a hostname the same as openshift-apiserver

pkg/operator/apiserver/audit/bindata/bindata.go, pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml, pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml, pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml, pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml, pkg/operator/apiserver/audit/testdata/multipleCr.yaml, pkg/operator/apiserver/audit/testdata/oauth.yaml, pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
cherry-pick of https://github.com/openshift/library-go/pull/1394 (manually done)
=> [release-4.10] OCPBUGS-5345: routes/status resources can leak sensitive data

pkg/cloudprovider/external.go, pkg/cloudprovider/external_test.go
This PR migrates the vSphere cloud provider from in-tree to out-of-tree. It must be merged in tandem with the PR for KCMO and CCMO to avoid a build that contains one or the other operator PRs without the other. If either merges without the other, it will either lead to no cloud controllers or duplicate cloud controllers, either of which will not work well.
* [KCMO PR](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/687)
* [CCMO PR](https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/214)
* [Cluster Bot demonstration of above PRs](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-vsphere-modern/1612407690103885824)
* [Updating origin external CCM …
=> [OCPCLOUD-1818] Migrate vSphere to out of tree cloudprovider

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go
Backporting https://github.com/openshift/library-go/pull/1427
=> OCPBUGS-4551: [release-4.11] guard controller: set an explicit hostname to avoid name collisions

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go, pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml, pkg/operator/staticpod/controllers.go
KS and KCM does not publish /readyz endpoint, only /healthz. On the other hand KA publishes both /healthz and /readyz. The /readyz endpoint is more suitable for checking the readiness.
Thus, the guard controller needs to be allow to explicitly set the readiness probe endpoint.
/hold
=> WRKLDS-649: Guard controller: set the readiness probe endpoint explicitly

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go
Backporting https://github.com/openshift/library-go/pull/1427
=> [release-4.10] OCPBUGS-4552: guard controller: set an explicit hostname to avoid name collisions

OWNERS_ALIASES
Catching up with openshift/cluster-version-operator@f921431cca (openshift/cluster-version-operator#891).
=> OWNERS_ALIASES: Update approvers: add David, remove Jack, and earlier

pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/key_controller_test.go, pkg/operator/encryption/crypto/keys.go, pkg/operator/encryption/encryptionconfig/config.go, pkg/operator/encryption/encryptionconfig/config_test.go, pkg/operator/encryption/secrets/secrets.go, pkg/operator/encryption/secrets/secrets_test.go, pkg/operator/encryption/state/types.go, pkg/operator/encryption/testing/helpers.go
proof PR: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1446
=> API-1509: Enable aes-gcm encryption provider

test/library/encryption/helpers.go
This reverts commit 38724ca8e236fbd938f9c0b737b35c9d6f5091f6, reversing changes made to 4db74c34da22999cca8b30bbd5b52d0f408af731.
This patch was actually incorrect and introduced a bug in the test:
> Mar  2 16:23:34.132: ERROR: Wrong number of migrated resources for "encryption-key-openshift-kube-apiserver-1" key, expected 2, got 1
Looking at it again the scenario of a previous key not existing is correctly handled here: https://github.com/openshift/library-go/blob/master/test/library/encryption/helpers.go#L150-L153
=> Revert "Merge pull request #1477 from dgrisonnet/fix-encryption-test"

pkg/operator/staticpod/controller/guard/bindata/bindata.go, pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go, pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml, pkg/operator/staticpod/controllers.go
Building on top of https://github.com/openshift/library-go/pull/1478
=> [release-4.10] OCPBUGS-8235: Guard controller: set the readiness probe endpoint explicitly

pkg/operator/revisioncontroller/revision_controller.go
If a configmap or secret has been created, don't indicate it has "changed".
In addition, indicate whether the config or secret is required or optional.
=> revision: add more context to reason messages

pkg/cloudprovider/external.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
This PR migrates the AWS cloud provider from in-tree to out-of-tree. It must be merged in tandem with the PR for KCMO and CCMO to avoid a build that contains one or the other operator PRs without the other. If either merges without the other, it will either lead to no cloud controllers or duplicate cloud controllers, either of which will not work well.
Note the AWS cloud provider code has been removed from K8s in-tree in 1.27, this must merge in 4.14.
* [KCMO PR](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/707)
* [CCMO PR](https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/232)
* [Tested with Cluster Bot](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1633075931457261568) …
=> [OCPCLOUD-1988] Migrate AWS to out of tree cloud provider

pkg/cloudprovider/external.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
This PR migrates the Azure cloud provider from in-tree to out-of-tree. It must be merged in tandem with the PR for KCMO and CCMO to avoid a build that contains one or the other operator PRs without the other. If either merges without the other, it will either lead to no cloud controllers or duplicate cloud controllers, either of which will not work well.
* [KCMO PR](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/705)
* [CCMO PR](https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/231)
* [Cluster Bot](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-azure-modern/1633496854534557696)
* [Origin PR](https://github.com/openshift/origin/pull/27776)
=> [OCPCLOUD-1987] Migrate Azure to out of tree cloud provider

pkg/config/leaderelection/leaderelection.go, pkg/controller/controllercmd/cmd.go
In this [pr](https://github.com/openshift/library-go/pull/1104/files), we set the default value for `LeaseDuration/RenewDeadline/RetryPeriod`. 
But sometimes, the default config is not suitable for every component, so we should make these options are configurable.
=> make leader election option "LeaseDuration/RenewDeadline/RetryPeriod" configurable

pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
`ControlPlaneTopologyHook` is currently always the last in CSIControllerSet and sets `nodeSelector=nil` on HyperShift. This does not allow CSI driver operators that run in Hypershift's hosted control plane to set their own `nodeSelector` that would match HostedControlPlane CR.
Inspired by https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/93
Set the hook as the first one, so subsequent hooks can add their own node selector.
=> OCPBUGS-8691: Allow CSI driver operators to override nodeSelector on HyperShift

pkg/operator/configobserver/featuregates/simple_featuregate_reader.go, pkg/operator/configobserver/featuregates/simple_featuregate_reader_test.go
provides the API of https://github.com/openshift/library-go/pull/1468 with the old mechanism for reading featuregates form openshift/api to ease the transition.
=> provide new interface with old method of reading featuregates

pkg/cloudprovider/external.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
This reverts commit 3706d32a00d0cb0ed02d92f1789960440903dd4a.
Revert of https://github.com/openshift/library-go/pull/1484 to compare impact related to OCPBUGS-11308
=> Revert "Migrate Azure to out of tree cloud provider"

pkg/oauth/tokenrequest/challengehandlers/basicauth.go, pkg/oauth/tokenrequest/request_token_test.go
This is to sync the lib-go code with what's in oc.
xref https://github.com/openshift/oc/pull/991
=> tokenrequest: add webconsoleurl to basicauth challenger

pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go, pkg/operator/configobserver/featuregates/observe_featuregates.go, pkg/operator/configobserver/featuregates/observe_featuregates_test.go, pkg/operator/configobserver/featuregates/simple_featuregate_reader.go, pkg/operator/configobserver/featuregates/simple_featuregate_reader_test.go
For https://github.com/openshift/enhancements/pull/1373
Part 2 of a multi-step plan to make individual featuregates observable via the API. This was previously avoided because when featuregates get promoted from TechPreview to Default, during an upgrade, an old operator may try to enable a TechPreview variant of a feature.
This can be addressed by keying the featuregates by version. Let's see how ugly that will be in practice now that we have a decent build-out of library-go.
Unit tests are still owed.  Proof is still owed.  cluster-config-operator controller is still owed.
/hold
This is proving the concept, not to be merged until it shows as working end-to-end.
Other steps include
1. cluster-config-operator (upgrades first) writing the new featuregate
2. enhancements write up describing …
=> Read featuregates from cluster state

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
Centralize this aspect of manifest filtering, so it can be shared between the cluster-version operator ([where it currently lives][1]) and `oc` (where we want [manifest extraction to understand this sort of condition][2]).
[1]: https://github.com/openshift/cluster-version-operator/blob/cce97c25292b263a5a549b2bb8ce82ed7f2d4923/pkg/cvo/sync_worker.go#L959-L987
[2]: https://issues.redhat.com/browse/OTA-559
=> OTA-559: pkg/manifest: Add 'overrides' handling

pkg/cloudprovider/external.go, pkg/cloudprovider/external_test.go
This PR teaches the ExternalCloudProvider decision to understand new Azure and GCP feature gates so that these two CCMs can be promoted individually.
CC @deads2k
=> [OCPCLOUD-2034] Update Cloud Provider code to use new Azure/GCP specific feature gates

pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go, pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
In MCO, I need to be able to read a rendered `FeatureGate` from disk, and understand what the desired features are for the current version.
This wraps the hardcoded accessor with a function that extracts the data from the `FeatureGate.Status`, which should allow render stage operators to read from the installer generated features
=> Add FeatureGateAccess for reading from a static FeatureGate object

pkg/operator/render/options/config.go, pkg/operator/render/options/generic.go, pkg/operator/resource/resourceread/generic.go
This will make it easier to consume input from previous steps to do things like read featuregates.
/hold
holding for proof in cluster-config-operator.
=> add mechanism to read previously rendered manifests during rendering

pkg/operator/render/options/config.go, pkg/operator/render/options/generic.go
=> tweak rendering reader for easier consumption

pkg/operator/render/options/config.go, pkg/operator/render/options/generic.go
/hold
This would require that manifests be consistent with each other.  They should be already given random retries, but this is a choice.
=> make reading rendered manifests easier

pkg/operator/render/options/generic.go, pkg/operator/render/render.go
read featureset from FeatureGate manifest.
=> add featureset reading

pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml, pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml, pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml, pkg/operator/apiserver/audit/testdata/multipleCr.yaml, pkg/operator/apiserver/audit/testdata/oauth.yaml, pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
Don't audit-log jwt tokens (pre-SHA'ed).
- the **kube-apiserver** logs `serviceaccounts/token`.
- The **oauth-apiserver** logs `tokenreviews` from `oauth.openshift.io`.
- I couldn't find `tokenrequests` from `oauth.openshift.io`, but added it anyway.
I couldn't find any references to `tokenreviews` from `oauth.openshift.io`.
Should we be worried about that?
```yaml
User: &{system:node:$NODE_NAME [system:nodes system:authenticated] map[]}
Verb: create
IsReadOnly: false
Namespace: openshift-cluster-csi-drivers
Resource: serviceaccounts
Subresource: token
Name: gcp-pd-csi-driver-operator
APIGroup: 
APIVersion: v1
IsResourceRequest: true
Path: /api/v1/namespaces/openshift-cluster-csi-drivers/serviceaccounts/gcp-pd-csi-driver-operator/token
```
```yaml
User: …
```
=> OCPBUGS-2765: don't log jwt tokens

pkg/operator/render/options/generic.go
cleaning up after https://github.com/openshift/installer/pull/7152
=> remove the old featuresets flag that can conflict with manifests

pkg/operator/render/options/generic.go
This aims to fix [this comment](https://github.com/openshift/installer/pull/7158#issuecomment-1547582330).
Because the `LoadFilesRecusively` function returns the path names relative to the directory passed into it, the original filenames currently do not take into account the path to the directory. We must include the directory in the original filename else files will likely just be dumped back into CWD (which is what I saw in debugging the feature gate issue)
=> Make sure the directory path is included in rendered manifest paths

test/library/encryption/assertion.go, test/library/encryption/perf_scenarios.go, test/library/encryption/scenarios.go
Cherry-pick a missing commit with testing code for AES-GCM that was added for 4.13 release.
=> test/library/encryption: add aesgcm

pkg/operator/staticpod/installerpod/cmd.go
To conform to CIS benchmarks
Testing PR: https://github.com/openshift/cluster-kube-scheduler-operator/pull/485
=> staticpod installer: set the manifests directory permissions to 0600

pkg/cloudprovider/OWNERS
The cloud team should own this, for now, myself and @elmiko have the context on this
=> Add OWNERS file for cloudprovider package

pkg/controller/factory/base_controller.go, pkg/controller/factory/factory.go
before you could find `Controller %q resync interval is set to %s which might lead to client request throttling` in the logs for `0` interval which was misleading because the controller requires an interval to be > 0 and < 60s
xref: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1503
=> OCPBUGS-13946: report fast resync interval only when > 0 and < 60

pkg/operator/apiserver/controller/apiservice/apiservice_controller.go, pkg/operator/apiserver/controller/apiservice/apiservice_controller_test.go
SSIA
Needed by https://github.com/openshift/cluster-openshift-apiserver-operator/pull/532
=> WRKLDS-728: controller/apiservice: allow to disable/delete an API service resources

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
Because the default Go serialization causes some very long lines:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/950/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-ovn/1670881314321993728/artifacts/e2e-aws-ovn/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-8598f95688-jswk8_cluster-version-operator.log | grep ' excluding ' | head -n1
I0619 20:21:07.321663       1 payload.go:210] excluding {0000_10_config-operator_01_apiserver-CustomNoUpgrade.crd.yaml {apiextensions.k8s.io CustomResourceDefinition apiservers.config.openshift.io } {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{...
$ curl -s …
```
=> pkg/manifest: Add Manifest.String() method

pkg/operator/staticpod/installerpod/cmd.go
To be more compliant with CIS benchmarks
/hold
so the change can be verified in KSO and KCMO first.
=> OCPBUGS-15256: installerpod: change config map based files mode to 0600

pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller.go, pkg/operator/csi/csicontrollerset/csi_controller_set.go
When using Amazon Web Services (AWS) Secure Token Service (STS), a OLM-based CSI driver operator must add `cloudTokenPath` and `providerSpec.stsIAMRoleARN` to its CredentialsRequest.
Add hook support to CredentialsRequestController to allow them so.
In addition, CredentialsRequestController must sync CredentialsRequest even when CCO is in Manual mode, because it can still create Secrets for STS CredentialsRequest.
Enhancement: https://github.com/openshift/enhancements/blob/master/enhancements/cloud-integration/tokenized-auth-enablement-operators-on-cloud.md
@openshift/storage
=> STOR-1376: Allow CredentialsRequestController to work in STS mode

pkg/features/features.go
Update `setFeatureGates()` to use `GetAll()` to fetch all known featuregates that were initialized instead of using `KnownFeatures()` since it returns the feature gates in the following format `RouteExternalCertificate=true|false (ALPHA - default=false)`. 
Follow up for: https://github.com/openshift/library-go/pull/1550
=> Fix techpreviewnouprade feature set initialization

pkg/operator/apiserver/controller/apiservice/apiservice_controller.go, pkg/operator/apiserver/controllerset/apiservercontrollerset.go
https://github.com/openshift/cluster-openshift-apiserver-operator/pull/532#discussion_r1284264567
APIServiceController can be passed a list of disabled/enabled APIs which might require additional resource to take into account when reconciling. In the case of https://github.com/openshift/cluster-openshift-apiserver-operator/pull/532 new capabilities are taken into account when rendering a list of enabled/disabled API services.
=> APIServiceController: allow to pass informers for registering additional event handlers

pkg/crypto/crypto.go, pkg/crypto/crypto_test.go
When generating certificates there is a check to see if the cert already exists. If it does, it compares the existing IPs and DNSs in the cert against the hostnames it should have. If there is one missing entry from the hostnames in the cert it is regenerated. If not, then the cert is left untouched.
There is no check to see if the entries in the cert are present in the hostname list, leaving room for outdated IP/DNS entries to remain.
In other words: If the certificate already exists and one or more entries are removed from the hostnames list, the cert will be left untouched and those wrong values will be part of the CN/SANs.
=> USHIFT-1593: Regenerate certs on hostname changes

pkg/operator/staticpod/installerpod/cmd.go
Set static pod manifests permissions to 0600 to conform with CIS benchmarks.
proof PR: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1544
=> OCPBUGS-16796: pkg/operator: update static pod manifests perms

pkg/certs/cert-inspection/certgraphanalysis/analyzer.go
v1beta1 has different fields and apparently not used in any supportable OCP version anymore.
Follow up for https://github.com/openshift/library-go/pull/1581#discussion_r1350548131
=> cert-inspection: remove InspectCSRv1beta1

pkg/config/serving/server.go, pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/cmd.go
backport of https://github.com/openshift/library-go/pull/1587
=> Allow enabling HTTP, the default is off [4.14]

pkg/config/serving/server.go, pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/cmd.go
backport of https://github.com/openshift/library-go/pull/1587
=> Allow enabling HTTP, the default is off [4.13]

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/target.go
certrotation: allow setting an owner reference on rotated content
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
certrotation: make status reporting optional
When we're rotating certificates in a context that does not have a
static pod on which OperatorConditions are exposed, we need to emit our
status reporting in another manner. Unfortunately, without some external
place to store the prior reporing state, we can't only report on state
transitions. Therefore, we choose to only report errors and hope that it
will not be spammy.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
=> certrotation: add more options for consumers

pkg/certs/cert-inspection/certgraphanalysis/collection_options.go, pkg/certs/cert-inspection/certgraphanalysis/collector.go, pkg/certs/cert-inspection/certgraphanalysis/filtering_options.go, pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
Skip secrets and configmaps hashed by openshift-monitoring, i.e. prometheus-adapter secret. Follow up for https://github.com/openshift/library-go/pull/1599
Testing this in https://github.com/openshift/origin/pull/28373
=> cert-inspection: add RewriteNodeIP options

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go
E.g. to re-create completed pods produced by kubelet preemption
/hold until the change proved to be working
=> OCPBUGS-18697: guard controller: re-create pods with phase nor pending neither running

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controllers.go
optionally `pdbUnhealthyPodEvictionPolicy` can be set to `AlwaysAllow` to allows
eviction of unhealthy (not ready) pods even if there are no disruptions allowed
on a PodDisruptionBudget. This can help to drain/maintain a node and recover
without a manual intervention when multiple instances of nodes or pods are
misbehaving. Use this with caution, as this option can disrupt perspective pods
that have not yet had a chance to become healthy (ready).
Solves the following issue:
1. upgrade the cluster 
2. 2 or more kube-apiserver pod do not become online. Network access could be lost due to misconfiguration or wrong rhel update. We can simulate this with:
- ssh into a node 
-  run `iptables -A INPUT -p tcp --destination-port 6443 -j DROP`
3. 2 or more kube-apiserver-guard pods lose readiness …
=> OCPBUGS-23796: add pdbUnhealthyPodEvictionPolicy option to a GuardController 

pkg/operator/revisioncontroller/revision_controller.go, pkg/operator/v1helpers/helpers.go
In some cases a status yields two different revisions for supposedly the same status. Either there's some other code updating the status in parallel or the static pod operator client is slow in updating its internal cache. Either way the revision controller reports a possible race when updating the latest available revision.
This PR is meant strictly to get better idea about the operator status to help in debugging https://issues.redhat.com/browse/OCPBUGS-21846. Once the underlying issue is resolved, this change is expected to be reverted.
=> OCPBUGS-21846: revision_controller: be more verbose about LatestAvailableRevision and resourceVersion

pkg/operator/certrotation/annotations.go, pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/target.go, pkg/operator/csr/cert_controller.go, pkg/operator/resourcesynccontroller/core.go
This updates RotatedSelfSignedCertKeySecret, RotatedSigningCASecret and CABundleConfigMap structs and functions so that managed secrets and configmaps are annotated to identify component and purpose of the secret.
See https://github.com/openshift/cluster-kube-apiserver-operator/pull/1568 for example of usage
=> cert rotation: add optional jira component and description annotations to TLS artifacts

pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/builder_test.go
In a HyperShift context, the toplogy that a component is expected to adhere to is not the management-cluster-wiide infrastructure, but the tenant-specific value. This commit allows consumers to detect topology in less rigid ways.
=> controllercmd: allow configuring topology detection

pkg/certs/cert-inspection/certgraphanalysis/collection_options.go, pkg/certs/cert-inspection/certgraphanalysis/collector.go, pkg/certs/cert-inspection/certgraphanalysis/filtering_options.go, pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go, pkg/certs/cert-inspection/certgraphapi/type_registry.go
This is useful so that we can have a calling repo (like origin for instance), specify the annotations to be collected without updating the schema.  But we are able to avoid a free-for-all of "any annotation you like" by requiring a list to be provided.
=> Add ability to collect whitelisted annotations specified by the caller

pkg/operator/revisioncontroller/revision_controller.go, pkg/operator/v1helpers/helpers.go
Reverts openshift/library-go#1631
=> OCPBUGS-21846: Revert "OCPBUGS-21846: revision_controller: be more verbose about LatestAvailableRevision and resourceVersion"

pkg/operator/status/condition.go, pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
Cherry-pick of https://github.com/openshift/library-go/pull/1634
Add ClusterFleetEvaluationType to status controller.
It is a valid ClusterOperator status, but doesn't have a mechanism to be pulled from Operator's status into ClusterOperator's status.
=> AUTH-471: pkg/operator/status - add EvaluationConditionDetected

pkg/apiserver/apiserverconfig/longrunning.go, pkg/apiserver/apiserverconfig/longrunning_test.go
Avoid using expensive MatchString when request params are already set in requestInfo
Back in 3.x days this was necessary as buildconfigs and imagestreams was served under `/oapi`, but now they are proper CRs so its better to match them via requestInfo params
```
$ benchstat -delta-test=none old.txt new.txt               
name                                                                 old time/op  new time/op  delta
IsLongRunningRequest/path_/api-8                                     11.5ns ± 5%   9.9ns ± 8%  -14.20%
IsLongRunningRequest/path_/api/buildconfigs/foo/instantiatebinary-8   870ns ± 7%     6ns ± 9%  -99.32%
IsLongRunningRequest/path_/api/imagestreamimports-8                   391ns ± 3%    10ns ± 5%  -97.47%
```
Next this needs to be re-imported by openshift-apiserver
=> OCPBUGS-19056: apiserver: optimize IsLongRunningRequest

pkg/operator/revisioncontroller/revision_controller.go, pkg/operator/revisioncontroller/revision_controller_test.go
fixes https://github.com/openshift/library-go/pull/1649 by adding a commit that ensures that the latestAvailableRevision  actually is the latest instead of hoping that the second update actually works.
Looking at https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.16-e2e-gcp-sdn-techpreview-serial/1736680969496170496 we can see 
> 2023-12-18T09:56:54.930966948Z I1218 09:56:54.930910       1 revision_controller.go:247] down the branch indicating that our cache was out of date and we're trying to recreate a revision.
2023-12-18T09:56:54.939349351Z I1218 09:56:54.939268       1 event.go:298] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-kube-apiserver-operator", Name:"kube-apiserver-operator", …
=> Fix ordering bug

pkg/operator/resource/resourceapply/admissionregistration.go, pkg/operator/resource/resourceapply/apiextensions.go, pkg/operator/resource/resourceapply/apiregistration.go, pkg/operator/resource/resourceapply/apps.go, pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/migration.go, pkg/operator/resource/resourceapply/monitoring.go, pkg/operator/resource/resourceapply/policy.go, pkg/operator/resource/resourceapply/rbac.go, pkg/operator/resource/resourceapply/storage.go, pkg/operator/resource/resourceapply/volumesnapshotclass.go
if we're about to make a server call from an operator, it's worth the cost to log the reason for the change.  We won't add to the event (yet) due to the additional size, but it could be considered for a good enough reason.
Came up while checking https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-sdn-cgroupsv2/1743684397107777536
=> move diff before update to klog v2

pkg/operator/configobserver/config_observer_controller_test.go, pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go, pkg/operator/managementstatecontroller/management_state_controller_test.go, pkg/operator/status/status_controller_test.go, pkg/operator/v1helpers/helpers.go, pkg/operator/v1helpers/interfaces.go, pkg/operator/v1helpers/test_helpers.go
The retry logic already existed, but relied on updating the cache.  In runs like https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-sdn-cgroupsv2/1743684397107777536 (and others I've seen) this appears to be highly latent when observing the 
> base_controller.go:268] ConsoleOperator reconciliation failed: Operation cannot be fulfilled on consoles.operator.openshift.io "cluster": the object has been modified; please apply your changes to the latest version and try again
messages.  It's not likely to be connectivity since the updates are going through.  The lister is still preferred, but after the first failure (made this easy to tune), the code does a live GET of the current state.
/assign @stlaz 
eliminates the noise.
=> when updating status, do a live GET after conflict

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/cabundle_test.go, pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
for CEO we would like to dynamically run this controller multiple times within the lifetime of another. We would need to expose some struct fields for that.
=> expose more funcs for etcd cert_rotation 

pkg/operator/certrotation/annotations.go, pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/target.go, pkg/operator/csr/cert_controller.go, pkg/operator/resourcesynccontroller/core.go
Function signature won't require changes when new cert requirements are being created
Tested in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1631
=> certrotation: replace JiraComponent/Description with AdditionalMetadata struct

test/library/metrics/query.go
OCPBUGS-19527 shows that when the code fails to retrieve the list of secrets from openshift-monitoring, the leaf error isn't logged (only  `"failed to list secrets in the openshift-monitoring namespace"`).
=> OCPBUGS-19527: wrap errors for clarity

pkg/cloudprovider/external.go, pkg/cloudprovider/external_test.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
The final external cloud providers were promoted in 4.15. Feature gates are no longer required to make the decision on whether the CCMs should be GA or not. This PR removes the feature gate access and cleans up the function so that it may continue to provide a respect of which platforms are external going forward, without the need for feature gate access.
Once this is merged, KASO, KCMO, MCO and CCMO will all need to be updated.
=> OCPCLOUD-2514: Cloud Provider External no longer depends on a feature gate

pkg/verify/verify.go
Typo slipped in when the file was created in c43c2cb208 (#837).
=> pkg/verify: Fix "suffient" -> "sufficient" Godoc typo

pkg/operator/certrotation/metadata.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
Pre-4.7 clusters had `SecretTypeTLS` type set, so on 4.15 upgrade these clusters had the secret delete and recreated. This commit will ensure these are being created without cert and key being regenerated.
Fixes two issues wrt handling secrets:
* existing secret type is converted to `kubernetes.io/tls`. If it cannot be done (i.e. `tls.crt` or `tls.key` is missing) it would be regenerated with `SignerUpdateRequired` event
* if the type can be converted existing data is preserved, so born-before-4.7 clusters look identical to 4.15 clusters in regards to secret type
=> OCPBUGS-30119: certrotation: update all secret types to `kubernetes.io/tls` preserving existing content

pkg/operator/certrotation/annotations.go, pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/metadata.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go, pkg/operator/csr/cert_controller.go, pkg/operator/resourcesynccontroller/core.go
Cherrypick of https://github.com/openshift/library-go/pull/1681 on release-4.15
=>  OCPBUGS-30304: [release-4.15] certrotation: update all secret types to kubernetes.io/tls preserving existing content

pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
etcd is now including IP in cert description, it needs to be replaced with `<master-index>` too
=> NO-JIRA: cert-inspection: replace node name from annotation value

pkg/route/common.go, pkg/route/hostassignment/assignment.go, pkg/route/hostassignment/assignment_test.go, pkg/route/hostassignment/externalcertificate.go, pkg/route/hostassignment/externalcertificate_test.go, pkg/route/validation/validation.go, pkg/route/validation/validation_test.go
Updates route validations based on openshift/enhancements#1307 which introduces a new field in the route API externalCertificate behind the TP feature gate.
- `ValidateRoute()` has been updated to pass additional args (secrets lister and subjectaccessreviewer) to validate
`externalCertificate` and the rbac required. Now it also does additional subject access review authorization checks to verify if the router SA has the correct permissions to parse `externalCertificate`. It also adds a hard requirement that the secret referenced in `externalCertificate` be present prior to creating the route.
- `ValidateHostUpdate()` has also been updated since updating route host/subdomain is also affected by updating
certificates on the route. Now `certificateChangeRequiresAuth()` will always return …
=> CFE-882: Route external certificate validation

pkg/route/hostassignment/assignment.go, pkg/route/hostassignment/assignment_test.go
Follow up : https://github.com/openshift/library-go/pull/1625
=> CFE-882: add few test cases for external-certificate

pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go
this helps in updating CEO status in a rotation process.
=> add return flag when signer was regenerated

pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go, pkg/operator/resource/resourceapply/core.go
back port of https://github.com/openshift/library-go/pull/1705
not clean, requires reviewing.
=> OCPBUGS-31807: [release-4.15] use update only secret-apply for cert rotation logic

pkg/operator/bootstrap/bootstrap.go, pkg/operator/bootstrap/bootstrap_test.go
`IsBootstrapComplete` returns true if bootstrap has completed.
This function checks if `bootstrap` config map in `kube-system` namespace was created and has status equal to complete.
The configmap is created when bootstrapping is done [by the installer](https://github.com/openshift/installer/blob/911203db89a5728f00aaef011b5fb8add7abf646/data/data/bootstrap/files/usr/local/bin/report-progress.sh#L21). 
As of today it is used by [etcd](https://github.com/openshift/cluster-etcd-operator/blob/3d5483e1871ba147a692736c71645175a85769c4/pkg/operator/ceohelpers/bootstrap.go#L110) and [network](https://github.com/openshift/cluster-network-operator/blob/d25562d4a52220b7ed3be76bc848ba26eae068f2/pkg/network/node_identity.go#L37-L46) operators
As of today there is nothing else we could depend on to …
=> operator/bootstrap: expose IsBootstrapComplete function

pkg/operator/apiserver/controller/apiservice/apigroup.go, pkg/operator/apiserver/controller/apiservice/apiservice_controller.go, pkg/operator/apiserver/controller/apiservice/apiservice_controller_test.go
This PR refactors `newEndpointPrecondition ` into `preconditionsForEnabledAPIServices` so that other preconditions can be defined.
I'm planing to use it in https://github.com/openshift/library-go/pull/1694 and later on in https://github.com/openshift/cluster-authentication-operator/pull/662
=> OCPBUGS-24195: controller/apiservice: support for defining multiple preconditions

pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
Required to be able to advise customers to follow workflow described in https://github.com/openshift/enhancements/pull/1583. If they want to taint control-plane nodes to avoid any other thing to run there (while enforcing it further with validating admission policies), control plane workloads need to tolerate that taint.
installer-pods: already tolerate every taint
pruner-pods: already tolerate every taint
guard-pods: toleration to relevant NoExecute taint added
monitor-pods: already tolerate every taint
=> WRKLDS-1167: tolerate node-role.kubernetes.io/control-plane:NoExecute 

pkg/secret/OWNERS, pkg/secret/fake/fake_secret_monitor.go, pkg/secret/monitor.go, pkg/secret/monitor_test.go, pkg/secret/secret_monitor.go, pkg/secret/secret_monitor_test.go
Functionality for monitoring and handling "single" secret dynamically. 
- `ObjectKey`  representing the unique identifier for a resource.
- `singleItemMonitor`  responsible for monitoring a single resource using a SharedInformer.
- Defined methods for starting and stopping informers, adding and removing event handlers, and retrieving items from the informer's cache.
- Implemented functionalities to create and manage informers for specific secrets.
- `SecretEventHandlerRegistration`  for registering and unregistering event handlers for secret monitoring.
- `SecretMonitor`  for monitoring and handling specific secrets using `singleItemMonitor`.
- Added methods for adding and removing secret event handlers, retrieving secret objects from the informer's cache.
- operations for counting the …
=> CFE-866: feature: monitoring and handling "single" secret dynamically

pkg/route/secretmanager/fake/fake_manager.go, pkg/route/secretmanager/manager.go, pkg/route/secretmanager/manager_test.go
This PR adds `route` layer (introduces a new `secretmanager` package) on top of https://github.com/openshift/library-go/pull/1675 to consume the `secret_monitor`.
These changes primarily focus on enhancing the functionality of managing secrets associated with routes. 
- **RegisterRoute**: Allows registering a route with a secret, enabling dynamic monitoring of secret changes associated with the route.
- **UnregisterRoute**: Provides functionality to remove the registration of a route from the monitor.
- **GetSecret**: Enables retrieving the secret object registered with a route.
Related: [CFE-866](https://issues.redhat.com//browse/CFE-866)
Implements: https://github.com/openshift/enhancements/pull/1307
=> CFE-866: Add secret manager for routes to consume secret_monitor

pkg/operator/deploymentcontroller/deployment_controller.go
This is specially useful for controllers that don't want certain conditions.
=> OCPBUGS-29126: deploymentcontroller: use builder pattern

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
These flags are being deprecated and will eventually raise an error when
set.
Sibling PRs to remove the calls to the NewCloudProviderObserver function will be added here.
Signed-off-by: Nolan Brubaker <nolan@nbrubaker.com>
=> OCPCLOUD-2513: Remove cloud-provider and cloud-config flags

pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
https://issues.redhat.com/browse/OCPBUGS-24061
Patching the ClusterCSIDriver causes the `progressing` condition to flip-flop between true and false during DaemonSet rollout. For example:
`$ oc -n openshift-cluster-storage-operator get event --sort-by='.lastTimestamp' --watch`
`$ oc patch clustercsidriver/csi.vsphere.vmware.com --type=merge -p '{"spec":{"driverConfig":{"vSphere":{"globalMaxSnapshotsPerBlockVolume": 5}}}}'`
```
0s          Normal    OperatorStatusChanged                            deployment/cluster-storage-operator                       Status for clusteroperator/storage changed: Progressing changed from False to True ("VSphereCSIDriverOperatorCRProgressing: VMwareVSphereDriverNodeServiceControllerProgressing: Waiting for DaemonSet to act on changes")
0s          Normal …
```
=> OCPBUGS-24061: Keep CSI operators progressing=true during DaemonSet rollout

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
This was returning the previous config, which means when we vendor it into KCMO, the config can never be removed.
The intention was to return an empty configuration.
=> Return empty configuration from cloud observer

pkg/route/hostassignment/assignment.go
Return "you do not have permission" error messages instead of "field is immutable" error messages when the user tries to update a route's `spec.host`, `spec.subdomain`, or `spec.tls` field without the required "custom-host" permission.
Note that this change does not affect the HTTP status code for these errors, which will continue to be HTTP 422, "Unprocessable Entity", as both [the openshift-apiserver admission](https://github.com/openshift/openshift-apiserver/blob/c5ba848e78463f9c73e1d2daec9e565daa4a6f4a/vendor/k8s.io/apiserver/pkg/registry/rest/update.go#L154-L156) and [the kube-apiserver admission](https://github.com/openshift/kubernetes/blob/5a4819c6048e42515c3c5538b723ba6272440eee/openshift-kube-apiserver/admission/route/hostassignment/admission.go#L135-L137) wrap errors from the …
=> OCPBUGS-22332: route: Improve errors for missing custom-host permissions

pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go, pkg/operator/deploymentcontroller/deployment_controller.go, pkg/operator/deploymentcontroller/deployment_controller_test.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
We want to disable storage if system administrator sets `spec.ManagementState` of ClusterCSIDriver to `Removed`. This PR ensures that NodeService and Deployment controllers delete resources when `spec.ManagementState` is `Removed`.
Also, it patches `StaticResourceController` Sync() to call `DeleteAll()` if the ManagementState is Removed, and implements support of multiple conditional StaticResourceControllers.
/cc @openshift/storage @jsafrane
=> STOR-1767: Delete resources if spec.ManagementState is equal to Removed for removable CSI drivers

pkg/verify/configmap.go
Previously, when both `ReadArmoredKeyRing` and `ReadKeyRing` failed, we'd only return the latter error.  But in [OCPBUGS-35528][1], `ReadArmoredKeyRing` errors like:
openpgp: invalid data: user ID self-signature invalid: openpgp: invalid signature: RSA verification failure
pointed at the SHA-1 self-signature issue, but were masked by `ReadKeyRing`'s:
openpgp: invalid data: tag byte does not have MSB set
and required additional work on out-of-cluster reproducers.  With this commit, we'll return an error aggregating both underlying errors on failure, to make future debugging easier.
[1]: https://issues.redhat.com/browse/OCPBUGS-35528
=> OCPBUGS-35528: pkg/verify/configmap: Aggregate errors in loadArmoredOrUnarmoredGPGKeyRing

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go, pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/staticpod/controllers.go
Some static pod controllers use cached listing clients and they were not properly synchronized.
=> Ensure static pod controller informers sync

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
Each function used in cert rotation controller should issue just one ApplySecret/ApplySecret per call. This call may  not be atomic, so running several replicas of this controller can cause unexpected races
=> API-1802: certrotation: issue one Update request in cert rotation functions

pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivernodeservicecontroller/helpers.go
We already have these for secrets. Add them for config maps.
This is needed for the OpenStack Cinder CSI Driver Operator. See https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/168/ for more information.
=> csi: Add Deployment, DaemonSet hooks for config map hash annotations

pkg/operator/resource/resourceapply/admissionregistration.go
For k8s 1.30, ValidatingAdmissionPolicy is GA and only v1 is enabled by default.
=> Add support for ValidatingAdmissionPolicy v1

pkg/config/validation/general.go, pkg/controller/factory/controller_context.go, pkg/oauth/tokenrequest/request_token.go, pkg/operator/configobserver/featuregates/featuregate.go, pkg/operator/configobserver/featuregates/observe_featuregates_test.go, pkg/operator/encryption/controllers/prune_controller.go, pkg/operator/staticpod/prune/cmd.go, pkg/route/validation/validation.go
Now that Go includes slice operations such as slices.Contains, some uses of sets are no longer useful. In particular, creating a set using a slice just to check whether the slice contains a specific item is more expensive than checking the slice directly.
=> Avoid using sets when existing slices suffice

test/library/junitapi/types.go
moved from https://github.com/openshift/origin/blob/master/pkg/test/ginkgo/junitapi/types.go for re-use.
/assign @dgoodwin
=> add junit types for serializing junit directly

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
Avoiding failures like:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-capi-operator/181/pull-ci-openshift-cluster-capi-operator-main-e2e-aws-capi-techpreview/1806459134145466368/artifacts/e2e-aws-capi-techpreview/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-85cdd86f99-nrqd6_cluster-version-operator_previous.log | grep '0000_30_cluster-api_00_namespace.yaml'
I0627 23:22:20.849886       1 payload.go:210] excluding Filename: "0000_30_cluster-api_00_namespace.yaml" Group: "" Kind: "Namespace" Name: "openshift-cluster-api": unrecognized value "CustomNoUpgrade" in release.openshift.io/feature-set=CustomNoUpgrade,TechPreviewNoUpgrade; known values are: …
```
=> NO-ISSUE: pkg/manifest: Restore CustomNoUpgrade handling

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/cabundle_test.go, pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/target.go
* Explicitly log "secret/configmap doesn't exist" events
* when CA bundle is updated log which signer update caused it
Tested in this [job](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-gcp-modern/1805164315519488000) with shortened rotation periods.
[This Loki query](https://grafana-loki.ci.openshift.org/explore?orgId=1&left=%7B%22datasource%22%3A%22PCEB727DF2F34084E%22%2C%22queries%22%3A%5B%7B%22expr%22%3A%22%7Binvoker%3D%5C%22openshift-internal-ci%2Frelease-openshift-origin-installer-launch-gcp-modern%2F1805164315519488000%5C%22%2C+type%3D%5C%22pod%5C%22%7D+%7C+json+%7C+namespace%3D%7E%5C%22openshift-%28etcd-operator%7Ckube%29.*%5C%22+%7C+line_format+%5C%22%7B%7B._entry%7D%7D%5C%22+%7C%7E+%5C%22%28SignerUpdateRequired%7CTarget …
=> NO-JIRA: certrotation: improve error messages

pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go, pkg/operator/resource/resourceapply/core.go
This reverts commit 96e8597e284a104936ffc92a54c458ac08523e25.
All `SecretTypeTLS` secrets have been migrated to `kubernetes.io/tls` type on 4.15 upgrade, time to remove the deprecated setting which enables this migration. This also prevents us from landing #1772
=>  OCPBUGS-38335: Revert "use update only secret-apply for cert rotation logic"

pkg/certs/cert-inspection/certgraphanalysis/collector.go
Bootstrap node name is no longer the last word in the description, instead the name should be extracted from the secret name.
Testing this in https://github.com/openshift/origin/pull/28868
=> certgraphanalysis: update bootstrap name lookup

pkg/cloudprovider/external.go
Dropped variables which are no longer present in openshift/api.  These variables do not appear to be used elsewhere, but their presence in library-go causes api bumps in other repos which use library-go to fail.
=> SPLAT-1772: drop vars removed in api#1780

pkg/operator/resource/resourcehelper/resource_helpers.go
If Create/Update returns nil pointer `GuessObjectGroupVersionKind` should not panic and return `<unknown>` kind
=> OCPBUGS-39255: resourcehelper: handle nil object when guessing GVK

pkg/operator/apiserver/audit/manifests/base-policy.yaml, pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml, pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml, pkg/operator/apiserver/audit/testdata/default.yaml, pkg/operator/apiserver/audit/testdata/multipleCr.yaml, pkg/operator/apiserver/audit/testdata/none.yaml, pkg/operator/apiserver/audit/testdata/oauth.yaml, pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
Re-enable audit logs about Events to be able to identify misconfigured clients.
=> audit/manifests: log requests to Events

pkg/certs/cert-inspection/certgraphanalysis/analyzer.go, pkg/certs/cert-inspection/certgraphanalysis/collector.go, pkg/certs/cert-inspection/certgraphanalysis/disk_certs.go
Extract CA and certs used in kubeconfigs as TLS artifacts too.
Tested in https://github.com/openshift/origin/pull/28864
=> OCPBUGS-35231: cert-inspection: parse secret/configmap/files as kubeconfigs

pkg/route/secretmanager/fake/fake_manager.go, pkg/route/secretmanager/manager.go, pkg/route/secretmanager/manager_test.go
Update `IsRouteRegistered()` to `LookupRouteSecret()` which will also return the registered secret name from secretManager.
```
LookupRouteSecret returns the secret name associated with a route,
and true indicating if the route is registered with manager.
If the route is not registered, an empty string and false are returned.
```
Related to [OCPBUGS-33958](https://issues.redhat.com/browse/OCPBUGS-33958)
=> OCPBUGS-33958: retrieve registered secret name from secretManager

pkg/controller/factory/base_controller.go, pkg/controller/factory/interfaces.go, pkg/operator/README.md, pkg/operator/apiserver/controller/apiservice/apiservice_controller.go, pkg/operator/configobserver/config_observer_controller_test.go, pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go, pkg/operator/managementstatecontroller/management_state_controller_test.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/staticresourcecontroller/static_resource_controller.go, pkg/operator/status/status_controller_test.go, pkg/operator/v1helpers/canonicalize.go, pkg/operator/v1helpers/interfaces.go, pkg/operator/v1helpers/test_helpers.go
use apply in operator status instead of updates.  This will
1. eliminate unnecessary conflicts and repeated writes
2. eliminate retries in controller logic
3. make it easier to describe desired state from multiple different controllers
4. make it possible to locate conflicting writers in CI
Messing around with the core bits in this repo and will try revendoring into a couple.
=> API-1835: Apply operator status

pkg/operator/genericoperatorclient/dynamic_operator_client.go
Manual check of applies looks clean.
=> API-1835: prevent conditions missing information

pkg/operator/deploymentcontroller/deployment_controller.go
Failure:
```
{Operator degraded (GCPPDCSIDriverOperatorCR_GCPPDDriverControllerServiceController_SyncError): GCPPDCSIDriverOperatorCRDegraded: GCPPDDriverControllerServiceControllerDegraded: unable to ApplyStatus for operator using fieldManager "": PatchOptions.meta.k8s.io "" is invalid: fieldManager: Required value: is required for apply patch  Operator degraded (GCPPDCSIDriverOperatorCR_GCPPDDriverControllerServiceController_SyncError): GCPPDCSIDriverOperatorCRDegraded: GCPPDDriverControllerServiceControllerDegraded: unable to ApplyStatus for operator using fieldManager "": PatchOptions.meta.k8s.io "" is invalid: fieldManager: Required value: is required for apply patch}
```
xref: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_gcp-pd-csi-driver-operato …
=> API-1835: fix initialization of variable in deployment controller

pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
If ControlPlaneTopology is set to `HighlyAvailable` return pod count 2 else 1.
=> OCPBUGS-36233: Replicas hook consider Control plane topology

pkg/operator/apiserver/audit/manifests/base-policy.yaml, pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml, pkg/operator/apiserver/audit/testdata/default.yaml, pkg/operator/apiserver/audit/testdata/multipleCr.yaml, pkg/operator/apiserver/audit/testdata/none.yaml, pkg/operator/apiserver/audit/testdata/oauth.yaml, pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
when we switched the API [servers](https://github.com/openshift/cluster-openshift-apiserver-operator/pull/588) to use the /livez EP we forgot to update the audit policy.
this pr updates the base policy which stops logging request to the mentioned ep.
kudos to @deads2k for discovering this.
proof pr at https://github.com/openshift/cluster-kube-apiserver-operator/pull/1751
=> audit: do not log requests to /livez

pkg/manifestclient/mutation_tracker.go, pkg/manifestclient/read_roundtripper.go, pkg/manifestclient/readwrite_roundtripper.go, pkg/manifestclient/write_roundtripper.go, pkg/manifestclienttest/client_test.go, pkg/manifestclienttest/client_write_test.go, pkg/manifestclienttest/informer_test.go, pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go, pkg/operator/genericoperatorclient/test_operator_client.go
Adds the ability to track mutations to our manifest client with unit tests.  We can build on this for comparing predicted versus actual mutations.
=> API-1835: add mutation tracking to the fake client

pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller.go, pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller_test.go
Similar to `ROLEARN` check for AWS we need to check GCP WIF values and decide about syncing credentials request. Also moves the logic to separate function for clarity.
=> STOR-1988: support GCP WIF in credentials request controller

pkg/manifestclient/mutation_directory_reader.go, pkg/manifestclient/mutation_directory_writer.go, pkg/manifestclient/mutation_tracker.go, pkg/manifestclient/readwrite_roundtripper.go, pkg/manifestclient/serialized_request.go, pkg/manifestclient/serialized_request_test.go, pkg/manifestclient/write_roundtripper.go, pkg/manifestclienttest/client_test.go, pkg/manifestclienttest/client_write_test.go, pkg/manifestclienttest/testdata/mutation-tests/APPLY-STATUS-crd-in-dataset-with-options/ApplyStatus/cluster-scoped/config.openshift.io/featuregates/001-body-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/APPLY-STATUS-crd-in-dataset-with-options/ApplyStatus/cluster-scoped/config.openshift.io/featuregates/001-options-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/APPLY-crd-in-dataset/Apply/cluster-scoped/config.openshift.io/featuregates/001-body-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/APPLY-crd-in-dataset/Apply/cluster-scoped/config.openshift.io/featuregates/001-options-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/CREATE-crd-in-dataset/Create/cluster-scoped/config.openshift.io/featuregates/001-body-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/CREATE-crd-not-in-dataset/Create/cluster-scoped/config.openshift.io/apiservers/001-body-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/DELETE-crd-in-dataset/Delete/cluster-scoped/config.openshift.io/featuregates/001-body-cluster.yaml, pkg/manifestclienttest/testdata/mutation-tests/UPDATE-STATUS-crd-in-dataset-with-options/UpdateStatus/cluster-scoped/config.openshift.io/featuregates/001-body-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/UPDATE-STATUS-crd-in-dataset-with-options/UpdateStatus/cluster-scoped/config.openshift.io/featuregates/001-options-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/UPDATE-crd-in-dataset/Update/cluster-scoped/config.openshift.io/featuregates/001-body-new-item.yaml, pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go, pkg/operator/genericoperatorclient/test_operator_client.go, pkg/operator/v1helpers/canonicalize.go
1. adds ability to write recorded mutation requests to disk
2. adds ability to read recorded mutation requests from disk
3. adds ability to compare various mutation requests for equivalence
4. adds test that can record mutation requests to a testdata location.  this tests 1 and we need it for real operators
5. adds test that reads the tesdata location. this tests 2 and 3
6. adds a fake annotation to deletion request bodies so that we know which instance was being deleted
7. adds function to make filenames go.mod friendly
=> API-1835: demonstrate how we will store desired mutations

pkg/operator/apiserver/controller/workload/workload.go, pkg/operator/apiserver/controller/workload/workload_test.go
Proof: https://github.com/openshift/cluster-authentication-operator/pull/715.
Here's a verb usage comparison between **e2e-aws-single-node** jobs of the PR above and https://github.com/openshift/cluster-authentication-operator/pull/705.
/assign @deads2k @p0lyn0mial
=> API-1835: Migrate WorkloadController to SSA

pkg/operator/resource/resourceread/admission.go, pkg/operator/resource/resourceread/admission_test.go
This is required for the [MCO to use ValidatingAdmissionPolicyV1](https://issues.redhat.com/browse/OCPBUGS-43509). We currently use ValidatingAdmissionPolicyV1Beta1 which has been deprecated.
=> OCPBUGS-43509: add resourceread functions for ValidatingAdmissionPolicyV1

pkg/manifestclient/context.go, pkg/manifestclient/context_test.go, pkg/manifestclient/mutation_tracker.go, pkg/manifestclient/write_roundtripper.go, pkg/manifestclienttest/client_write_test.go, pkg/manifestclienttest/testdata/mutation-tests/UPDATE-crd-in-dataset-with-controller-name/Update/cluster-scoped-resources/config.openshift.io/featuregates/001-body-new-item.yaml
requires https://github.com/openshift/library-go/pull/1860
=> API-1835: manifestclient/write_roundtripper: set the controller name in the annotation if specified in the ctx

pkg/manifestclient/readwrite_roundtripper.go
found while testing authentication operator.
=> API-1835: tremendously increase QPS for manifest client to avoid delay

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go, pkg/operator/revisioncontroller/revision_controller.go
Proof: https://github.com/openshift/cluster-authentication-operator/pull/733
/hold
=> API-1825: revisioncontroller: add controller-instance-name label to secrets and configMaps

pkg/operator/staleconditions/remote_stale_conditions_test.go, pkg/operator/staleconditions/remove_stale_conditions.go, pkg/operator/v1helpers/test_helpers.go
Proof: https://github.com/openshift/cluster-authentication-operator/pull/729
Manual testing done:
1. Introduced the removestaleconditions controller in https://github.com/openshift/gcp-pd-csi-driver-operator and marked the **ManagementStateDegraded** condition to be removed.
2. Removed the managementstate controller from the operator.
3. Watched the removestaleconditions controller remove the condition correctly.
4. Added the managementstate controller back to the operator and watched both controller fighting.
=> API-1835: Don't use Update in removestaleconditionscontroller

pkg/manifestclient/mutation_directory_reader.go, pkg/manifestclient/mutation_directory_writer.go, pkg/manifestclient/mutation_tracker.go, pkg/manifestclient/serialized_request.go, pkg/manifestclient/serialized_request_test.go, pkg/manifestclient/write_roundtripper.go, pkg/manifestclienttest/client_write_test.go, pkg/manifestclienttest/testdata/mutation-tests/APPLY-STATUS-crd-in-dataset-with-options/ApplyStatus/cluster-scoped-resources/config.openshift.io/featuregates/001-metadata-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/APPLY-crd-in-dataset/Apply/cluster-scoped-resources/config.openshift.io/featuregates/001-metadata-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/CREATE-crd-in-dataset/Create/cluster-scoped-resources/config.openshift.io/featuregates/001-metadata-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/CREATE-crd-not-in-dataset/Create/cluster-scoped-resources/config.openshift.io/apiservers/001-metadata-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/DELETE-crd-in-dataset/Delete/cluster-scoped-resources/config.openshift.io/featuregates/001-body-cluster.yaml, pkg/manifestclienttest/testdata/mutation-tests/DELETE-crd-in-dataset/Delete/cluster-scoped-resources/config.openshift.io/featuregates/001-metadata-cluster.yaml, pkg/manifestclienttest/testdata/mutation-tests/PATCH-crd-in-dataset/Patch/cluster-scoped-resources/config.openshift.io/featuregates/001-body-instance-name.yaml, pkg/manifestclienttest/testdata/mutation-tests/PATCH-crd-in-dataset/Patch/cluster-scoped-resources/config.openshift.io/featuregates/001-metadata-instance-name.yaml, pkg/manifestclienttest/testdata/mutation-tests/PATCH-crd-in-dataset/PatchStatus/cluster-scoped-resources/config.openshift.io/featuregates/002-body-instance-name.yaml, pkg/manifestclienttest/testdata/mutation-tests/PATCH-crd-in-dataset/PatchStatus/cluster-scoped-resources/config.openshift.io/featuregates/002-metadata-instance-name.yaml, pkg/manifestclienttest/testdata/mutation-tests/UPDATE-STATUS-crd-in-dataset-with-options/UpdateStatus/cluster-scoped-resources/config.openshift.io/featuregates/001-metadata-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/UPDATE-crd-in-dataset-with-controller-name/Update/cluster-scoped-resources/config.openshift.io/featuregates/001-body-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/UPDATE-crd-in-dataset-with-controller-name/Update/cluster-scoped-resources/config.openshift.io/featuregates/001-metadata-new-item.yaml, pkg/manifestclienttest/testdata/mutation-tests/UPDATE-crd-in-dataset/Update/cluster-scoped-resources/config.openshift.io/featuregates/001-metadata-new-item.yaml
Pulls https://github.com/openshift/library-go/pull/1873 and fixes failing unit tests.
=> API-1835: track patches in mutation client

pkg/certs/cert-inspection/certgraphanalysis/analyzer.go
CAs can be stored in a variety of keys. This commits adds more
common used configmap key names for CAs.
Tested in https://github.com/openshift/origin/pull/29170
=> certgraphanalysis: add more locations for CA locations

pkg/operator/apiserver/controller/workload/workload.go, pkg/operator/apiserver/controller/workload/workload_test.go
Deployment rollout should depend on the Deployment Progressing condition
to asses the state of the deployment as there can be unavailable pods
during the deployment. This is capped by a 15 minute deadline. As a result
- Degraded condition should be False during the deployment rollout.
- Progressing condition should be True  during the deployment rollout.
followup for https://github.com/openshift/library-go/pull/1732 
- fixes https://issues.redhat.com//browse/OCPBUGS-23435
- partially fixes https://issues.redhat.com/browse/OCPBUGS-38675
=> OCPBUGS-23435: Fix Progressing and Degraded condition during workload rollouts.

pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go, pkg/operator/deploymentcontroller/deployment_controller.go
This change warns about `reason` and `message` fields in conditions being mandatory in the future: https://github.com/openshift/library-go/pull/1804/files#diff-49fde404f27181b69aea013be73a1439f91fcef3e1c11701f49fe01a5cef6268R351-R356
Causing overhaul of warning messages for controllers that don't set those:
```
W1125 12:50:39.932013   42393 dynamic_operator_client.go:352] .status.conditions["AWSEFSDriverControllerServiceControllerAvailable"].reason is missing; this will eventually be fatal
W1125 12:50:39.932042   42393 dynamic_operator_client.go:355] .status.conditions["AWSEFSDriverControllerServiceControllerAvailable"].message is missing; this will eventually be fatal
W1125 12:50:39.932047   42393 dynamic_operator_client.go:352] …
```
=> OCPBUGS-44374: CSI controller conditions should provide reason and message

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go, pkg/operator/staticpod/controller/node/node_controller.go, pkg/operator/staticpod/controller/node/node_controller_test.go, pkg/operator/staticpod/controllers.go
Per EP: https://github.com/openshift/enhancements/pull/1674
This PR adds a check for arbiter node role to guard and node controller for static pods, this is exposed via a `WithArbiter`  builder function to the static pod builder. This should allow folks to decide if their component is designed for the arbiter or not.
=> OCPEDGE-1309: feat: add arbiter node check

pkg/operator/staticpod/controller/guard/guard_controller.go, pkg/operator/staticpod/controller/guard/guard_controller_test.go, pkg/operator/staticpod/controller/node/node_controller.go, pkg/operator/staticpod/controller/node/node_controller_test.go
while reviewing https://github.com/openshift/library-go/pull/1882 I found that the master nodes selector is being parsed on each `sync` for some controllers.
=> NO-JIRA: operator/node-controller, guard-controller: parse the master node selector during construction

pkg/operator/staticpod/controller/node/node_controller.go
If the operator status retrieved from the lister has not observed the most recent NodeStatus write from the installer controller, the node controller will overwrite it with stale information. This would have returned a 409 and retried using update, but it's now a forced apply. The node controller is only concerned that there exists a node status entry per node and not with their actual statuses.
=> OCPBUGS-46372: Prevent node controller from stomping NodeStatus fields owned by installer controller

pkg/operator/revisioncontroller/revision_controller.go, pkg/operator/revisioncontroller/revision_controller_test.go
This makes the error handling slightly easier, keeps the retry on error logic, leaves the requeue on self-modification we rely upon.
This doesn't introduce VAP to prevent writes to "immutable" configmaps and secrets, but I'm open to doing that to prevent stale caches from creating unstable and inconsistent revisions.
new
```yaml
- apiVersion: operator.openshift.io/v1
fieldsType: FieldsV1
fieldsV1:
f:status:
f:conditions:
k:{"type":"RevisionControllerDegraded"}:
.: {}
f:lastTransitionTime: {}
f:reason: {}
f:status: {}
f:type: {}
manager: RevisionController-reportDegraded
operation: Apply
subresource: status
time: "2025-01-10T20:20:59Z"
- apiVersion: operator.openshift.io/v1
fieldsType: FieldsV1
fieldsV1:
f:status:
f:latestAvailableRevision: {}
manager: kube-apiserver-RevisionController …
```
=> OCPBUGS-48276: Make the revision controller report degraded on error

pkg/operator/apiserver/controller/workload/workload.go, pkg/operator/deploymentcontroller/deployment_controller.go, pkg/operator/v1helpers/helpers.go
Patch deployment controller so it transitions to Degraded=True when it's been in progressing state for 15 minutes or longer.
- this does not provide any hints about what requirement of the controller was not met, this would require further refactoring and using preconditions similar to workload controller - we decided not to address this issue in scope of this bug
- the controller can not set Degraded=True condition directly because it gets immediately [overwritten](https://github.com/openshift/library-go/blob/b06fb9d374b312718c7d28f01c740ebed985a0c5/pkg/controller/factory/base_controller.go#L250) to Degraded=False due to usage of `WithSyncDegradedOnError` so we just return error from sync and let base controller handle it
- we leave CSO running to update storage operator status
Remove …
=> OCPBUGS-24588: degrade when deployment progressing too long

Makefile
Use default timeout and proc count for monitoring test suite.
***
_For https://github.com/openshift/library-go/pull/1823#discussion_r1805273268._
/cc @p0lyn0mial
=> chore: use default timeout and proc count

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
The static pod installer controller builds an apply configuration for the status of the nodes it manages based on potentially-stale state from an informer cache. The controller is written to assume that it has observed the effect of its own previous writes. If the cache is stale, this assumption can be violated which results in unpredictable installation decisions.
A mechanism was recently introduced requiring the installer controller to wait for its lister to catch up to the latest version after performing a write. This mechanism did not work because it depended on keeping state across calls to the Sync method, and because Sync has a value receiver, field writes were not visible on subsequent calls.
=> OCPBUGS-45924: Fix "live get after write" in static pod installer controller.

pkg/operator/certrotation/annotations.go
Some annotation updates may be non-trivial to spot, so we should print which annotation has changed and the diff. It would make spotting hotlooping due to concurrent updates easier to find
=> NO-JIRA: certrotation: print diff when updating annotations

pkg/certs/cert-inspection/certgraphanalysis/certkeypair.go, pkg/certs/cert-inspection/certgraphapi/types.go
This is useful for cluster-debug-tools - https://github.com/vrutkovs/cluster-debug-tools/commit/ac958fff43542cdc5c02bdc04933714cc24465fa specifically. Alongside the time secret was created we also log timestamps when certificate is valid for 
These fields are not exported to JSON to avoid leaking these values to TLS registry exports. Tested in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1785
=> NO-JIRA: certgraphanalysis: save not-before and not-after, don't export to JSON

pkg/operator/resource/resourceread/apiregistration.go
I am tasked with building a KueueOperator for installing upstream kueue into Openshift.
I want to follow an established pattern of having the operator install data in binData. This seems to require reading resources and applying those resources. I noticed that APIServer is not yet a function in resourceread.
Proposing this PR to add this as a function so I can apply APIService from upstream Kueue.
=> [NO-JIRA]: add readApiServerOrDieV1 for kueue-operator work

pkg/operator/deploymentcontroller/deployment_controller.go
Once a deployment takes more than 15 minutes to come up, the owner operator can never get out of the progressing state.
This check was introduced in #1914
However, it is positioned in a way that will never allow a cluster operator to get out of the progressing state, it will always return an error if the deployment has taken too long.
Move the check to occur only when the operator remains in the progressing state. If the operator is exiting the progressing state, then don't do the check.
=> OCPBUGS-51357: Only check deployment time when remaining in Progressing state

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/cabundle_test.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/signer_test.go, pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
There are two copies of this controller running in the cluster: one in the operator with RefreshOnlyWhenExpired=false and one leader in kube-apiserver sidecar with RefreshOnlyWhenExpired=true. This method allows us to generate certs in operator before kube-apiserver pods are created - and regenerate expired certs after the cluster was shutdown.
However, regardless of the mode, this controller applies metadata changes.
So if an update introduces a change in some annotations these controller copies are racing, as there are different versions of the controller running - an updated one in the operator and outdated in kube-apiserver sidecar.
This change ensures that controllers in
RefreshOnlyWhenExpired=true mode don't update metadata. The primary goal is to have certificate contents fresh …
=> OCPBUGS-35102: certrotation: don't update metadata in RefreshOnlyWhenExpired mode

pkg/operator/certrotation/cabundle.go, pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/target.go
Signer/CABundle/Target certcontrollers use informers to fetch updates and may work on outdated versions of the secret/configmap. If update has returned "please apply your changes to the latest version and try again" error the controller should silently skip it, otherwise it will produce multiple duplicate events and operator status updates.
=> OCPBUGS-35102: certrotation: ignore optimistic lock errors

pkg/crypto/crypto.go, pkg/crypto/crypto_test.go
This would help us build certificates with shorter lifetime. Instead of accepting days the functions are updated to accept arbitrary time.Duration. This is necessary for ShortCertRotation featuregate implementation (https://github.com/openshift/service-ca-operator/pull/245)
=> CNTRLPLANE-317: crypto: rework functions to accept time.Duration instead of days

pkg/manifestclient/readwrite_roundtripper.go, pkg/manifestclient/testing/create_test.go, pkg/manifestclient/write_roundtripper.go
added test to validate using the round tripper with the k8s/client-go clientsets
=> OCPEDGE-1693: feat: update client configs for manifestclient

pkg/crypto/crypto.go, pkg/crypto/crypto_test.go
https://github.com/openshift/library-go/pull/1850
enabled TLS 1.3 ciphers.
But CipherSuite lookup functions are
still explicitly failing for TLSv1.3 ciphers.
Let's fix it to avoid the need to filter out
the list on caller side before calling
CipherSuitesOrDie
=> Don't fail on CipherSuites lookup for TLSv1.3 ciphers

pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml, pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml, pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml, pkg/operator/apiserver/audit/testdata/multipleCr.yaml, pkg/operator/apiserver/audit/testdata/oauth.yaml, pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
`MachineConfig` and `ControllerConfig` APIs from the `machineconfiguration.openshift.io` group can contain sensitive data such as pull secrets (in general they contain everything that needs to be written to disk).
This PR excludes these objects from being logged into the audit logs for the `WriteRequestBodies` and `AllRequestBodies` policies.
=> OCPBUGS-52466: Exclude machineconfig and controllerconfig objects from audit logs

pkg/controller/factory/factory.go, pkg/controller/factory/factory_test.go
Adding the same informer several times is useless and has a negative side-effect: a change of object on API-server leads to scheduling reconcile loop several times. Calling reconcile more often than necessary is not great.
=> OCPBUGS-54385: Avoid adding the same informer more than once

pkg/route/validation/validation.go, pkg/route/validation/validation_test.go
Api validation was added to library-go in order to reject any router that is created with a '#' or whitespace in the route spec.path # as this causes HaProxy error and the ingress to become degraded
=> OCPBUGS-47773: Add API validation to reject # or whitespace in spec.path

pkg/operator/certrotation/target.go
this is just a no-op refactoring that renames some functions.
=> operator/certrotation/target: decouple setting annotation from setTargetCertKeyPairSecret into a seperate fn

pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
ROSA Hypershift tests create this secret with a certificate, but its name always starts with a random hash. This option would allow us to replace the variable part so that this certificate could be tracked in TLS registry.
See flaking test ` all registered tls artifacts must have no metadata violation regressions` in [this](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.20-e2e-rosa-sts-hypershift-ovn/1943821536276254720) ROSA test:
```
requirement/ownership: --namespace=openshift-ingress secret/2jvlkpa3d9m62op6t1789pd503rsl9g8-primary-cert-bundle-secret regressed and does not have value set
```
Tested in https://github.com/openshift/origin/pull/29995
=> OCPBUGS-59526: certgraphanalysis: remove hash from primary cert bundle secret

pkg/operator/certrotation/annotations.go, pkg/operator/certrotation/signer.go, pkg/operator/certrotation/target.go
Move testcase name out of auto-regenerate-after-offline-expiry, add
refresh-period.
Follow-up for https://github.com/openshift/origin/pull/29327
Tested in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1768 and https://github.com/openshift/cluster-authentication-operator/pull/742
=> OCPBUGS-57049: Update cert annotations

pkg/operator/resource/resourceapply/storage.go, pkg/operator/resource/resourceapply/storage_test.go
Replaces https://github.com/openshift/library-go/pull/1997
=> [4.17] OCPBUGS-60597: Fix panic in required labels for csidriver object

pkg/operator/v1helpers/informers.go
https://issues.redhat.com/browse/OCPBUGS-54385
New helper `NewKubeInformersForNamespacesWithResyncPeriod()` is useful for operators who want to opt out of automatic per-Informer resync. They will call this helper with zero `resyncInterval` arg.
=> OCPBUGS-54385: Add new helper to informers.go: NewKubeInformersForNamespacesWithResyncPeriod()

pkg/operator/certrotation/target.go, pkg/operator/certrotation/target_test.go
Ensure that we exit early when no refresh is necessary in RefreshOnlyWhenExpired=true mode. This prevents from unnecessary check of CA bundle contents.
Tested in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1905
=> NO-JIRA: needNewTargetCertKeyPair: handle RefreshOnlyWhenExpired

pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/certrotation/client_cert_rotation_controller_test.go
When different controllers update the same CA bundle a conflict may occur. In that case we return an empty set of certificates and empty error.
The sync procedure should exit if either non-empty error received or cabundle is empty, as this ca bundle is later used to detemine whether target cert can be verified. If conflict occurred during CA bundle update we should restart the sync worker again - otherwise this may lead to target certificate unexpectedly regenerated. When service network target certificate is being updated it may be fatal, as the operator will lose its connection to API server and won't be able to receive an updated certificate.
=> OCPBUGS-60045: certrotation: exit when received cabundle is empty
