openshift/library-go

.travis.yml, Makefile, hack/verify-golint.sh
=> Add linter

pkg/operator/resource/resourceapply/rbac.go, pkg/operator/resource/resourcecread/rbac.go
Allows the simple management of RBAC resource for read and merge.
=> manage rbac resources for operator

pkg/operator/resource/resourcemerge/apps.go, pkg/operator/resource/resourcemerge/generic_config_merger.go, pkg/operator/resource/resourcemerge/generic_config_merger_test.go
Adds config merging methods.  Approved as part of https://github.com/openshift/service-serving-cert-signer/pull/18
=> add config merging operator methods

pkg/config/helpers/config_refs.go
Missed a file reference when purging adding new types.
=> add missing file ref

pkg/operator/resource/resourceapply/core.go
=> add ability to copy configmap/secret from another namespace

pkg/operator/resource/resourceapply/generic.go, pkg/operator/resource/resourceapply/generic_test.go
addressing posthumous comments
=> hard fail on failure

OWNERS
@deads2k looks like Jordan missed this one.
=> Remove liggit from approvers & reviewers

pkg/operator/resource/resourceapply/apps.go, pkg/operator/resource/resourcemerge/apps.go
used in https://github.com/openshift/cluster-openshift-apiserver-operator/pull/18
=> support daemonsets for rollout

.travis.yml
=> Update golint download URL

pkg/config/configdefaults/config_default.go
Add default value setters for some additional types.
=> add default value functions

pkg/operator/resource/resourceapply/storage.go, pkg/operator/resource/resourceread/storage.go
=> Add storage to resourceread

glide.lock, pkg/operator/status/controller.go, vendor/github.com/hashicorp/golang-lru/.gitignore, vendor/github.com/hashicorp/golang-lru/2q.go, vendor/github.com/hashicorp/golang-lru/2q_test.go, vendor/github.com/hashicorp/golang-lru/LICENSE, vendor/github.com/hashicorp/golang-lru/README.md, vendor/github.com/hashicorp/golang-lru/arc.go, vendor/github.com/hashicorp/golang-lru/arc_test.go, vendor/github.com/hashicorp/golang-lru/lru.go, vendor/github.com/hashicorp/golang-lru/lru_test.go, vendor/github.com/hashicorp/golang-lru/simplelru/lru.go, vendor/github.com/hashicorp/golang-lru/simplelru/lru_test.go, vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go, vendor/github.com/openshift/api/operator/v1alpha1/types.go, vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go
lifted with comments addressed from https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/20
=> add ClusterOperator status controller

pkg/operator/status/controller.go, pkg/operator/v1alpha1helpers/helpers.go
adds conditions that the CVO expects
=> fix up status reporting conditions

pkg/operator/render/options/config.go, pkg/operator/render/options/generic.go, pkg/operator/render/options/manifest.go, pkg/operator/render/render.go
Example usage in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/53.
=> Add pkg/operator/render as a generic render command

pkg/operator/status/controller.go
=> add zero-diff check to status controller sync method

pkg/operator/resource/resourceread/core.go
needed by static pod management.
@sttts already signed off before, plan to merge on green.
=> add pod handling

pkg/operator/staticpodoperator/installerpod/cmd.go, pkg/operator/staticpodoperator/installerpod/cmd_test.go
Adds the installer pod we're already using in kube-apiserver-operator
/assign @sttts
=> add installer pod command

pkg/operator/staticpod/staticpodcontroller/installer_controller.go, pkg/operator/staticpod/staticpodcontroller/installer_controller_test.go
=> Add multi-node tests and fix some logical errors

pkg/operator/staticpod/staticpodcontroller/deployment_controller.go, pkg/operator/staticpod/staticpodcontroller/deployment_controller_test.go, pkg/operator/staticpod/staticpodcontroller/installer_controller_test.go, pkg/operator/staticpod/staticpodcontroller/node_controller_test.go, pkg/operator/staticpod/staticpodcontroller/test_utils.go
Based on https://github.com/openshift/library-go/pull/66
=> add deployment controller unit tests

pkg/operator/staticpod/installerpod/cmd.go
An alternative approach to https://github.com/openshift/library-go/pull/73
This will add exponential back-off to installer command. In case of failure (API server down/etc.) the command will keep retry for ~2 minutes until it fails.
=> retry copying content in installer command

pkg/operator/staticpod/controller/common/test_utils.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controllers.go
library-go part of https://github.com/openshift/cluster-kube-apiserver-operator/pull/112.
=> staticpod: wait for PodReady condition

pkg/operator/v1staticpod/controller/installer/installer_controller.go
Follow-up of https://github.com/openshift/library-go/pull/89.
=> staticpod: sync installer with v1alpha1 changes

pkg/operator/resource/resourcemerge/apps.go
Generation handling changed in operatorv1 and this updates us to use it.
/assign @sanchezl
=> update generation handling for operator v1

pkg/config/client/client_config.go
/hold
holding until we prove it works.
=> use protobuf when possible

pkg/operator/events/recorder.go
If we are missing an envVar, we should not straight out fail.  Instead we can take a best guess for the owner.
=> tolerate imperfect pod specs

pkg/controller/controllercmd/builder.go, pkg/operator/events/recorder_upstream.go
I tried integrating with openshift-apiserver-operator and spammed events.  This switches the default to the upstream event recorder.
@tnozicka fyi
=> use upstream event recorder

pkg/controller/fileobserver/OWNERS
=> add mfojtik to owners for fileobserver

pkg/operator/resource/resourceapply/event_helpers.go, pkg/operator/resource/resourceapply/event_helpers_test.go
@deads2k @sttts one more fix, this time with unit tests so I can verify the message format...
=> resourceapply: add event helpers unit tests

pkg/operator/resource/resourceapply/apiextensions.go, pkg/operator/resource/resourcemerge/apiextensions.go
=> Add function to apply CRDs

pkg/operator/status/controller.go, pkg/operator/status/controller_test.go
Add events to operator status controllers.
/cc @deads2k
=> events: add events to operator status controller

pkg/operator/resource/resourcehash/as_configmap.go
upstream guts from https://github.com/openshift/cluster-openshift-apiserver-operator/pull/62
=> add functions for finding resource hashes

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
These were lost in the "make status consistent" pull.
/assign @sttts
=> add back available and progressing

glide.yaml, pkg/operator/configobserver/config_observer_controller_test.go
Added unit test to catch accidental upgrade of mergo library.
=> check for incompatible version of mergo

pkg/operator/certrotation/signer.go, pkg/operator/certrotation/target.go
Sets the secret type for rotated certs
=> fix secret types for certs

pkg/operator/resourcesynccontroller/interfaces.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Promotion of https://github.com/openshift/cluster-kube-apiserver-operator/pull/181
=> create a generic resource sync control loop

pkg/operator/staticpod/controller/prune/prune_controller.go, pkg/operator/staticpod/controller/prune/prune_controller_test.go
InProgress revisions will be pruned without this.
/assign @damemi
=> protect unknown status revisions

pkg/operator/status/status_controller.go
clearing the conditions like this loses the last transition time
/assign @mfojtik @sanchezl
=> don't clear status conditions or we get update churn

pkg/operator/resource/resourcehash/as_configmap.go
=> streamline objectref hash

pkg/operator/resource/resourcehash/as_configmap.go
Use listers to compute hashes 
/assign @juanvallejo
=> Reduce qps

pkg/operator/resource/resourcehash/as_configmap.go
This way we can add hashes to our configmaps for optional items.
=> make the hash tolerant of missing items

pkg/operator/status/status_controller.go
@deads2k @sttts guess we don't want this as the field is going away.
=> Revert "status: report cluster operator version"

pkg/operator/v1helpers/core_getters.go
This may be causing lots of weird stuff.
@mfojtik @sanchezl @damemi whoever gets to it first.
=> fix cached getters to return fresh objects to avoid cache mutation

Makefile, alpha-build-machinery/make/lib/golang.mk, alpha-build-machinery/make/targets/golang/verify-update.mk
=> Remove unneeded GO_PACKAGES_EXPANDED

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
This fixes cases where one node goes down and others are good.
@eparis 
=> static pods are available even if they aren't at the latest revision

pkg/operator/staticpod/installerpod/cmd.go
Add debugging info to installer cmd
this is just glog.  Tagging
=> add installer cmd debugging

pkg/operator/staticpod/controller/installer/installer_controller.go
The revision controller should create the `revision-status` configmap before the installer controller creates the installer pod, so we just get that configmap and set the installer pod ownerrefs to the configmap to tie into revision pruning already set up
=> Prune old installer pods

pkg/operator/staticpod/controller/installer/bindata/bindata.go, pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml, pkg/operator/staticpod/controller/prune/bindata/bindata.go, pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
copied from https://github.com/openshift/library-go/pull/209
=> add pruner pod priorityclass and toleration

alpha-build-machinery/make/targets/openshift/deps.mk
/cc @sttts @deads2k @openshift/sig-master
=> Fix diffing symlinks for `make verify-deps`

alpha-build-machinery/scripts/update-deps.sh
=> Fix updating deps for mercurial

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
- do not proceed with other nodes if one node installation fails
- retry on OOM of the installer
=> installer: handle installer failures better

pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
we need to report version updates during updates, not just create.
=> fix version reporting in status controller

pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/resourcesynccontroller/resourcesync_controller_test.go, pkg/operator/v1helpers/core_getters.go
Fixing the scope of client used for resource sync.
=> operator: fix resourcesync controller client scope

pkg/operator/staticpod/controller/revision/revision_controller.go, pkg/operator/status/status_controller.go
This is just fixing debt from before we had an event recorder
=> add events for why a revision happens

pkg/operator/resource/resourceapply/event_helpers.go
=> fix annoying group typo

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Avoid blip to failure=true in operator status when "not-ready" container is found in the static pod. This is usually very short period of time for each container and is not worth signaling failure via operator.
Additionally, only set failure=true when the the container is terminated due to an error (in case of graceful termination because of cert reload or something, don't report failure=true).
/cc @deads2k
=> staticpodstate: do not blip on unready containers and check the termination exit code

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/staticpod/controllers.go, pkg/operator/status/version.go
approved in https://github.com/openshift/cluster-kube-apiserver-operator/pull/262
=> add version setting to static pod management

pkg/operator/staticpod/controllers.go
```go
staticPodController, err = NewBuilder().
WithEvents().
WithInstaller().
WithPruning().
WithVersioning().
ToControllers()
```
/assign @sttts
=> refactor static pod controller building

pkg/operator/configobserver/network/observe_network.go, pkg/operator/configobserver/network/observe_networking_test.go
Get service and cluster networks from `networks.config.openshift.io/cluster` instead of cluster `cm/cluster-config-v1.kube-system`.
=> get network CIDRs from config api

pkg/operator/configobserver/network/observe_network.go, pkg/operator/configobserver/network/observe_networking_test.go
This reverts commit 3debbce95edaad70bff2b66eea70570eabab891a.
I forgot to require the matching pulls in th eoperator repos to prove it.
=> Revert "get network CIDRs from config api"

pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
@soltysh may it never happen again.
=> if an operator is unmanaged, it should change status to unknown

pkg/operator/staticpod/installerpod/cmd.go
Fixes this case: https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/4546
Also switch the installer client to protobuf when fetching secrets/configs.
=> Installer pod fixes

pkg/operator/resource/resourceapply/rbac.go
Hopefully this will make the code more clear and fixes the stoping for good.
=> resource: fix apiGroup defaulting for rolebindings

pkg/operator/staticpod/controllers.go, pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go, pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller_test.go
proven in https://github.com/openshift/cluster-kube-apiserver-operator/pull/304
=> add controller for setting upgradeable conditions to false if unsupprtedConfigOverrides is set

pkg/operator/staticpod/controllers.go
=> start upgradable controller for static pods

pkg/operator/status/condition.go, pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
If there are no conditions to union, you are unknown, not whatever your default is.
=> make no matching conditions result in unknown, not success

pkg/operator/staticpod/certsyncpod/certsync_cmd.go, pkg/operator/staticpod/certsyncpod/certsync_controller.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controllers.go, pkg/operator/staticpod/installerpod/cmd.go
reviewed and tested in https://github.com/openshift/cluster-kube-apiserver-operator/pull/321
=> add ability to separately copy certs

cmd/crd-schema-gen/generator/generator.go
=> Use CRD kind and group as the key

pkg/operator/staticpod/certsyncpod/certsync_cmd.go
Refactors the command to follow other commands structure.
Add file observer that kill the process when the kubeconfig file change.
Start the informer the controller need ;-)
=> certsyncpod: add reloader and fix starting informers

alpha-build-machinery/make/targets/openshift/bindata.mk, alpha-build-machinery/make/targets/openshift/codegen.mk
=> Implicitly hook {verify,update}-generated into {verify,update}

pkg/operator/status/condition.go
=> Concat condition reason to it's type on condition union

pkg/controller/controllercmd/builder.go, pkg/operator/resourcesynccontroller/interfaces.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Adds an http handler to serve resource sync rules info
See https://github.com/openshift/cluster-openshift-apiserver-operator/pull/172
=> Add ResourceSync controller debug endpoint

pkg/operator/resourcesynccontroller/resourcesync_controller.go
=> resourcesynccontroller: use cached get to confirm resource exists before deleting target

pkg/operator/configobserver/featuregates/observe_featuregates.go, pkg/operator/configobserver/featuregates/observe_featuregates_test.go
generic version of https://github.com/openshift/cluster-kube-apiserver-operator/pull/374
/hold 
holding until the first one merges.
=> add generic feature gate observer

pkg/config/client/client_config.go, pkg/config/helpers/client.go
This avoids losing the important wrap transport for in-cluster config. There is more work to collapse the two paths we have.
wait for proof before merging
=> wrap the existing wrap transport to handle 1.13

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
=> Add a common cloudprovider observer

pkg/crypto/crypto.go, pkg/crypto/rotation_test.go, pkg/operator/certrotation/cabundle_test.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
/assign @deads2k 
Requires https://github.com/openshift/release/pull/3418
=> Switch openshift/library-go to go1.11

pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go, pkg/operator/management/management_state_controller.go, pkg/operator/management/management_state_controller_test.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go, pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go, pkg/operator/staticpod/controller/revision/revision_controller.go, pkg/operator/staticpod/controller/revision/revision_controller_test.go, pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
To ensure the union goes well.
=> update all control loops for degraded

pkg/operator/loglevel/logging_controller.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1701272
/cc @deads2k
=> loglevel: fix reporting via events

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controllers.go
for https://bugzilla.redhat.com/show_bug.cgi?id=1702104
This waits for unrevisioned certs to be present before continuing.
/hold
hold for proof and unit tests
=> wait for certs to be present before installing

cmd/crd-schema-gen/generator/generator.go
=> domain is not optional, repo is optional

pkg/operator/status/status_controller.go, pkg/operator/v1helpers/helpers.go
This will help us track how long it takes to indicate that we've achieved the next version.
=> emit specific events for version changes

pkg/operator/staticpod/controller/installer/installer_controller.go
Cleans up error message for https://bugzilla.redhat.com/show_bug.cgi?id=1702930
=>  fix the failing revision counts

pkg/operator/staticpod/controller/revision/revision_controller.go, pkg/operator/staticpod/controller/revision/revision_controller_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1701316
If an operator resource is deleted, it comes back with latest revision number 0 which will cause conflicts with what the actual latest revision is. This uses the revision status configmaps to get the revision history and update the operator status to the actual latest revision number
=> Revision recovery from operator object deletion

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
Cleaner alternative to https://github.com/openshift/library-go/pull/381
/cc @deads2k
=> installer: add revision suffix to required resources

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go
Further code refactoring for @sttts :-)
=> installer: refactor code style for checking required resources

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
Replaces https://github.com/openshift/library-go/pull/389.
=> only acccept cloud config files for certain providers

pkg/operator/staticpod/installerpod/cmd.go
Proof: https://github.com/openshift/cluster-kube-apiserver-operator/pull/455
=> installerpod: save secrets 0600

pkg/operator/certrotation/client_cert_rotation_controller.go
This is needed for cert recovery.
=> expose run-once and wait-for-ready options on cert rotation

pkg/operator/resource/resourceapply/rbac.go
=> Fix copies

pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/condition/condition.go, pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go, pkg/operator/management/management_state_controller.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go, pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go, pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go, pkg/operator/staticpod/controller/revision/revision_controller.go, pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Collect all conditions that are spread across different controller loops and concentrate them in one place with proper godoc.
=> operator/condition: add initial list of condition names

pkg/authorization/authorizationutil/subject.go, pkg/authorization/authorizationutil/util.go
move of pkg/authorization/util  used by CLI, controllers, and apiserver
=> add authorization helper functions

pkg/build/envresolve/env.go, pkg/build/envresolve/kube_copy.go
pkg/pod/envresolve
used by build controllers and CLI.  Copied kube code for k/k deps.
=> add envresolve package

pkg/authentication/bootstrapauthenticator/bootstrap.go
And the openshift-apiserver
This gives us a common spot for it.
=> add bootstrap authenticator which is used by oauth-server and kube-apiserver

pkg/template/OWNERS, pkg/template/generator/doc.go, pkg/template/generator/examples/doc.go, pkg/template/generator/examples/remotevalue.go, pkg/template/generator/examples/remotevalue_test.go, pkg/template/generator/expressionvalue.go, pkg/template/generator/expressionvalue_test.go, pkg/template/generator/generator.go
This moves `pkg/template/generator` from Origin. Used by openshift-apiserver and `oc process`.
/cc @deads2k 
/cc @adambkaplan
=> pkg/template: template generator

pkg/serviceability/logrus.go
=> provide function to init logrus from klog

pkg/config/helpers/readresource.go
this is used in many admission plugins and config reading code.
=> add resource read function to consume bytes

pkg/build/naming/namer.go, pkg/build/naming/namer_test.go, pkg/security/ldapquery/errors.go, pkg/security/ldapquery/query.go, pkg/security/ldapquery/query_test.go, pkg/security/ldapquery/types.go
pkg/api/apihelpers  used by controllers and newapp
/assign @soltysh
=> add name generation methods

pkg/image/imageutil/helpers.go, pkg/image/referencemutator/builds.go, pkg/image/referencemutator/builds_test.go, pkg/image/referencemutator/meta.go, pkg/image/referencemutator/pods.go, pkg/image/referencemutator/pods_test.go, pkg/image/trigger/annotations.go, pkg/image/trigger/annotations_test.go, pkg/image/trigger/interfaces.go, pkg/image/trigger/types.go
This is very small fraction of image helpers that is being shared between apiserver, controllers and oc.
=> Add image utils

pkg/network/networkutils/networkutils.go, pkg/network/networkutils/networkutils_test.go
Move some network utils helpers from origin to here
See https://github.com/openshift/origin/pull/22969
=> Add networkutils package

pkg/quota/clusterquotamapping/clusterquotamapping.go, pkg/quota/clusterquotamapping/clusterquotamapping_test.go, pkg/quota/clusterquotamapping/helpers.go, pkg/quota/clusterquotamapping/mapper.go
used by admission in kas, oas and by the ocm
=> move clusterquotamapping to library-go

pkg/image/imageutil/helpers_test.go
=> Add missing unit test for image utils

pkg/authorization/scopemetadata/clusterrole_describers.go, pkg/authorization/scopemetadata/describers.go, pkg/authorization/scopemetadata/user_describers.go, pkg/authorization/scopemetadata/validation.go, pkg/authorization/scopemetadata/validation_test.go, pkg/config/helpers/readresource.go
=> add writeyaml function

pkg/operator/staticpod/certsyncpod/certsync_cmd.go, pkg/operator/staticpod/certsyncpod/certsync_controller.go
Test PR in https://github.com/openshift/cluster-kube-apiserver-operator/pull/487
/cc @deads2k
=> Bug 1714158: Prevent cert-syncer to act on stale data

pkg/authorization/scopemetadata/user_describers.go, pkg/oauth/oauthserviceaccountclient/oauthclientregistry.go, pkg/oauth/oauthserviceaccountclient/oauthclientregistry_test.go
Shared between OAS and oauth-server.
This is our last shared dep for oauth-server.  Straight move along arc.  Tagging.
=> add serviceaccount oauth client determination

pkg/template/templateprocessing/object.go, pkg/template/templateprocessing/object_test.go, pkg/template/templateprocessing/template.go, pkg/template/templateprocessing/template_test.go, pkg/template/templateprocessing/testdata/guestbook.json, pkg/template/templateprocessing/testdata/guestbook_list.json
=> add template processing to library-go

pkg/security/uid/uid.go, pkg/security/uid/uid_test.go
=> move security uid package for scc

pkg/network/networkutils/networkutils.go
used in oc, controllers, and node stuff
=> add network plugin constants

pkg/image/imageutil/helpers.go, pkg/image/imageutil/helpers_test.go
=> Add image util used by cli and apiserver

pkg/image/imageutil/helpers.go, pkg/image/imageutil/helpers_test.go
=> Add more imageutils shared between oc and importer

pkg/image/imageutil/helpers.go
rebase of https://github.com/openshift/library-go/pull/445/commits
=> image: expose ParseDigest

pkg/image/imageutil/helpers.go, pkg/image/imageutil/helpers_test.go
Image utils used in oc, apiserver and extended tests.
=> Add missing image utils

pkg/image/imageutil/helpers.go
approved via slack with @mfojtik
=> add shared apiserver/controller helpers for builds

pkg/quota/quotautil/error.go, pkg/quota/quotautil/helpers.go
Used by e2e tests and integration.
=> quota: add error helpers and fix package name

pkg/config/validation/serving_info.go, pkg/crypto/crypto.go
=> change intent of ValidTLSVersions()

pkg/apiserver/admission/admissionregistrationtesting/admissiontesting.go, pkg/apiserver/admission/admissionrestconfig/intiializers.go, pkg/apiserver/admission/admissiontimeout/decorator.go, pkg/apiserver/admission/admissiontimeout/timeoutadmission.go, pkg/apiserver/admission/admissiontimeout/timeoutadmission_test.go, pkg/apiserver/apiserverconfig/cachecontrol.go, pkg/apiserver/apiserverconfig/longrunning.go, pkg/apiserver/apiserverconfig/personal_subjectaccessreview.go, pkg/apiserver/apiserverconfig/project_request_info_resolver.go, pkg/apiserver/apiserverconfig/requestinforesolver.go
These are used by OAS, KAS, and oauth-server.
/assign @damemi
=> add apiserver helpers to library-go

alpha-build-machinery/Makefile, alpha-build-machinery/make/examples/multiple-binaries/.gitignore, alpha-build-machinery/make/examples/multiple-binaries/Makefile.test, alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log, alpha-build-machinery/make/examples/multiple-binaries/cmd/oc/main.go, alpha-build-machinery/make/examples/multiple-binaries/pkg/version/version.go, alpha-build-machinery/make/lib/golang.mk, alpha-build-machinery/make/targets/golang/build.mk
=> build-machinery: Add version support

alpha-build-machinery/make/targets/openshift/images.mk
/cc @sttts 
helps us use the targets for rhel images
=> Support extra args for `make images`

pkg/operator/staleconditions/remove_stale_conditions.go
promote https://github.com/openshift/cluster-kube-scheduler-operator/pull/143 to library-go so auth operator can use it.
=> add control loop to remove stale conditions

pkg/operator/staleconditions/remove_stale_conditions.go
we only need the operator client interface, not the static one.
=> use a plain operator client

pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/genericoperatorclient/dynamic_operator_client_test.go, pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
=> Add generic operator client for ease of use

pkg/operator/staleconditions/remove_stale_conditions.go
Signed-off-by: Monis Khan <mkhan@redhat.com>
=>  [release-4.1] Bug 1725936: Add RemoveStaleConditions controller

alpha-build-machinery/Makefile, alpha-build-machinery/make/examples/multiple-binaries/.gitignore, alpha-build-machinery/make/examples/multiple-binaries/Makefile, alpha-build-machinery/make/examples/multiple-binaries/Makefile.test, alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log, alpha-build-machinery/make/lib/golang.mk, alpha-build-machinery/make/targets/golang/build.mk
=> Cross build

alpha-build-machinery/Makefile, alpha-build-machinery/make/default.mk, alpha-build-machinery/make/examples/multiple-binaries/Makefile, alpha-build-machinery/make/examples/multiple-binaries/Makefile.test, alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log, alpha-build-machinery/make/examples/multiple-binaries/ocp.spec, alpha-build-machinery/make/targets/openshift/rpm.mk
=> Add rpm-build

pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/genericoperatorclient/dynamic_operator_client_test.go
Before this, we just used mergo to merge old spec/status with the new value. It had no concept of specified `OperatorSpec/Status` fields and also merged observed configs with mergo. The consequence was that fields were never removed, although the new observed config did not have those fields anymore.
=> Bug 1738432: genericoperatorclient: only preserve fields outside of Operator{Spec,Status}

pkg/operator/staticpod/certsyncpod/certsync_controller.go
=> Emit event when certificate gets updated

pkg/crypto/crypto.go
`pkg/crypto:MakeSelfSignedCAConfig` requires that the subject be supplied as a string. This PR adds an equivalent method that accepts a `pkix.Name` to allow creation of a new self-signed cert for service ca rotation that retains all the subject fields of the previous cert.
This change is in support of https://github.com/openshift/service-ca-operator/pull/73
=> Add pkg/crypto:MakeSelfSignedCAConfigForSubject

alpha-build-machinery/make/targets/openshift/bindata.mk
=> Explicitly disable go.mod for bindata generation

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/json_patch_helpers.go, pkg/operator/staticpod/controller/revision/revision_controller.go
=> Bug 1761280: don't log secret data

alpha-build-machinery/make/examples/multiple-binaries/Makefile, alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log, alpha-build-machinery/make/targets/openshift/controller-gen.mk
=> Use pre-built version of controller-gen

pkg/operator/encryption/controllers/key_controller_test.go, pkg/operator/encryption/controllers/migration_controller_test.go, pkg/operator/encryption/controllers/prune_controller_test.go, pkg/operator/encryption/controllers/state_controller_test.go, pkg/operator/encryption/deployer/staticpod.go, pkg/operator/encryption/testing/helpers.go, pkg/operator/v1helpers/test_helpers.go
Without this, if pods disappear the encryption operator make progress although they should wait for all nodes.
=> encryption: expect pods for all nodes in staticpod operator status

test/library/encryption/assertion.go, test/library/encryption/e_log.go, test/library/encryption/etcd_client.go, test/library/encryption/helpers.go
this code will be used by `kube-apiserver` and `openshift-apiserver`
=> moves e2e encryption code to library-go

pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/key_controller_test.go, pkg/operator/encryption/controllers/prune_controller.go, pkg/operator/encryption/controllers/prune_controller_test.go, pkg/operator/encryption/controllers/state_controller.go, pkg/operator/encryption/controllers/state_controller_test.go, pkg/operator/encryption/testing/helpers.go, pkg/operator/events/eventstesting/recorder_wrapper.go
Copy of https://github.com/openshift/cluster-kube-apiserver-operator/pull/610 that was lost during heavy lifting.
=> encryption: add events to controllers

pkg/controller/metrics/client_metrics.go, pkg/controller/metrics/client_metrics_test.go
Infinite recursion registering client controller metrics.
/cc @deads2k
=> Fix stack overflow with controller metrics

pkg/operator/staticpod/certsyncpod/certsync_controller.go
As reported, the `CertificateRemoved` might cause event spam when the secret is not found permanently. This will reduce the events only to fire when we actually remove the file.
=> Bug 1772190: certsyncpod: reduce amount of events produced by removing files

test/library/encryption/perf_helpers.go, test/library/encryption/perf_scenarios.go
the following scenario will be used by https://github.com/openshift/cluster-openshift-apiserver-operator/pull/261 and https://github.com/openshift/cluster-kube-apiserver-operator/pull/654
=> adds an e2e load test scenario for encryption/migration

pkg/operator/staticpod/controllers.go
Do not run service monitor controller if the builder is not initialized with `WithServiceMonitor()`.
Also deprecate this and remove in next release.
This will also prevent panic in operator when the controller is disabled.
=> staticpod: deprecate service monitor controller

pkg/operator/staticpod/controller/installer/installer_controller.go
I needed a correct message to figure out what state the operator thinks it is in
/assign @sttts
=> bug 1781804: fix revision pending message

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/event_helpers.go
secret types are immutable, so we need to delete and recreate on certain kinds of errors.
/hold
hold for proof.
=> bug 1784052: delete secrets if immutable fields don't match

alpha-build-machinery/make/targets/openshift/deps-gomod.mk
=> build-machinery: Add human readable messages to go mod verify-deps

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go
some configmaps have injected CA bundles.  We don't want to overwrite the well-known ones so that the configmaps can still be applied overall by a simple "make me these resources" list.
/assign @stlaz
=> allow injection of ca bundles

pkg/operator/configobserver/apiserver/observe_cors.go, pkg/operator/configobserver/apiserver/observe_cors_test.go
=> Add observer for APIServer.Spec.AdditionalCORSAllowedOrigins

pkg/operator/configobserver/featuregates/observe_featuregates.go, pkg/operator/configobserver/featuregates/observe_featuregates_test.go
=> make it possible to nerf feature gates if they are broken

pkg/controller/controllercmd/cmd.go, pkg/controller/controllercmd/flags.go, pkg/operator/events/recorder.go
Namespace flag is needed for running the controller locally.
Probably by not setting it I found the seqfault fixed in the other commit.
/cc @deads2k @mfojtik
=> Add namespace flag

pkg/operator/resource/resourceapply/generic.go, pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go, pkg/operator/staticpod/controllers.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
last two commits are unique and auto-adds informers we know about.
=> let the static pod resource controller auto-find the required informers

pkg/operator/apiserver/controllerset/apiservercontrollerset.go
it will be eventually used by workload controller prepared in https://github.com/openshift/cluster-authentication-operator/pull/243
=> adds static-resources-controller to apiserver-controller-set

pkg/operator/staticresourcecontroller/static_resource_controller.go
proof in https://github.com/openshift/cluster-openshift-apiserver-operator/pull/304
=> fix informer typo in static resource controller

pkg/controller/factory/controller_test.go
Rework the shutdown test to use channels instead time.Sleep, make it more reliable and flake prone.
=> controller: deflake controller factory test

pkg/operator/resource/resourcemerge/generic_config_merger.go, pkg/operator/resource/resourcemerge/generic_config_merger_test.go
This is straight promotion out of the kube-apiserver operator.
=> add methods to manipulation observed configuration values

pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/cmd.go
To avoid reaching the serving internal client for delegated auth config map, we need a way to disable it for recovery containers using special SNI endpoint
proof in https://github.com/openshift/cluster-kube-apiserver-operator/pull/768
/cc @deads2k @sttts @soltysh 
=> Bug 1805398: Allow disabling serving in ControllerBuilder

pkg/image/registryclient/client.go
Added support for user provided `transport.RequestModifiers` on registry client. I found out that the code here is duplicated into two other repositories, each one of the with a slightly different feature set.
With this PR we can get rid of the duplicated code on [image-registry](https://github.com/openshift/image-registry/tree/master/pkg/origin-common/image/registryclient).
=> DEVEXP-515: Added support for RequestModifiers.

pkg/security/ldapquery/query.go
=> Bug 1806876: limit number of ldap entries based on its capacity

go.mod, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
Create reusable package for use by CVO and 'oc adm release mirror'
=> Create reusable package to manage manifests for use by CVO and oc

go.mod, pkg/operator/apiserver/controller/workload/workload.go, pkg/operator/apiserver/controller/workload/workload_test.go, pkg/operator/apiserver/controllerset/apiservercontrollerset.go
it will be used by `openshift-apiserver` and `oauth-apiserver`
=> implements a generic workload controller

pkg/controller/factory/base_controller.go, pkg/controller/factory/base_controller_test.go, pkg/controller/factory/controller_context_test.go, pkg/controller/factory/factory.go, pkg/controller/factory/factory_test.go
This covers ~89% factory with unit tests.
=> factory: improve unit test coverage

pkg/operator/configobserver/apiserver/observe_cors.go, pkg/operator/configobserver/apiserver/observe_cors_test.go, pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go, pkg/operator/configobserver/apiserver/observe_tlssecurityprofile_test.go
=> apiserver observers: add switch to observe to apiServerArguments

pkg/operator/encryption/controllers.go, pkg/operator/encryption/controllers/condition_controller.go, pkg/operator/encryption/controllers/controller.go, pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/key_controller_test.go, pkg/operator/encryption/controllers/migration_controller.go, pkg/operator/encryption/controllers/migration_controller_test.go, pkg/operator/encryption/controllers/migrators/inprocess.go, pkg/operator/encryption/controllers/migrators/kubestorageversionmigrator.go, pkg/operator/encryption/controllers/migrators/types.go, pkg/operator/encryption/controllers/prune_controller.go, pkg/operator/encryption/controllers/prune_controller_test.go, pkg/operator/encryption/controllers/state_controller.go, pkg/operator/encryption/controllers/state_controller_test.go, pkg/operator/encryption/deployer/revisionedpod.go, pkg/operator/encryption/deployer/unionrevisionedpod.go, pkg/operator/encryption/deployer/unionrevisionedpod_test.go, pkg/operator/encryption/statemachine/transition.go, test/e2e-encryption/encryption_test.go
This migrates encryption controllers to use controller factory.
=> Migrate encryption controllers to factory

pkg/controller/factory/base_controller.go, pkg/controller/factory/base_controller_test.go, pkg/controller/factory/factory.go
Introduce `WithSyncDegradedOnError(operatorClient)` to factory which in case of `sync()` function return error set the `ControllerNameDegraded` condition automatically (and remove it when the sync does not return any error).
This is useful for simple operator controller loops and minimize the boiler plate in sync() calls. Also David called this idiot-proof :-)
=> factory: add WithSyncDegradedOnError that allows handling degraded for simple sync()

pkg/operator/apiserver/controller/workload/workload.go, pkg/operator/apiserver/controllerset/apiservercontrollerset.go, pkg/operator/encryption/controllers.go, pkg/operator/encryption/controllers/condition_controller.go, pkg/operator/encryption/controllers/controller.go, pkg/operator/encryption/controllers/helpers_test.go, pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/key_controller_test.go, pkg/operator/encryption/controllers/migration_controller.go, pkg/operator/encryption/controllers/migration_controller_test.go, pkg/operator/encryption/controllers/prune_controller.go, pkg/operator/encryption/controllers/prune_controller_test.go, pkg/operator/encryption/controllers/state_controller.go, pkg/operator/encryption/controllers/state_controller_test.go, test/e2e-encryption/encryption_test.go
that abstracts external dependencies and preconditions that need to be dynamic during a downgrade/upgrade
=> adds encryption.Provider 

pkg/operator/staticpod/controllers.go
There is a need in cluster etcd operator to check if it is safe
to install a revision on a node during install time.
Will allow to solve openshift/cluster-etcd-operator#278 with 
something like openshift/cluster-etcd-operator#281
=> add WithCustomInstaller method to Builder interface

test/library/metrics/query.go
This is coming from https://github.com/openshift/cluster-ingress-operator/pull/377
/assign @sttts @mfojtik
=> Bug 1826259: fix ingress CA cert location

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
We repeat the node name in pod name, which makes the events very long for no good reason.
This improves the messages and also make the controller to resync periodically, in case the pod informer is stuck.
This also explains the reason for ` container kube-apiserver is not ready`.
=> staticpodstate: improve condition and event messages

pkg/operator/status/status_controller.go
=> Fix error handling of status controller

pkg/controller/factory/factory.go
In some cases we don't want to add default event handlers to informer, but rather add custom event handlers upon registration of the informer for factory.
/cc @marun
=> factory: add bare informer registration

pkg/operator/staticpod/controller/node/node_controller.go, pkg/operator/staticpod/controller/node/node_controller_test.go
* `MasterNodesReadyChanged` event is never fired since it is at the end of the UpdateStaticPodStatusFunc chain. This issue has been fixed.
* Add defensive guard, if Ready condition is missing then `NodeControllerDegraded` should be set to True.
=> Fix missing event in node controller

go.mod, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
Used to manage manifests for use by CVO and oc.
=> Bug 1837675: Create reusable manifests package

pkg/controller/controllercmd/cmd.go
Needed to resolve https://github.com/openshift/cluster-kube-apiserver-operator/pull/846#discussion_r436199451.
=> allow disabling leader election in ControllerCommandConfig

pkg/controller/factory/base_controller.go, pkg/controller/factory/factory.go
This allow to pass multiple schedules for a single controller:
```
factory.New().ResyncSchedule("every 2s", "every 1d").
```
(realized that for some of our bugzilla reporters we run reports in multiple time zones...)
=> factory: allow multiple scheduled times for sync

pkg/operator/resource/resourceapply/generic.go, pkg/operator/resource/resourceapply/storage.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
=> Handle storage types in staticresourcecontroller

pkg/operator/staticpod/controller/installer/bindata/bindata.go, pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml, pkg/operator/staticpod/controller/prune/bindata/bindata.go, pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
Backporting changes from https://github.com/openshift/library-go/pull/683 and https://github.com/openshift/library-go/pull/707
=> [release-4.3] Bug 1848583: Add resource requests to pruner pod

pkg/operator/staticpod/controller/installer/bindata/bindata.go, pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml, pkg/operator/staticpod/controller/prune/bindata/bindata.go, pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
See https://github.com/openshift/library-go/pull/821
=> [release-4.2] Bug 1799079: Add resource requests to pruner and installer pod

pkg/operator/csi/csicontrollerset/csi_controller_set.go
By the time the inline function is executed  in another goroutine, `controller` is something else already.
=> csi: fix startup of controllers in controllerset

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Adds support for cloud provider configs generated by the cluster-config-operator.
Configobserver should prefer configs generated by the config operator, but fall back
to config listed in infrastructure resource for backwards compatibility.
https://issues.redhat.com/browse/CORS-1483
This has been tested successfully vendoring my personal branch to the kube-controller-manager-operator. 
Before patching KCM-O:
```
$ oc describe cm cloud-config-7 -n openshift-kube-controller-manager
Name:         cloud-config-7
Namespace:    openshift-kube-controller-manager
Labels:       <none>
Annotations:  <none>
Data
====
config:
```
After patching: 
```
$ oc describe cm cloud-config-9 -n openshift-kube-controller-manager
Name:         cloud-config-9
Namespace:    openshift-kube-controller-manager
Labels: …
```
=> configobserver/cloudprovider: support cluster-config-operator

pkg/operator/resource/resourceapply/core.go
just make it work everywhere instead of just a single flow like https://github.com/openshift/library-go/pull/795
=> update ApplySecret to handle StringData

pkg/operator/resource/resourceapply/core.go
fixes a segfault when data is nil and you only have stringData
/cc @deads2k
=> Fix ApplySecret with stringData

pkg/operator/apiserver/controllerset/apiservercontrollerset.go, pkg/operator/secretspruner/prune_controller.go, pkg/operator/secretspruner/prune_controller_test.go
=> Add prune controller to the APIServerControllerSet

pkg/image/dockerv1client/client.go, pkg/image/dockerv1client/client_test.go
Prebase version of https://github.com/openshift/library-go/pull/852
/assign @damemi
=> dockerv1client: fix conversions

pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
need to fix the client initializations
=> fix the static pod operator client

pkg/operator/configobserver/config_observer_controller.go, pkg/operator/configobserver/config_observer_controller_test.go
without this, if there are multiple observers, these would be stepping on each other's toes, trying to set the same condition
/assign @p0lyn0mial
=> prefix nested observer condition to avoid racing

pkg/git/repository.go
Allow git global configurations to be added.
=> Bug 1876913: Add global git configs

pkg/git/repository.go, pkg/git/repository_test.go
- Redact proxy URLs if they contain user credentials.
- Pass empty directory when running git proxy config command.
=> Bug 1876913: Redact proxy urls in git config

pkg/controller/factory/base_controller.go, pkg/controller/factory/base_controller_test.go
Avoid panic on failure to sync caches and just exit.
/cc @mfojtik @deads2k
=> Fix panic in cache sync

pkg/controller/factory/controller_context.go, pkg/controller/factory/controller_context_test.go, pkg/controller/factory/factory.go
The conditional work queue pushing simplifies the logic for
controllers that take a certain resource type but only want to
react to the resource changes when a condition is met,
e.g. an annotation is set to a certain value.
Would be useful at https://github.com/openshift/service-ca-operator/pull/121/files#diff-eec55cf875708a3ee2197838c800c3faR80
=> controller factory: allow conditional queue key add

pkg/operator/v1helpers/informers.go
Need for https://github.com/openshift/cluster-authentication-operator/pull/351#discussion_r490856707
=> v1helpers: add namespaced informer for pods

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
https://github.com/openshift/library-go/pull/880#issuecomment-701202924
=> connectivitycheckcontroller: configurable enabled by default flag

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
When disabled, use the existence of `PodNetworkConnectivityCheck` resources outside of the controller's namespace as a flag to prevent the deletion of the `PodNetworkConnectivityChecks` CRD. This prevents `ConnectivityCheckController` instances opposite enablement flags set from stepping on each other.
=> connectivitycheckcontroller: do not remove crd if checks exist

pkg/operator/apiserver/controller/workload/workload.go
if the APIs are present, the kube-apiserver is up enough.  We don't need the additional check.
=> don't wait on kube-apiserver available

pkg/operator/staticpod/installerpod/cmd.go
We write the static pod yaml separately from the the backup static pod.yaml. This creates one set of bytes for both.  Still written twice though.
/cherrypick release-4.6
=> collapse static pod bytes

pkg/assets/create/testdata/secret-aggregator-client.yaml
=> Use 'kubernetes.io/tls' instead of SecretTypeTLS which is not being substituted

pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
Some operators (e.g. cno) don't know the set of related objects at startup. So, allow that to be dynamically generated.
=> status controller: allow setting RelatedObjects dynamically

pkg/operator/configobserver/etcd/observe_etcd_endpoints.go
I'm planing to use it in https://github.com/openshift/cluster-authentication-operator/pull/386
=> export StorageConfigURLsKey

pkg/operator/apiserver/controller/workload/workload.go, pkg/operator/apiserver/controller/workload/workload_test.go
this PR changes the generic `workload` controller used by `oas-o` and `cao` to set an operator's status to `degraded`, `not available` and `not progressing` when preconditions are not met.
Errors reported from `PreconditionFulfilled() (bool, error)` method will be reported in the `Message` message field, if empty then this will be set to `the operator haven't specified what preconditions are missing`
=> generic workload-controller sets status on preconditions  

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Stop deleting the PodNetworkConnectivityCheck CRD when the controller is "disabled". The network operator will now be responsible for ensuring that the CRD will be available after an install (https://github.com/openshift/cluster-network-operator/pull/898).
=> connectivitycheckcontroller: do not delete crd

pkg/operator/resource/resourceread/admission.go, pkg/operator/resource/resourceread/admission_test.go
Add read functions for ValidatingWebhookConfiguration and MutatingWebhookConfiguration + small smoke-tests.
@sttts @deads2k, PTAL.
=> Add resourceread.ReadValidating/MutatingWebhookConfiguration

pkg/authorization/hardcodedauthorizer/metrics.go, pkg/authorization/hardcodedauthorizer/metrics_test.go, pkg/controller/controllercmd/builder.go
/assign @sttts 
proof in https://github.com/openshift/kubernetes/pull/588
=> add hardcoded authorizers for metrics and token reviews

pkg/operator/apiserver/controller/workload/workload.go, pkg/operator/apiserver/controller/workload/workload_test.go, pkg/operator/apiserver/controllerset/apiservercontrollerset.go
=> use the controllerfactory in the workloadcontroller

pkg/operator/apiserver/audit/bindata/bindata.go, pkg/operator/apiserver/audit/manifests/audit-policies-cm.yaml, pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
Adds the ability to delete oauth tokens to secure default audit policy to capture logouts
=> add the ability to delete oauth tokens

pkg/operator/csi/csicontrollerset/csi_controller_set.go
When informers added to the controllerset with the method `.WithExtraInformers()` are **not started**, the cache-sync operation will wait forever and this message is shown in the log:
>  base_controller.go:66] Waiting for caches to sync for OpenStackCinderDriverControllerServiceController
This PR adds a custom context that will make the sync operation time out after 10 minutes. Once this happens, the following error message will be logged:
> caches did not sync
CC @openshift/storage @Fedosin
=> csi: give informers from controllerset 10 minutes to sync

pkg/image/registryclient/client.go
The scopes on one registry have nothing to do with another, and we
don't want a transport to be chosen when two identical sets of repos
on different registries is used.
If contexts were ever reused across multiple registries, this could
use the wrong tokens.
=> image/registryclient: Cache transports by host, not just by scopes

pkg/operator/resource/resourceread/storage.go
Allow reading storagev1.CSIDiver from manifests.
=> Add CSIDriver v1 resource read

pkg/operator/apiserver/controller/nsfinalizer/finalizer_controller.go, pkg/operator/certrotation/client_cert_rotation_controller.go, pkg/operator/configobserver/config_observer_controller.go, pkg/operator/encryption/controllers/condition_controller.go, pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/migration_controller.go, pkg/operator/encryption/controllers/prune_controller.go, pkg/operator/encryption/controllers/state_controller.go, pkg/operator/management/management_state_controller.go, pkg/operator/resourcesynccontroller/resourcesync_controller.go, pkg/operator/staleconditions/remove_stale_conditions.go, pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, pkg/operator/status/status_controller.go
Looks like someone had a copy/pasta issue and we ended up with tight loops for controllers stealing our qps.
=> fix the tight controller loops someone made

pkg/operator/resource/resourceread/route.go
=> Add ReadRouteV1OrDie helper for reading route from byte object

pkg/config/client/transport.go
`CancelRequest` exists to facilitate the cancellation. In general, there are at least three ways of canceling a request by an HTTP client:
1. Transport.CancelRequest (depreciated)
2. Request.Cancel
3. Request.Context (preferred)
While using client-go callers can specify a timeout value that gets passed directly to an http.Client.
The HTTP client cancels requests to the underlying Transport as if the Request's Context ended.
For compatibility, the Client will also use the deprecated CancelRequest method on Transport if found.
New RoundTripper implementations should use the Request's Context for cancellation instead of implementing CancelRequest.
Because this wrapper might be the first or might be actually wrapped with already existing wrappers that already implement CancelRequest we need …
=> provides CancelRequest method for the PreferredHost RoundTripper to facilitate cancellation

pkg/operator/v1helpers/args.go, pkg/operator/v1helpers/args_test.go
This PR provides convenient functions for dealing with command-line arguments.
=> shell args

pkg/controller/factory/base_controller.go
proof in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1101
=> allow static resource controller to set degraded on panic

pkg/operator/resource/resourceapply/monitoring.go, pkg/operator/resource/resourceapply/unstructured.go
To handle future us adding alerts to our operator.
/hold pending proof
=> add resourceApply for prometheus rule

pkg/operator/resource/resourceapply/unstructured.go, pkg/operator/resource/resourceapply/volumesnapshotclass.go, pkg/operator/resource/resourceapply/volumesnapshotclass_test.go
This commit allows managing VolumeSnapshotClass objects using a dynamic client.
=> Add resourceApply for VolumeSnapshotClass

pkg/operator/staticpod/certsyncpod/certsync_cmd.go, pkg/operator/staticpod/certsyncpod/certsync_controller.go
Follow-up of https://github.com/openshift/library-go/pull/1089.
=> staticpod: fix cert sync controller types to be unrevisioned

pkg/operator/csr/csr_approver.go, pkg/operator/csr/csr_approver_test.go
/assign @deads2k 
----
wip because the unit tests need finishing
=> Bug 1965929: add a CSR approving controller

pkg/operator/csr/csr_approver.go, pkg/operator/csr/csr_approver_test.go
=> csr: fix package name

pkg/controller/factory/eventfilters.go, pkg/operator/csr/csr_approver.go, pkg/operator/csr/csr_approver_test.go
=> csr approver: filter incoming CSRs before entering sync()

pkg/operator/staticpod/controller/installer/bindata/bindata.go, pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml, pkg/operator/staticpod/controller/prune/bindata/bindata.go, pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
=> Bug 1946479: pkg/operator/staticpod/controller/installer,pruner: use manual SA mounts

pkg/operator/csr/csr_approver.go
Add a noop operator client for generic controllers that are a part
of an operand rather than an operator.
=> csr approver: choose between logging and status updates on errors

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
As part of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/525, we need to have methods like the two I have exported here. It was suggested by @soltysh that we just expose these in library-go so that they can be shared.
Notes/Questions:
* Eventually this configobserver will go away/change, all current (known) consumers will eventually just set their flags to external - does this mean there will be deprecation to go through if these are no longer needed?
* Is this the correct package in which to have these methods exported?
* These may eventually be used for cloud config synchronisation which we plan to extract from this observer and integrate directly into the components the need this going forward, this is as of yet unknown
=> [OCPCLOUD-1109] Export CloudProvider configobserver helpers

pkg/operator/staticpod/installerpod/cmd.go, pkg/operator/staticpod/installerpod/cmd_test.go
up until now, the installer pod expected only a single pod manifest in the configmap (the cm is specified by the --pod flag)
since we are planning to add a startup monitor for assessing operand's health check we are extending the installer
to take into account optional keys that might contain other pods.
the new pods will be written to the same locations as the main pod (revisioned, manifests).
the name will be derived from the name filed and suffixed with "-pod.yaml"
xref: https://github.com/openshift/library-go/pull/1130
=> changes the installer-pod to write optional pods

pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
=> staticpod: document installer state controller

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/prune/prune_controller.go
When the startup-monitor marks revision as good, the installer controller is not the right place to update the revision status configmap. It fits better into the prune controller that also consumes it.
=> staticpod: move revision status configmap update to prune controller

pkg/operator/staticpod/controller/startupmonitorcondition/startup_monitor_condition.go, pkg/operator/staticpod/controller/startupmonitorcondition/startup_monitor_condition_test.go, pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition_test.go
xref: openshift/enhancements#833
=> adds startupMonitorPodConditionController for monitoring the lifecycle of the startup monitor pod

pkg/operator/csr/cert_controller.go, pkg/operator/csr/certificate.go, pkg/operator/csr/certificate_test.go, pkg/operator/csr/controller_test.go, pkg/operator/csr/simple_clientcert_controller.go
=> Bug 1978193: fix CSR requester controller possible infinite crashloop and expose cert validation errors

pkg/operator/resource/resourceapply/rbac.go
https://bugzilla.redhat.com/show_bug.cgi?id=1984942
cc @openshift/storage
=> Bug 1984942: ApplyClusterRoleBinding triggers boundsError when adding new subject

pkg/operator/staticpod/controller/installer/installer_controller.go
We want to make progress ASAP in that case, especially not waiting for long fallback backoff.
=> staticpod/installer: skip backoff if lastAvailableRevision > targetRevision

pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go, pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition_test.go
makes testing on an HA cluster easier
=> staticPodFallbackConditionController handles multiple pods returned from the API server

pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition_test.go
The order of pods yields different results, however, the test only
look for one possible outcome.
Instead of complicating the test to deal with all the different
possible returns, we can use a custom podlister that returns
the pods in a deterministic order.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
Tested with 
```
go test -v ./pkg/operator/staticpod/controller/staticpodfallback -run TestStaticPodFallbackConditionController -count 1 -c
$ stress ./staticpodfallback.test 
5s: 4406 runs so far, 0 failures
10s: 8767 runs so far, 0 failures
```
=> deflake TestStaticPodFallbackConditionController

pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
CSI controller pods contain many sidecars, which run leader election with the default setting (timeout after 15 seconds). Replace
`${LEADER_ELECTION_LEASE_DURATION}`, `${LEADER_ELECTION_RENEW_DEADLINE}` and `${LEADER_ELECTION_RETRY_PERIOD}` with correct OpenShift's values to make the sidecars resilient to API server disruption during update.
It's up to an operator to put these placeholders to their yaml files to benefit from this replacement.
This is a prerequisite for https://bugzilla.redhat.com/show_bug.cgi?id=1990662 - we need to update leader election in all CSI driver operators.
=> csi: Replace leader-election parameters

pkg/cloudprovider/external.go, pkg/cloudprovider/external_test.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Adds support for IBMCloud as an external cloud provider.
=> Add IBMCloud to IsCloudProviderExternal

pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
If the controller can't get a Pod from the API, typically because of
network problems of apiserver unavailable, we can't differentiate
if there are no images on the pods or if we couldn't  obtain them.
Only generate the event if we are sure the image was missing.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
=> Bug 2001856: Avoid spurious MissingVersion events on the static pod controller

go.mod, go.sum, vendor/modules.txt
Updating the openshift/client-go libraries.
=> Updating the client-go libraries

pkg/cloudprovider/external.go, pkg/cloudprovider/external_test.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Adding Alibaba cloud platform.
=> Adding Alibaba platform

pkg/operator/staticresourcecontroller/static_resource_controller.go
@ravisantoshgudimetla had a PR very similar to this with some other stuff layered on top.
@ingvagabund had a PR that has a specific implementation of this for PDBs
I think this is a basis for PDB creation on some topologies and not others by using conditionals.
/assign @ingvagabund
=> [poc] add conditional resources to the static resource controller

pkg/image/registryclient/client_mirrored.go, pkg/image/registryclient/client_test.go
ServeBlob uses only the first connected registry, but it does not check
that the registry has needed data. If the blob is absent of this
registry or the registry rejects the request, the client can safely make
another attempt with another registry.
=> Bug 2008539: Try another registry if blob is not found

pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go, pkg/operator/deploymentcontroller/deployment_controller.go, pkg/operator/deploymentcontroller/deployment_controller_test.go, pkg/operator/deploymentcontroller/helpers.go, pkg/operator/deploymentcontroller/helpers_test.go, pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/management/management_state.go, pkg/operator/management/management_state_controller_test.go, pkg/operator/resource/resourceapply/apps.go, pkg/operator/resource/resourceapply/apps_test.go, pkg/operator/resourcesynccontroller/resourcesync_controller_test.go, pkg/operator/v1helpers/helpers.go, pkg/operator/v1helpers/interfaces.go, pkg/operator/v1helpers/test_helpers.go
Backport deploymentcontroller to release-4.8.
=> [release-4.8] Bug 2022844: Extensive number of requests from storage version operator in cluster – Part 3

.ci-operator.yaml
=> Specify build-image in the repository through .ci-operator.yaml

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go, pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go, pkg/operator/resource/resourceapply/generic.go, pkg/operator/resource/resourceapply/generic_test.go, pkg/operator/resource/resourceapply/resource_cache.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
builds on https://github.com/openshift/library-go/pull/1235 to improve code-reuse
=> tweak implementation of resourcecache

pkg/operator/apiserver/controllerset/apiservercontrollerset.go
With introduction of conditional resources in https://github.com/openshift/library-go/pull/1246, `APIServerControllerSet.WithStaticResourcesController` needs to be extended to allow to set the conditional resources as well.
=> APIServerControllerSet: allow to set conditional resources

pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivernodeservicecontroller/helpers.go, pkg/operator/v1helpers/helpers.go
=> csi: add hook to inject custom CA bundle

go.mod, pkg/operator/metricscontroller/legacy_cn_certs_sync.go, pkg/operator/metricscontroller/legacy_cn_certs_sync_test.go, pkg/operator/metricscontroller/metrics_controller.go, vendor/modules.txt
This introduces "metrics controller".
It uses Prometheus to execute queries in regular intervals.
This is a cherry-pick of https://github.com/openshift/library-go/pull/1269.
=> Bug 2037274: metrics controller

pkg/operator/staticresourcecontroller/static_resource_controller.go
https://issues.redhat.com/browse/AUTH-136
This Pull Request introduces requirements into the StaticResourceController required by https://github.com/openshift/cert-manager-operator/pull/29
=> Add precondition to the StaticResourceController

pkg/operator/apiserver/audit/bindata/bindata.go, pkg/operator/apiserver/audit/manifests/base-policy.yaml, pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml, pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml, pkg/operator/apiserver/audit/testdata/default.yaml, pkg/operator/apiserver/audit/testdata/multipleCr.yaml, pkg/operator/apiserver/audit/testdata/none.yaml, pkg/operator/apiserver/audit/testdata/oauth.yaml, pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
KEP: https://github.com/kubernetes/enhancements/pull/2982/files
PR: https://github.com/kubernetes/kubernetes/pull/94986
=> audit: use API to drop managed fields

pkg/operator/metricscontroller/legacy_cn_certs_sync.go, pkg/operator/metricscontroller/legacy_cn_certs_sync_test.go
Currently, NewLegacyCNCertsMetricsSyncFunc cares about a single result from vectors.
By adding support for handling all results from vectors we can enhance status messaging
for better debugability of faulty certificates.
Additionally, this adds a conditionPrefix to support multiple metrics controllers.
=> Bug 2037274: pkg/operator/metricscontroller: add prefix, support vector results

pkg/image/OWNERS, pkg/operator/OWNERS
=> Add dmage and myself for pkg/image approvers, and myself to pkg/operator

pkg/operator/staticpod/installerpod/cmd.go
this resolves the problem of rapid revisions and it resolves the problem about rapid revisions causing overwrite by old revisions..
=> wait for other installers to finish

pkg/operator/staticpod/installerpod/cmd.go
from https://github.com/openshift/library-go/pull/1300#discussion_r795990250
=> add a check for the installer container status to be posted

pkg/operator/staticpod/installerpod/cmd.go
=> [release-4.10] wait for other installers to finish

pkg/image/referencemutator/pods.go
=> Add support for batch/v1 CronJob

pkg/operator/onepodpernodeccontroller/onepodpernode_controller.go
found in CI run https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/720/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws/1509612592396505088/artifacts/e2e-aws/gather-extra/artifacts/pods/openshift-ingress-operator_ingress-operator-697bc657df-wlc2g_ingress-operator_previous.log
=> assign recorder for one pod per node controller

pkg/manifest/manifest_test.go
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>
=> Adding unit tests to cover nil pointer cases of Include()

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
to check if manifest is enabled and to return manifest's capabilities.
=> pkg/manifest: Add methods to support capability implicit enablement

pkg/operator/csi/csicontrollerset/csi_controller_set.go, pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go, pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller_test.go
Backporting [PR#1245](https://github.com/openshift/library-go/pull/1345) to 4.10.
=> [4.10] add storage class controller

pkg/operator/csr/csr_approver.go
https://bugzilla.redhat.com/show_bug.cgi?id=1958198
=> Bug 1958198: Avoid zero resync interval

pkg/operator/status/status_controller.go
=> fix: should judge whether updateErr is nil

OWNERS
=> Add soltysh as approver

pkg/operator/encryption/deployer/revisionedpod.go, pkg/operator/encryption/deployer/revisionedpod_test.go
It turns out that when a node dies or is disconnected from the rest of the cluster, Kubernetes (kubelet) applies a policy for setting the phase of all Pods on the lost node to Failed.
Pods in the Failed state cannot transition back to Running state.
In addition, failed Pods are note GC'ed. The API objects remain in the cluster's API until a human or controller process explicitly removes them.
Thus we need to tolerate pods in Succeeded or Failed phase only if their revision <= the running pods. Otherwise, we won't make any progress.
See the following for more:
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
https://bugzilla.redhat.com/show_bug.cgi?id=2000276
=> Bug 2000276: EncryptionStateControllerDegraded: failed to get converged static pod revision

pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml, pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml, pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml, pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml, pkg/operator/apiserver/audit/testdata/multipleCr.yaml, pkg/operator/apiserver/audit/testdata/oauth.yaml, pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml, pkg/verify/configmap_test.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2073220
=> Bug 2073220: routes/status resources can leak sensitive data

pkg/crypto/crypto.go
While working on microshift, I noticed that this method was missing.
/assign @deads2k 
/cc @ibihim
=> AUTH-296: crypto: add a CA{} method for creating subCAs, too

pkg/operator/staticpod/installerpod/cmd.go
Investigating [trt-589](https://issues.redhat.com//browse/trt-589) found the installer pods stop running due to context timeout.  There is no indication in the captured terminated message indicating where in the run processing things timed out.  This is to add milestone logging to provide more details where the issue might be.
=> Add milestone logging to investigate PodNotReady failures

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
All repos have been updated, stop supporting the old.
/assign @wking
=> update to release.openshift.io/feature-set to match OCP 4.12

pkg/config/serving/server.go
This is a follow up to https://github.com/openshift/library-go/pull/1401.
=> Check for nil pointer before checking connectivity

pkg/operator/staticpod/OWNERS
Add myself and @tkashem to the staticpod library approvers since this code is owned by the API team, but we don't have anyone to approve changes to it.
/cc @tkashem 
=> Add additional approvers to the staticpod library

pkg/crypto/OWNERS
adds /me as the approver/reviewer
cc @deads2k
=> pkg/crypto: add stlaz as approver/reviewer

pkg/assets/assets.go, pkg/assets/assets_test.go, pkg/assets/create/create_test.go, pkg/operator/render/options/generic.go, pkg/operator/render/render.go
- add path to FileInfoPredicate
- add feature-set to generic render options
=> OCPBUGS-3123: add --feature-set option to render options

pkg/template/templateprocessingclient/dynamic_process.go
This reverts commit 0716adf0d71e00d243d835397dee436aa42bc8b8, reversing
changes made to 8d999552212f0e824d070c27c9dcaa5f5f41679d.
=> Revert "Merge pull request #1429 from vrutkovs/revert-1402-master"

pkg/operator/resource/resourceapply/storage.go, pkg/operator/resource/resourceapply/storage_test.go
https://issues.redhat.com/browse/STOR-1055
Enhancement: https://github.com/openshift/enhancements/blob/master/enhancements/storage/csi-inline-vol-security.md
Related PR's:
https://github.com/openshift/kubernetes/pull/1384
https://github.com/openshift/cluster-kube-apiserver-operator/pull/1385
https://github.com/openshift/csi-driver-shared-resource-operator/pull/59
/hold for those 3 PR's to merge first
=> STOR-1055: Add CSIDriver verification check in library-go

pkg/template/templateprocessingclient/dynamic_process.go
=> assign template namespace to default if not set

pkg/operator/configobserver/featuregates/observe_featuregates.go
Needed to cleanly incorporate featuregate handling.
=> expose method for finding featuregates

pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
https://issues.redhat.com/browse/STOR-947
In some cases like https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/126 the operator needs a way to check the StorageClassState first, take some action on it, then apply the SC at the end. This PR refactors the StorageClassStateEvaluator to make it possible to do this while only checking the StorageClassState once per sync.
=> STOR-947: allow separate evaluation of storage class state

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
This extends connectivity check controller's sync function with server side apply so that check objects can be applied directly on the K8s without need for checking existing object fields and calling update function.
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
=> Extend check controller with server side apply

pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
We need this for the vSphere CSI Driver Operator, where there is a different StorageClass controller.
=> STOR-1128: Export code that sets CSI StorageClass as the default one

pkg/security/ldapclient/client.go, pkg/security/ldapquery/query.go, pkg/security/ldapquery/query_test.go
The LDAP querying functions were being misused by calling them in a for loop, which has a potential of generating a needless amount of connection/bind attempts.
Make the user supply an LDAP client with an active connection in order to enforce proper behavior.
/cc @deads2k @ibihim
=> OCPBUGS-7190: ldapquery: expect an LDAP client with an active connection

pkg/operator/configobserver/featuregates/observe_featuregates.go
backport of https://github.com/openshift/library-go/pull/1453
=> [4.12] OCPBUGS-6789: expose method for finding featuregates

pkg/config/leaderelection/leaderelection.go, pkg/controller/controllercmd/builder.go
more info here: https://github.com/kubernetes/kubernetes/issues/107454
=> Use leases for leader election

pkg/controller/controllercmd/cmd.go
to avoid hacking around the webserver lifetime in https://github.com/openshift/cluster-etcd-operator/pull/1049
=> add ability to customize health checks

go.mod, go.sum, vendor/github.com/openshift/api/config/v1/feature_gates.go, vendor/github.com/openshift/api/config/v1/types_feature.go, vendor/modules.txt
update so that the list of featuregates via library-go dep is consistent.
=> update list of featuregates so deps are correctly indexed

pkg/oauth/tokenrequest/challengehandlers/basicauth.go, pkg/oauth/tokenrequest/challengehandlers/basicauth_test.go
=> tokenrequest: fix printing the console URL, add a test

pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
Allow StatusController to remove unknown versions. It's up to the caller to ensure that provided `VersionGetter` has all versions during the first `Sync()`.
Related to https://issues.redhat.com/browse/OCPBUGS-11359
=> Add a flag to StatusController to remove unknown versions

pkg/controller/factory/base_controller.go
found in https://github.com/openshift/library-go/pull/1535#discussion_r1211877928
=> factory/base_controller: properly synchronize runPeriodicalResync function

pkg/features/features.go
discovered while looking at openshift-apiserver.
/assign @thejasn
=> add helpers to make it easy to include openshift featuregates

pkg/operator/staticpod/installerpod/cmd.go
This PR is a manual cherry-pick of these 3 PRs;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546
=> [release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks

pkg/operator/staticpod/installerpod/cmd.go
This PR is a manual cherry-pick of these 3 PRs;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546
=> [release-4.12] OCPBUGS-19837: Update staticpod file permissions to conform with CIS benchmarks

pkg/certs/cert-inspection/certgraphanalysis/analyzer.go, pkg/certs/cert-inspection/certgraphanalysis/ca_bundle.go, pkg/certs/cert-inspection/certgraphanalysis/certkeypair.go, pkg/certs/cert-inspection/certgraphanalysis/collector.go, pkg/certs/cert-inspection/certgraphanalysis/deduplication.go, pkg/certs/cert-inspection/certgraphanalysis/nameguessing.go, pkg/certs/cert-inspection/certgraphapi/types.go, vendor/k8s.io/apimachinery/pkg/util/duration/duration.go, vendor/modules.txt
Needed for cert ownership checking.
=> move code from cluster-debug-tools for reuse in origin

pkg/certs/cert-inspection/certgraphanalysis/nameguessing.go
Follow up for https://github.com/openshift/library-go/pull/1568
=> cert-inspection: update MCO cert name

pkg/certs/cert-inspection/certgraphanalysis/collector.go, pkg/certs/cert-inspection/certgraphanalysis/nameguessing.go, pkg/certs/cert-inspection/certgraphapi/type_registry.go, pkg/certs/cert-inspection/certgraphutils/util.go
This adds few functions used in e2e test (from https://github.com/openshift/origin/pull/28222)
=> cert-inspection: add GatherCertsFromPlatformNamespaces, PKIRegistryInfo

pkg/config/serving/server.go, pkg/controller/controllercmd/builder.go, pkg/controller/controllercmd/cmd.go
backport of https://github.com/openshift/library-go/pull/1587
=> Allow enabling HTTP, the default is off [4.12]

pkg/operator/certrotation/OWNERS
=> pkg/operator/certrotation: add stlaz for review/approve

pkg/certs/cert-inspection/certgraphanalysis/collector.go, pkg/certs/cert-inspection/certgraphanalysis/options.go
=> allow skipping revisioned secrets and configmaps

pkg/certs/cert-inspection/certgraphanalysis/options.go
=> skip revisioned

pkg/operator/staticpod/controller/guard/guard_controller_test.go, pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
This is required to address https://issues.redhat.com/browse/OCPBUGS-22112.
=> guard: add workload partitioning annotation

pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go, pkg/operator/staticpod/installerpod/cmd.go, pkg/operator/staticpod/startupmonitor/cmd.go
=> Fix klog invocations

pkg/certs/cert-inspection/certgraphanalysis/collection_options.go, pkg/certs/cert-inspection/certgraphanalysis/collector.go, pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go, pkg/certs/cert-inspection/certgraphanalysis/options.go
=> add option to rewrite the proxy-ca for reduced size and understanding

pkg/certs/cert-inspection/certgraphanalysis/collection_options.go, pkg/certs/cert-inspection/certgraphanalysis/collector.go
First part of https://github.com/openshift/library-go/pull/1601. Testing in https://github.com/openshift/origin/pull/28378
=> certgraphanalysis: add SkipHashed option

pkg/oauth/tokenrequest/callback_server.go, pkg/oauth/tokenrequest/request_token.go, pkg/oauth/tokenrequest/request_token_test.go
=> [release-4.13] AUTH-443: add support for oauth authorization code flow

pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go, pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller.go, pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller_test.go, pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
=> STOR-1453: CSI: Set TLS ciphers based on observed configuration

pkg/operator/resource/resourceapply/rbac.go
Add support for aggregation rules to `ApplyClusterRole` in `resourceapply`
=> OCPCLOUD-2256: resourceapply: ApplyClusterRole, add support for aggregation rules

pkg/operator/certrotation/client_cert_rotation_controller.go
to fix the following issue: https://github.com/openshift/library-go/pull/1593#discussion_r1399767897
I have found out when bumping library-go https://github.com/openshift/cluster-kube-apiserver-operator/pull/1579 that it is not possible to set the private `conditionName` in StaticPodConditionStatusReporter. 
This solution would also help with the deduplication of the name.
=> make status reporting reuse name of CertRotationController

pkg/operator/revisioncontroller/revision_controller.go, pkg/operator/revisioncontroller/revision_controller_test.go
/hold
until tested through operators:
KS: https://github.com/openshift/cluster-kube-scheduler-operator/pull/514 worked
KCM: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/773#issuecomment-1848898230 worked
=> OCPBUGS-21846: revision_controller: update last revision only when a revision is completely rendered

pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
=> Add option to skip setting cloud-provider=external

pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
Do not emit an OperatorStatusChanged event when the update is a response to a stale challenge request.
=> skip change event on challenge response

pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
https://issues.redhat.com/browse/OCPBUGS-24226
/cc @openshift/storage @stlaz
manual test results here: https://github.com/openshift/csi-operator/pull/76#issuecomment-1853054957
=> OCPBUGS-24226: setting TLSSecurityProfile with no minTLSVersion crashes controller

pkg/crypto/crypto.go, pkg/crypto/crypto_test.go
When testing, it's useful to change what the current time is.
=> HOSTEDCP-1344: pkg/crypto: expose an unsafe self-signed cert generator

pkg/operator/resource/resourceread/config.go
I know I've written it at least twice. Moving here for vendoring other than openshift/api.
=> add featuregate reading and writing

pkg/certs/cert-inspection/certgraphanalysis/certkeypair.go, pkg/certs/cert-inspection/certgraphanalysis/collector.go, pkg/certs/cert-inspection/certgraphanalysis/deduplication.go, pkg/certs/cert-inspection/certgraphanalysis/disk_certs.go, pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go, pkg/certs/cert-inspection/certgraphapi/types.go
Tested in https://github.com/openshift/origin/pull/28444
TODO (can be follow ups):
* selinux labels, permissions
* replace IPs in paths
* keep just the last revision
=> cert-inspect: collect certificates from disk

pkg/certs/cert-inspection/certgraphanalysis/deduplication.go
=> expose combine location cert metadata functions

pkg/operator/configobserver/config_observer_controller_test.go, pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go, pkg/operator/managementstatecontroller/management_state_controller_test.go, pkg/operator/resource/resourceapply/admissionregistration.go, pkg/operator/resource/resourceapply/apiextensions.go, pkg/operator/resource/resourceapply/apiregistration.go, pkg/operator/resource/resourceapply/apps.go, pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/migration.go, pkg/operator/resource/resourceapply/monitoring.go, pkg/operator/resource/resourceapply/policy.go, pkg/operator/resource/resourceapply/rbac.go, pkg/operator/resource/resourceapply/storage.go, pkg/operator/resource/resourceapply/volumesnapshotclass.go, pkg/operator/status/status_controller_test.go, pkg/operator/v1helpers/helpers.go, pkg/operator/v1helpers/interfaces.go, pkg/operator/v1helpers/test_helpers.go
Backporting in order to backport https://github.com/openshift/console-operator/pull/837
/assign @stlaz
=> [release-4.15] When updating status, do a live GET after conflict & Move diff before update to klog v2

pkg/operator/v1helpers/helpers.go
/hold
needs proof prior to merge
/assign @stlaz
=> prefer lister when its resourceVersion is different than the last try

pkg/operator/v1helpers/helpers.go
=> reduce the noise on diffs to on request

pkg/operator/v1helpers/helpers.go
backport of https://github.com/openshift/library-go/pull/1668
/assign @stlaz @jhadvig
=> [4.15] pick for lister reuse

pkg/operator/resource/resourceapply/core.go, pkg/operator/resource/resourceapply/core_test.go
on ConfigMaps where service-ca-operator injects Service CA.
Needed for the https://github.com/openshift/cluster-monitoring-operator/pull/2226 effort where we're trying to migrate towards `resourceapply`'s intelligent utils (I haven't finished estimating the overhead of that intelligence on CMO's CPU and memory) to reduce UPDATE requests and avoid conflicts with the other controllers that we share the resources with.
=> resourceapply: prevent ApplyConfigMapImproved from triggering unnecessary updates

pkg/operator/staticpod/controller/installer/installer_controller.go
Singular if the node count is below 2, plural if more than 1
=> Use correct grammatical form

pkg/operator/certrotation/annotations.go
Use AutoRegenerateAfterOfflineExpiry value, not Description
=> NO-JIRA: certoration: fix a typo when setting AutoRegenerateAfterOfflineExpiry

pkg/features/feature_diff_summary.go, pkg/features/summarizer.go, pkg/markdown/markdown.go
adds analysis for serialized FeatureGates to produce table representations.
=> add featuregate summarization for oc and api

pkg/certs/cert-inspection/certgraphanalysis/disk_certs.go, pkg/certs/cert-inspection/certgraphanalysis/locationmetadata.go, pkg/certs/cert-inspection/certgraphanalysis/locationmetadata_unsupported.go
=> Use syscalls conditionally only for linux

pkg/operator/resource/resourceread/admission.go
/assign @dusk125 
I need this for an e2e test.  It would be good experience in library-go if you tried to create the resourceapply methods and wire into the staticresourcecontroller.
=> add validatingadmissionpolicy reading

pkg/operator/revisioncontroller/revision_controller.go, pkg/operator/revisioncontroller/revision_controller_test.go
Backporting https://github.com/openshift/library-go/pull/1682 to 4.15
=> WRKLDS-1078: Revision controller not found no new revision 4.15

pkg/operator/apiserver/controller/apiservice/apigroup.go, pkg/operator/apiserver/controller/apiservice/apiservice_controller.go, pkg/operator/apiserver/controller/apiservice/apiservice_controller_test.go, pkg/operator/apiserver/controllerset/apiservercontrollerset.go
the proof PR at https://github.com/openshift/cluster-authentication-operator/pull/662
=> OCPBUGS-24195: the apiservice controller waits until bootstrap complete

pkg/operator/resource/resourceapply/admissionregistration.go, pkg/operator/resource/resourceapply/admissionregistration_test.go, pkg/operator/resource/resourceapply/generic.go
Add apply methods for validatingadminssionpolicy and validatingadminssionpolicybinding
=> add validatingadmissionpolicy applying

pkg/certs/cert-inspection/certgraphapi/type_registry.go, pkg/certs/cert-inspection/certgraphutils/util.go
Required for https://github.com/openshift/origin/pull/28551
=> certgraphapi: store ondisk location in PKIRegistryInfo

test/library/metrics/query.go
e2e library code attempts to create a prometheus API client by using a legacy service account API token for the **promethus-k8s** service account. There is no guarantee that a legacy service account API token secret has been created at all, so the TokenRequest API should be used instead to obtain an API token. 
The TokenRequest API time-bounds the generated tokens. I request a token with a 24hr expiration time.
=> OCPBUGS-31589: e2e: use bound API token for prometheus-k8s SA

pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
etcd leaves bootstrap certificates around, which needs to be anonymized in RewriteNodeIPs. This function is extended to accept bootstrap IP, fetched from an annotation in `etcd-endpoints-*` configmap in `openshift-etcd` namespace.
Alternative to https://github.com/openshift/library-go/pull/1723 and https://github.com/openshift/library-go/pull/1717. Tested in https://github.com/openshift/origin/pull/28657
=> cert collection: rewrite bootstrap IP in secret details

pkg/oauth/oauthserviceaccountclient/oauthclientregistry.go, pkg/oauth/oauthserviceaccountclient/oauthclientregistry_test.go
This is a manual cherry-pick of #1686.
=> [release-4.15] OCPBUGS-33210: oauthserviceaccountclient: expect that there might be no tokens associated with SA

pkg/route/validation/validation.go
reduce error message details for Not Found secret
=> OCPBUGS-33574: reduce error message details for Not Found secret

pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go
Replace ${TLS_CIPHER_SUITES} and ${TLS_MIN_VERSION} in node DaemonSet manifests. Re-using functionality that we already have for Deployments.
cc @openshift/storage
=> OCPBUGS-32370: Add TLS config to CSI driver daemonset

pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
Include several ondisk certs in ElideProxyCADetails to mark them as trusted CA bundles
Tested in https://github.com/openshift/origin/pull/28868
=> certgraphanalysis: include ondisk certs in ElideProxyCADetails

pkg/route/OWNERS
Remove inactive, add current teams members.
=> pkg/route: update owners

test/library/junitapi/types.go
=> remove unnecessary comment

pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
=> OCPBUGS-37488: csi: add tools image to csi controller

OWNERS
=> NO-JIRA: Expand approvers for library-go

pkg/features/features.go
This updates `pkg/features` to support adding flags to a flagset, rather than just a cobra flag.
This is useful because in some projects we don't use cobra, e.g MAO and it's operands.
=> OCPCLOUD-2565: Updates features to support adding to FlagSet

go.mod, go.sum, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go, pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go, pkg/operator/deploymentcontroller/deployment_controller.go, pkg/operator/deploymentcontroller/deployment_controller_test.go, pkg/operator/resource/resourcemerge/apps.go, vendor/github.com/openshift/api/config/v1/types_cluster_version.go, vendor/github.com/openshift/api/operator/v1/types.go, vendor/github.com/openshift/client-go/operator/applyconfigurations/internal/internal.go, vendor/modules.txt
This is a follow-up to https://github.com/openshift/library-go/pull/1787 to cover CSI controllers.
Proof: https://github.com/openshift/gcp-pd-csi-driver-operator/pull/128
Here's a plot comparing a job with these changes and a job without these changes:
=> API-1835: use SSA in CSI controllers

pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
This was causing clients to fail to apply status.
=> API-1835: add Kind to static pod operator client creation

pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/v1helpers/canonicalize.go
found this when tightening the type rules to avoid mistakes :(.
/assign @bertinatto @p0lyn0mial
=> API-1835: set the last transition time for conditions

OWNERS, pkg/operator/OWNERS, pkg/operator/csi/OWNERS
=> Add jan as approver

pkg/operator/staticpod/controller/installerstate/installer_state_controller.go, pkg/operator/staticpod/controller/installerstate/installer_state_controller_test.go, pkg/operator/staticpod/controllers.go, pkg/operator/v1helpers/test_helpers.go
proof pr at https://github.com/openshift/cluster-kube-apiserver-operator/pull/1746
=> API-1835: Update the installer state controller to use Apply

pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go, pkg/operator/genericoperatorclient/test_operator_client.go
makes it more practical to start testing with different clients.
=> refactor dynamic client creation and add testing ones

pkg/operator/genericoperatorclient/dynamic_operator_client.go, pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go, pkg/operator/genericoperatorclient/test_operator_client.go, pkg/operator/v1helpers/canonicalize.go
precursor to https://github.com/openshift/library-go/pull/1824
=> API-1835: add clock to client for injection

pkg/apiserver/jsonpatch/jsonpatch.go, pkg/apiserver/jsonpatch/jsonpatch_test.go
proof pr at https://github.com/openshift/origin/pull/29163
=> intro json patch library

Makefile
Add a placeholder Makefile rule to test https://github.com/openshift/release/pull/57664 before adding the actual test in https://github.com/openshift/library-go/pull/1823.
=> Add test-e2e-monitoring placeholder rule

OWNERS
=> add p0lyn0mial to OWNERS

pkg/manifestclient/get.go, pkg/manifestclient/list.go, pkg/manifestclienttest/client_test.go
Needed to feed operators that get, list, watch namespaces.
=> API-1835: add ability to get and list namespaces from must-gather

pkg/operator/staticpod/controller/node/node_controller.go, pkg/operator/staticpod/controller/node/node_controller_test.go
@bertinatto  IOUs from https://github.com/openshift/library-go/pull/1821
=> NO-JIRA: node_controller: change newTargetNodeState assignment and rename to triggerStatusApplyError

pkg/operator/staticpod/controller/node/node_controller_test.go, pkg/operator/v1helpers/test_helpers.go
xref: https://github.com/openshift/library-go/pull/1845
=> NO-JIRA: ability to trigger an err on status apply

pkg/crypto/crypto.go, pkg/operator/configobserver/apiserver/observe_tlssecurityprofile_test.go, pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller_test.go
enable cipher suites previously disabled due to go limitations
=> NO-JIRA: enable TLS 1.3 ciphers

pkg/manifestclient/mutation_directory_reader.go, pkg/manifestclient/mutation_tracker.go, pkg/manifestclient/serialized_request.go, pkg/manifestclient/serialized_request_test.go, pkg/manifestclient/write_roundtripper.go
Found in cluster-authentication-operator
=> API-1835: add generateName for mutation: came up on CSRs

pkg/operator/staticpod/controller/installer/installer_controller.go, pkg/operator/staticpod/controller/installer/installer_controller_test.go, pkg/operator/staticpod/controllers.go
proof pr at https://github.com/openshift/cluster-kube-apiserver-operator/pull/1756
=> API-1835: migrate the installer controller to SSA

pkg/operator/revisioncontroller/revision_controller.go
From failed run: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-4.18-cpou-upgrade-from-4.15-aws-ipi-mini-perm-arm-f14/1842004955238502400
noteworthy log message:
```
2024-10-04T10:05:42.236079365Z E1004 10:05:42.236012       1 runtime.go:79] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
2024-10-04T10:05:42.236079365Z goroutine 2202 [running]:
2024-10-04T10:05:42.236079365Z k8s.io/apimachinery/pkg/util/runtime.logPanic({0x26081a0, 0x3005130})
2024-10-04T10:05:42.236079365Z 	/go/src/github.com/openshift/cluster-authentication-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x7c
2024-10-04T10:05:42.236079365Z …
```
=> OCPBUGS-42932: ensure annotations map exists before mutating it

pkg/operator/apiserver/controllerset/apiservercontrollerset.go, pkg/operator/encryption/controllers.go, pkg/operator/encryption/controllers/condition_controller.go, pkg/operator/encryption/controllers/key_controller.go, pkg/operator/encryption/controllers/migration_controller.go, pkg/operator/encryption/controllers/prune_controller.go, pkg/operator/encryption/controllers/prune_controller_test.go, pkg/operator/encryption/controllers/state_controller.go, pkg/operator/managementstatecontroller/management_state_controller.go, pkg/operator/managementstatecontroller/management_state_controller_test.go, pkg/operator/staticpod/controllers.go, pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Better reviewed commit by commit.
Proof: https://github.com/openshift/cluster-authentication-operator/pull/721
Verb usage comparison between single-node jobs from proof and https://github.com/openshift/cluster-authentication-operator/pull/715:
=> API-1835: Migrate multiple controllers to SSA

pkg/controller/factory/base_controller.go, pkg/controller/factory/factory.go, pkg/operator/staticpod/controller/installerstate/installer_state_controller.go, pkg/operator/staticpod/controller/node/node_controller.go, pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
I will update more controllers in follow-up PRs to use expose the new name.
=> API-1835: staticpod/controllers: expose ControllerInstanceName

pkg/operator/apiserver/controllerset/apiservercontrollerset.go, pkg/operator/encryption/controllers.go
/hold
for proof 
xref: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1762 
xref: https://github.com/openshift/cluster-authentication-operator/pull/736
=> API-1835: expose controllers from the apiserver controllerset

pkg/operator/staticpod/controller/startupmonitorcondition/startup_monitor_condition.go, pkg/operator/staticpod/controllers.go
=> API-1835: migrate startup monitor conditon to ssa

pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go, pkg/operator/staticpod/controllers.go
/hold
for proof (https://github.com/openshift/cluster-kube-apiserver-operator/pull/1765)
=> API-1835: migrate static pod fallback to ssa

pkg/manifestclient/group_resource_discovery.go
=> manifestclient: fix discovery of namespaces

pkg/operator/apiserver/controller/apiservice/apiservice_controller.go, pkg/operator/apiserver/controller/auditpolicy/auditpolicy_controller.go, pkg/operator/apiserver/controllerset/apiservercontrollerset.go
IOU from https://github.com/openshift/library-go/pull/1887#discussion_r1848528007
=> API-1835: operator/apiserver: resync apiservice and auditpolicy controllers every one minute.

pkg/manifestclienttest/client_test.go
=> API-1835: manifestclient: add a few tests for discovery

pkg/manifestclient/group_resource_discovery.go
It seems like we can't reach this code path.
=> API-1835: manifestclient: remove unused discovery code

pkg/apiserver/node/minimum_kubelet_version_test.go
xref: https://github.com/openshift/library-go/pull/1831#discussion_r1853532372
=> NO-JIRA: node/minimim_kubelet_version_test: simplify TestValidateConfigNodeForMinimumKubeletVersion

pkg/operator/csr/csr_approver.go, pkg/operator/csr/csr_approver_test.go
To avoid the necessity of having multiple CSRApproverController instances like in https://github.com/openshift/cluster-policy-controller/commit/1f053433338879160c5a7f471bf5907f3315f08a
And instead be able to do https://github.com/openshift/cluster-policy-controller/pull/148/files instead.
~not really what I need actually, this would require more changes~
=> feat(pkg/operator/csr): add NewServiceAccountMultiSubjectsApprover approver

pkg/operator/v1helpers/helpers.go
added sort func to help make testing easy by having a consistent output for a list of errors
=> NO-JIRA: feat: add sort func for controller errors

pkg/operator/staticpod/controller/installer/installer_controller.go
With the move to SSA, the state machine that used to prevent two installer pods from being scheduled concurrently was broken. Because we don't always have up-to-date information from the lister anymore, we need to make sure that the static pod operator data the controller is getting is up-to-date with the last changes it performed.
=> OCPBUGS-45924: Prevent the installer controller from stomping statuses it just applied

pkg/operator/resource/resourceapply/generic.go, pkg/operator/resource/resourceapply/networking.go, pkg/operator/resource/resourceread/networking.go, pkg/operator/staticresourcecontroller/static_resource_controller.go
Includes informers, appliers and readers.
=> OPRUN-3883: Add NetworkPolicies to the list of resources

pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller.go, pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller_test.go
https://issues.redhat.com/browse/OCPBUGS-58254
/cc @openshift/storage @jsafrane
=> OCPBUGS-58254: CredentialsRequestController: do not sync if the state is not Managed

pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller.go, pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller_test.go
CredentialsRequestController syncs / does not sync its CredentialsRequest based on presence of env. vars for AWS STS or GCE WIF. These env. vars are hardcoded.
Allow the CredentialsRequest to set the env. vars it expects to exist in the CredentialsRequest annotations. So a CSI driver operator (AWS EFS) can have two CredentialsRequest, each synced / not synced based on different env. vars.
=> STOR-2479: Allow CredentialsRequestController to check custom env. vars

pkg/operator/staticpod/controllers.go
An informer for an empty namespace will list resources from all namespaces and cluster level. This may be undesirable, as this make the controller react to events from different namespaces, while we're only interested in cluster-level events. Splitting this into a separate set of informers will prevent that.
Tested in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1874/commits
=> OCPBUGS-59626: staticpodcontroller: require a separate informer for cluster-level events

pkg/operator/certrotation/client_cert_rotation_controller.go
No need to call sync whenever any secret/configmap updates - we should call sync either on timer or when signer/target secret or CA configmap are updated.
Tested as https://github.com/openshift/cluster-kube-apiserver-operator/pull/1890
=> certrotationcontroller: ignore events from other configmaps/secrets
